### ISSUE TITLE
findmnt with duplicate filesystem uuid reports the filesystem once, not twice

### ISSUE THREAD

**Issue by dstromberg** [util-linux/util-linux#1078]
I've written a small program to make copying one partition to another a little safer, and to give a progress bar.  It seems to work, except I'm using findmnt to find what devices correspond to what filesystems (mountpoints), to give the user information about what they may or may not be overwriting.

However, I have a Partial transfer on my system at the moment, and so I have two partitions with the same UUID, but only one actually works.  I'd kind of expect findmnt to list them both under the same mountpoint, or to give an error, but instead it lists the broken partition as the one in fstab:

$ ./'findmnt' '--fstab' '--evaluate' '--json'
below cmd output started 2020 Sun Jun 28 05:41:31 PM PDT
{
   "filesystems": [
      {"target":"/", "source":"/dev/sdb1", "fstype":"ext4", "options":"errors=remount-ro"},
      {"target":"none", "source":"/dev/sdb5", "fstype":"swap", "options":"sw"},
      {"target":"/backshift", "source":"/dev/sdc1", "fstype":"xfs", "options":"auto"}
   ]
}
above cmd output done    2020 Sun Jun 28 05:41:31 PM PDT
dstromberg@zareason-limbo:~/src/util-linux x86_64-unknown-linux-gnu 27432

$ blkid
below cmd output started 2020 Sun Jun 28 05:41:42 PM PDT
/dev/sda1: UUID="38b0733e-530f-4041-bcca-15cbd6f9a4e3" TYPE="xfs" PARTUUID="55f53d44-ad07-4b75-99b0-c0fe0cecd51a"
/dev/sdb1: UUID="025b3743-9063-49dc-b793-1f199757152a" TYPE="ext4" PARTUUID="d94f9846-01"
/dev/sdb5: UUID="ff06f62c-9acf-4f3b-b396-d9d1079b2329" TYPE="swap" PARTUUID="d94f9846-05"
/dev/sdc1: UUID="38b0733e-530f-4041-bcca-15cbd6f9a4e3" TYPE="xfs" PARTUUID="55f53d44-ad07-4b75-99b0-c0fe0cecd51a"

Is there anything that can be done about this?

I'd be willing to put in some elbow grease on it, if folks can guide me to an acceptable approach.

Thanks!

**Comment by dstromberg** [comment]
I perhaps should add: I don't expect findmnt to know what's a usable filesystem and what's not.  I do think it probably should either list both partitions (since they have the same UUID) with the same mount point, or give an error, instead of listing one and silently ignoring the other.  The fact that findmnt's preferring the bad filesystem is most likely just a coincidence.

**Comment by karelzak** [comment]
Well, findmnt(8) follows the way how mount(8) interprets tags (LABELs, UUIDs, ...). It uses udev /dev/disk/by-label/ symlinks to get the device name. If you have duplicates tags than the result is mostly undefined -- (or usually the last probed disk wins).
 
We can add an extra option to print all variants, but it will require root access to the device and probe all devices -- it's definitely anything we do not want to use by default.

**Comment by dstromberg** [comment]
Root access isn't a problem - I'm assuming that already.  And having an option for being exhaustive sounds nice.

**Comment by karelzak** [comment]
Implemented.

I have added a new column "SOURCES" (pl.) rather than an extra option for this purpose. It means:

* SOURCE returns one device only (the "winner" from udev point of view)
* SOURCES returns by multi-line cell (or JSON array) all devices with the same tag

Example (the same UUID from fstab used by two devices):
```
$ findmnt --fstab -oTARGET,SOURCES --evaluate --json UUID=b45897ca-ffc4-4089-8404-5d6072f5aee1
{
   "filesystems": [
      {
         "target": "/mnt/test",
         "sources": [
             "/dev/sdb1", "/dev/sdc"
         ]
      }
   ]
}
```
