### ISSUE TITLE
x-* mount options being dropped

### ISSUE THREAD

**Issue by travisghansen** [util-linux/util-linux#1429]
All but the first `x-*` option is 'forgot' and not stored in utab and therefore cannot be detected by later tooling.

Am I doing something wrong or is this a bug?

**Comment by travisghansen** [comment]
Thanks for the info! Is the fix in any release yet at all?

**Comment by karelzak** [comment]
> Thanks for the info! Is the fix in any release yet at all?

Note yet, I'd like to prepare v2.38 in November.
