### ISSUE TITLE
Reporting test coverage

### ISSUE THREAD

**Issue by masatake** [util-linux/util-linux#1472]
How about introducing [codecov](https://about.codecov.io/) ?

**Comment by evverx** [comment]
I pushed [a follow up commit](https://github.com/evverx/util-linux/commit/8d3ba5cd4202e59c36c197a477aa6b8f43f26334) there to run the tests as root and according to Coveralls  almost half of the code base is covered (as opposed to 35% without that commit).

**Comment by karelzak** [comment]
OK, I have created an account on Coverall, enabled access for util-linux, and merged @evverx PR with github-action for this. We will see :-)

**Comment by evverx** [comment]
Judging by https://coveralls.io/github/util-linux/util-linux it's up and running. I'm not sure where to put [![Coverage Status](https://coveralls.io/repos/github/util-linux/util-linux/badge.svg?branch=master)](https://coveralls.io/github/util-linux/util-linux?branch=master) to make it easier to find those reports though

**Comment by karelzak** [comment]
> I'm not sure where to put to make it easier to find those reports though

Let's use testers discussion page: https://github.com/orgs/util-linux/teams/testers ;-)

**Comment by karelzak** [comment]
Hmm... the "team" pages are visible only for organization members ;-(

**Comment by masatake** [comment]
Thank you very much for setting up coverall.
Putting the badge to README like https://raw.githubusercontent.com/universal-ctags/ctags/master/README.md looks popular way.

For me, knowing the test coverage of my pull request is enough.
It is now solved.
