### ISSUE TITLE
RFE: mkswap has no --quiet parameter

### ISSUE THREAD

**Issue by keszybz** [util-linux/util-linux#1499]
Context: I'm working on file system creation in systemd-repart/systemd-makefs which call `mkfs.{ext2,ext3,ext4,btrfs,swap,…}` to do the actual file system creation. This code is also called by zram-generator, which creates a zram device and then calls mkswap on it.

Other mkfs.foo binaries support --quiet, but mkswap doesn't, so we always get fairly verbose output. For an in-memory block device this is not really useful. Please add --quiet that suppresses all non-error output.

**Comment by karelzak** [comment]
Good idea. Implemented.

**Comment by keszybz** [comment]
Oh, nice, thanks for the quick response.
