### ISSUE TITLE
Bizarre behavior where the `/` parent is inconsistent (testable using `nsenter`)

### ISSUE THREAD

**Issue by otavio** [util-linux/util-linux#1500]
We're trying to understand a bizarre behavior where the `/` parent is inconsistent. We can easily demonstrate it after running a `nsenter` command and issuing a `cat /etc/os-release` we can easily demonstrate it. Considering I am running on an Arch Linux machine, confirmed by:
```console
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
I'm going to open an Ubuntu instance, inside Docker, with:
```console
docker run -it --rm --privileged --pid=host -v /:/host archlinux /bin/sh
```
and inside it use `nsenter` to open a shell inside the host (the Arch Linux in this case). We confirm it using: 
```console
/usr/bin/nsenter -t 1 -a --wd=/host/root /bin/sh
$ echo $PWD
/root
$ cat ../etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

Now, if we go to `/` parent, it's expected to return the same content still, but surprisingly it shows the container rootfs. We confirm this using:
```console 
$ cat ../../etc/os-release
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

But, even more surprisingly, if we force a directory change (using `cd $PWD`), it works. We confirm it is using:
```console
$ cd $PWD
$ cat ../etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
$ cat ../../etc/os-release
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```

We'd like to understand why this different behavior is happening. We are wondering where the bug is? Inside the `nsenter` or Linux Kernel namespace support?

**Comment by karelzak** [comment]
The option --wd is just "cd" and nothing else. The path (--wd=path) is evaluated **before** it calls setns() (it means in original VFS before it changes any namespace, so your working directory is "tunnel" to the original hierarchy of directories :-).

It would be probably better to use ` /bin/pwd -P` and `realpath` to be sure of your location and to avoid env.variables and relative paths. It's also not obvious what is your root directory (findmnt may help).  Something like:

```
# /bin/pwd -P
# findmnt /
# /usr/bin/nsenter -t 1 -a --wd=/host/root /bin/sh
# /bin/pwd -P
# findmnt /
```
Anyway: 
```
nsenter --wd=/host/root /bin/sh    ---> cd /host/root (in meaning before nsenter call)  [arch]
cat ../etc/os-release              ---> [arch]
cat ../../etc/os-release           ---> [ubuntu]
```
I guess this all is correct.

Your --wd is an open file descriptor to the original tree and relative paths are evaluated according to the location (I guess), try the same with absolute paths, I guess you will get a different result.

After `cd $PWD` (cd /root) you move to the host tree (Arch) which is your real root directory. Now there is only /etc/os-release (Arch), and it does not matter how many "../" you will use :-)

So, not a bug from my point of view.

**Comment by otavio** [comment]
@karelzak this is exactly what we found in the `nsenter` source code. We wonder if:

1. it makes sense to change the `--wd` behavior to change the directory after `setns()` is called?
2. add a new option `--nswd` (or similar) to allow it to be used with the expected behavior?

I'd prefer the option (2) but it's up to the maintainers to decide.

**Comment by karelzak** [comment]
> @karelzak this is exactly what we found in the `nsenter` source code. We wonder if:
>     2. add a new option `--nswd` (or similar) to allow it to be used with the expected behavior?

This seems better, but do we really need it? You can use "cd /foo" after nsenter :-)

**Comment by otavio** [comment]
@karelzak, we use it with different applications, and we don't necessarily use a shell. We cannot guarantee a shell will be in use, so 3rdparty provided applications would have a consistent behavior.

**Comment by karelzak** [comment]
OK, I have added --wdns. More details are in the commit message. Please, test it in your use case.

Thanks for your report!
