### ISSUE TITLE
nsenter -a: Don't try entering namespaces that don't exist in the running kernel

### ISSUE THREAD

**Issue by Jongy** [util-linux/util-linux#1502]
`nsenter -a` is very convenient to use, but it must match the kernel version, since as `nsenter` progresses and covers the latest namespaces (such as `ns/time`), old Linux kernels do not support them and using `nsenter -a` in such cases will fail immediately, e.g: `nsenter: cannot open /proc/1/ns/time: No such file or directory`.

I suppose it makes more sense that the `-a` option will automatically skip trying to reassociate namespaces that do not exist? (as in: no `ns/X` file). Just like it avoids calling `setns(CLONE_NEWUSER)` if the target NS matches the current NS, since that's not allowed by Linux.

If you think it makes sense I'll be happy to send a PR fixing it.

**Comment by Jongy** [comment]
This works:
```
diff --git a/sys-utils/nsenter.c b/sys-utils/nsenter.c
index 8eac7800b..a055af702 100644
--- a/sys-utils/nsenter.c
+++ b/sys-utils/nsenter.c
@@ -378,6 +378,12 @@ int main(int argc, char *argv[])
                            && is_same_namespace(getpid(), namespace_target_pid, nsfile->name))
                                continue;
 
+                       char pathbuf[PATH_MAX];
+                       snprintf(pathbuf, sizeof(pathbuf), "/proc/%u/%s", namespace_target_pid, nsfile->name);
+                       struct stat st;
+                       if (stat(pathbuf, &st) != 0 && errno == ENOENT)
+                               continue;
+
                        namespaces |= nsfile->nstype;
                }
        }
```

and maintains the same error behavior that `nsenter` used to give for nonexisting PIDs (the `is_same_namespace` check for the user NS fails)

**Comment by karelzak** [comment]
Good idea. 

Please send PR, but it would be nice to keep it in a separate function, my suggestion is to rename is_same_namespace() to is_usable_namespace() (or so) and check for ENOENT as well as comparison against getpid() there.

**Comment by Jongy** [comment]
Thanks for the quick review @karelzak :)
