### ISSUE TITLE
mount.8.adoc: missing semicolon?

### ISSUE THREAD

**Issue by camoz** [util-linux/util-linux#1539]
Hi, in https://github.com/util-linux/util-linux/blob/master/sys-utils/mount.8.adoc I think there is a semicolon or line break missing:

> The alternative (classic) way to create a read-only bind mount is to use the remount operation, for example:
>
>  `mount --bind olddir newdir mount -o remount,bind,ro olddir newdir`

Not creating a PR myself since I'm not familiar with the adoc syntax.

**Comment by karelzak** [comment]
Thanks for your report!
