### ISSUE TITLE
more - reading quit character should immediately return that command

### ISSUE THREAD

**Issue by anya-evergreen** [util-linux/util-linux#1540]
In older releases of util-linux/text-utils/more.c, when the command 'q' or 'Q' was received, the program would immediately terminate.

Now we have a command parsing loop, which parses all the input before returning.

I'm automating something which sits on top of more, and sends 'q\n'

This is consumed in a single read operation, and the way the parsing operates, this causes:

see a 'q' -> set the key to 'quit'
see a '\n' -> set the key to 'go to next line'

returns 'go to next line', ignores 'quit'. Hilarity ensues as all my expect driven code fails because more didn't exit.

I've a one-line fix.

**Comment by anya-evergreen** [comment]
Commit for the change - https://github.com/anya-evergreen/util-linux/commit/bf3e1c789337f65575fb2e2c6969e080e16e8c3c

**Comment by karelzak** [comment]
Fixed by submmited patch. Thanks.
