### ISSUE TITLE
fdisk: first LBA

### ISSUE THREAD

**Issue by musinsky** [util-linux/util-linux#1554]
```
# rpm -qf $(which fdisk)
util-linux-2.37.2-1.fc35.x86_64
```

existing "standard" GPT (first LBA start from 34)
```
# fdisk -x /dev/nvme0n1
Disk /dev/nvme0n1: 476.94 GiB, 512110190592 bytes, 1000215216 sectors
Disk model: SSDPEMKF512G8 NVMe INTEL 512GB
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 1DC144BD-733C-4AAA-9CCC-D3C9C9EFC612
First LBA: 34
Last LBA: 1000215182
Alternative LBA: 1000215215
Partition entries LBA: 2
Allocated partition entries: 128

```
now create a new empty GPT partition table with fdisk
```
# fdisk -x /dev/nvme0n1
Disk /dev/nvme0n1: 476.94 GiB, 512110190592 bytes, 1000215216 sectors
Disk model: SSDPEMKF512G8 NVMe INTEL 512GB
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 0572F142-AB4B-724D-B59E-6F17B371216A
First LBA: 2048
Last LBA: 1000215182
Alternative LBA: 1000215215
Partition entries LBA: 2
Allocated partition entries: 128
```
1. why first LBA start from 2048 ?
2. how create new GPT with first LBA 34 ?

**Comment by karelzak** [comment]
1 MiB offset (=2048 512-byte sectors) is the default layout used by all partitioning tools in the last years. It's used to have the same layout for all usual use-cases and block devices. 1 MiB works fine with 4K devices, RAIDs, etc. 1 MiB granularity is also an elegant way how to align partitions.

If you don't like this default then you have to use sfdisk or create a sfdisk-like script and load it to fdisk (command 'I'). Unfortunately, fdisk does not have any user-friendly interface to change it.

```
# cat /root/a
label: GPT
first-lba: 34

# fdisk /dev/sdc
...
Command (m for help): I
Enter script file name: /root/a

Created a new GPT disklabel (GUID: 60B65FA7-914D-8242-8621-A32F423F8FB9).
Script successfully applied.

Command (m for help): x
Expert command (m for help): p
...
Disklabel type: gpt
Disk identifier: 60B65FA7-914D-8242-8621-A32F423F8FB9
First LBA: 34
...
```
Or just:
```
# echo -e "label: GPT\nfirst-lba: 34\n" |  sfdisk /dev/sdc
```

**Comment by musinsky** [comment]
> 1 MiB offset (=2048 512-byte sectors) is the default layout used by all partitioning tools in the last years.

Yes of course, but first LBA is first **[usable](https://github.com/util-linux/util-linux/blob/47831cc02ac0d71c335caecef1753f4c8861277c/libfdisk/src/gpt.c#L113)** LBA (not first "recommended" or  first "aligned" LBA).
Other tools create new GPT with first LBA 34. **UEFI specfication** to same, please see [page 121](https://uefi.org/sites/default/files/resources/UEFI_Spec_2_9_2021_03_18.pdf).

**Comment by karelzak** [comment]
The First and Last LBA define the area where is possible to create partitions, if we want the first partition at 1MiB offset then it makes sense to use it for FirstLBA too. Why does it make sense to define the area from sector 34 and after that keep the gap between sectors 34 and  2048 always empty (for usual use-cases)?

And if the area will be from sector 34 then tools will offer the gap for use (for new partitions) or they need an extra exception
to skip it, seems pretty inelegant. Yes, GNU Parted does it, but I don't see it usable if there is consensus that the first partition should be at 1MiB offset.

Sector 34 also means only 128 partitions although there is usually an unused area to allocate more partitions.

Again, it's libfdisk default and you can change it if you do not like it. IMHO it's better and more robust than the gap.

**Comment by musinsky** [comment]
Yes, your logic is understandable. Anyway, the same first LBA=2048 for 512-byte sector drive and 4K drive is very confusing for me (yes, is correct for create partition, but confusing with UEFI specfication term First **Usable** LBA).

Summarum: first LBA in fdisk = first LBA where is possible to create partition ≠ first LBA after primary GPT ?

**Comment by karelzak** [comment]
>  Anyway, the same first LBA=2048 for 512-byte sector drive and 4K drive is very confusing for me 

The offset depends on optimal I/O and logical sector size. If you have 4K with a 512-byte logical sector then it's still 2048 (logical) sectors. If you have a 4K disk with 4K logical sector then it will be probably aligned to 4MiB offset, because
optimal I/O size is 4MIB for the device. 

See https://github.com/util-linux/util-linux/blob/master/libfdisk/src/alignment.c#L609

> Summarum: first LBA in fdisk = first LBA where is possible to create partition ≠ first LBA after primary GPT ?

Yes. We need to use "First Unable LBA" in the `fdisk -x` output to make it more readable :-)

**Comment by musinsky** [comment]
What about (see page 125-126 in UEFI 2.9 specification) ?
current version:
```
First usable LBA: 2048
Partition entries LBA: 2
Allocated partition entries: 128
```
new version (example for 512-byte logical sector)
```
First usable LBA: 2048
Partition entries starting LBA: 2
Partition entries ending LBA: 33
Allocated partition entries: 128
```

**Comment by karelzak** [comment]
Implemented.
```
# fdisk -x /dev/sdc
Disk /dev/sdc: 500 MiB, 524288000 bytes, 1024000 sectors
Disk model: scsi_debug      
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 524288 bytes
Disklabel type: gpt
Disk identifier: D93DB84C-A430-BB4D-AD6A-826435251FFB
First usable LBA: 2048
Last usable LBA: 1023966
Alternative LBA: 1023999
Partition entries starting LBA: 2
Allocated partition entries: 128
Partition entries ending LBA: 33
```

**Comment by musinsky** [comment]
Perfect, thanks !
