### ISSUE TITLE
lsblk ( 'man' pages| Unknown observed convention in regard to multiple-byte units

### ISSUE THREAD

**Issue by Ricky-Tigg** [util-linux/util-linux#1572]
util-linux v. 2.37.2 | lsblk | `man`-page (updated 2021-08-16)

Hello. As noticeable in that user guide, unknown is the **observed convention** chosen to express sizes by default; for instance according to SI (power of **10^3**) or IEC (power of **2^10**), in **bit** / **bytes**. It would be worth a mention. _Suggested model_:

"_By default sizes are expressed in power of 10^3 / 2^10, in bit / bytes, a human-readable format._"

**Comment by karelzak** [comment]
Good point. What about:

`By default, sizes are expressed in bytes, in the power of 2 followed by the multiplicative suffix (but without "iB"; K, M or G means KiB, MiB or GiB, etc.).`

**Comment by Ricky-Tigg** [comment]
After reading it carefully, iI concluded that a correct interpretation could most probably lead to understand that _2_ alone is the value of the **base** that governs the prefix, therefore not the expected _2¹⁰_ which is _1024_. A value of _2_ as **base** would suggest that it is the SI standard that applies, and therefore prefixes of _10³_. So what about:

_By default, sizes are expressed in bytes and according to the ISO/IEC standards, then with unit prefixes in power of 2^10 (1024). Abbreviations are on purpose exhibitied truncated in order to reach a better readability, by exhibiting the first letter of them alone; examples: KiB and MiB would be respectively exhibited as K and M, then without the mention "iB", as part of these abbreviations._

**Comment by Ricky-Tigg** [comment]
After reading it carefully, iI concluded that a correct interpretation could most probably lead to understand that _2_ alone is the value of the **base** that governs the prefix, therefore not the expected _2¹⁰_ which is _1024_. So what about that:

_By default, sizes are expressed in bytes and with unit prefixes in power of 2^10 (1024). Abbreviations are on purpose exhibited truncated in order to reach a better readability, by exhibiting alone the first letter of them; examples: KiB and MiB are to be exhibited respectively as K and M, then without the mention "iB", which is part of these abbreviations._

**Comment by Ricky-Tigg** [comment]
A correct interpretation leads to understand that _2_ alone is the value of the **base** as part of that model:  b^n


  that governs the prefix, therefore not the expected _2¹⁰_ which is _1024_. So what about that:

_By default, sizes are expressed in byte unit and unit prefixes in power of 2^10 (1024). Abbreviations are on purpose exhibited truncated in order to reach a better readability, by exhibiting alone the first letter of them; examples: KiB and MiB are to be exhibited respectively as K and M, then without the mention "iB", which is part of these abbreviations._

**Comment by Ricky-Tigg** [comment]
A correct interpretation of "_in the power of 2 followed by the multiplicative suffix_" leads to understand that in the context of the function _b_^_n_, with _b_ as **base** and _n_ as **exponent**,  _2_, alone, is the value for _b_, while it is expected to be _2¹⁰_ which is _1024_. Be _m_ that "_multiplicative suffix_" you mentioned, unknown would be its location as part of that function. Unknown as well would be the function the prefixes obey to. _New suggestion_:
2^n
_By default, the unit sizes are expressed in, is byte, and unit prefixes in power of 2^10 (1024). Symbol abbreviations are exhibited truncated in order to reach a better readability, by exhibiting alone the first letter of them; examples: KiB and MiB are to be exhibited respectively as K and M, then omitting on purpose the mention "iB", which is part of these abbreviations._

**Comment by Ricky-Tigg** [comment]
A correct interpretation of "_in the power of 2 followed by the multiplicative suffix_" leads to understand that in the context of the function _b_^_n_, with _b_ as **base** and _n_ as **exponent**,  _2_, alone, is the value for _b_, while it is expected to be _2¹⁰_ which is _1024_. Be _m_ that "_multiplicative suffix_" you mentioned, unknown is its location as part of that function and then unknown as well is the function the prefixes obey to. _New suggestion_:

_By default, the unit sizes are expressed in, is byte, and unit prefixes are in power of 2^10 (1024). Abbreviations of symbols are exhibited truncated in order to reach a better readability, by exhibiting alone the first letter of them; examples: "1 KiB" and "1 MiB" are respectively exhibited as "1 K" and "1 M", then omitting on purpose the mention "iB", which is part of these abbreviations._

**Comment by Ricky-Tigg** [comment]
A correct interpretation of "_in the power of 2 followed by the multiplicative suffix_" leads to understand that in the context of the function _b_^_n_, with _b_ as **base** and _n_ as **exponent**,  _2_, alone, is the value for _b_, while it is expected to be _2¹⁰_ which is _1024_. Be _m_ that "_multiplicative suffix_" you mentioned, unknown is its location as part of that function and then unknown as well is the function the prefixes obey to. _New suggestion_:

_By default, the unit, sizes are expressed in, is byte, and unit prefixes are in power of 2^10 (1024). Abbreviations of symbols are exhibited truncated in order to reach a better readability, by exhibiting alone the first letter of them; examples: "1 KiB" and "1 MiB" are respectively exhibited as "1 K" and "1 M", then omitting on purpose the mention "iB", which is part of these abbreviations._
