### ISSUE TITLE
Ignore passno for btrfs fs

### ISSUE THREAD

**Issue by Githob2021** [util-linux/util-linux#1575]
When running this command on a btrfs system:
```
sudo findmnt --verify
```
to see if everything is up to snuff in fstab, it says
```
[W] recommended root FS passno is 1 (current is 0)
```
However, according to
https://forum.endeavouros.com/t/recommended-root-fs-passno-is-1-current-is-0/22555
for btrfs fs you don't need passno to be 1.
"Traditional filesystems need to run their respective fsck utility in case the filesystem was not unmounted cleanly and the log needs to be replayed before mount. This is not needed for btrfs. You should set fs_passno to 0. https://btrfs.wiki.kernel.org/index.php/FAQ#When_will_Btrfs_have_a_fsck_like_tool.3F"

It seems a change was also made to the XFS fs to fix the defaults. Can the same be implemented for btrfs please? In which case when running sudo findmnt --verify there would be no warning when using btrfs for passno = 0.

XFS change: https://github.com/util-linux/util-linux/commit/f5b7bf155b9881de5b99cc0a23b4dccf9a2d4af3
https://bugzilla.redhat.com/show_bug.cgi?id=1719069

**Comment by karelzak** [comment]
Good catch. Thanks!
