### ISSUE TITLE
Latest release (v2.37.3) doesn't know about Haiku partitions

### ISSUE THREAD

**Issue by kallisti5** [util-linux/util-linux#1585]
Just noticed the latest release of v2.37.3 isn't aware of the GUID for Haiku partitions?

Looks like code was committed to master almost a year ago for it?
https://github.com/util-linux/util-linux/commit/28d6722d930566429f9f371c05ca7101b9af3b36

**Comment by karelzak** [comment]
Yes, this is expected.  v2.37.x contains only bugfixes from the master and v2.37.3 is about security bugfixes only. 

The change you're asking for will be in v2.38, my plan is to prepare v2.38-rc1 next week (original plan was at beginning of January).
