### ISSUE TITLE
findmnt --verify incorrectly errors with glusterfs volumes

### ISSUE THREAD

**Issue by scyto** [util-linux/util-linux#1590]
I have a gluster volume mounted via fstab using
```
#mount glusterfs volume
docker01.mydomain.com:/gluster-vol1  /mnt/gluster-vol1 glusterfs  defaults,_netdev        0 0
```
this mounts just fine with the mount comand etc

however findmnt --verify errors like so

```
/mnt/gluster-vol1
   [W] unreachable source: docker01.mydomain.com:/gluster-vol1: No such file or directory
   [W] glusterfs seems unsupported by the current kernel
   [W] cannot detect on-disk filesystem type
```

would be nice if findmnt could verify OR didnt return invalid errors and just say glusterfs not supported by findmnt
i am using current debian buster stable packages that includes glusterfs

**Comment by karelzak** [comment]
Thanks for your report, the problem should be fixed now.
