### ISSUE TITLE
lsblk: --pairs output is not backward compatible after 58b510e

### ISSUE THREAD

**Issue by matthewruffell** [util-linux/util-linux#1594]
Dear util-linux maintainers,

I know this happened a long time ago, but I would like to discuss the impact of the move to having lsblk -P / --pairs output column names that are parsable by shells as it created some significant backward compatibility challenges.

This happened in #1201 and landed in 58b510e.

I understand that users should not be blindly using default commands like -P in their scripts, and that the output is subject to change to change at any time, as mentioned by your manpage:

```
The default output, as well as the default output from options like --fs and --topology, is subject to change. So
whenever possible, you should avoid using default outputs in your scripts. Always explicitly define expected columns by
using --output columns-list and --list in environments where a stable output is required.
```

For better or worse, -P *is* widely used in scripts, and it also mirrors the functionality of -J, just presented in a different format.

I know of two projects, Curtin, and MAAS, that were relying on -P in scripts that were broken by the change. They have both been changed to rely on -J:

MAAS: https://git.launchpad.net/maas/commit/?id=e2c01963430e6837198a54bc1eadf3efc9fdd9a2
Curtin: https://github.com/canonical/curtin/commit/ce811db127fe1ce46498b83615f8faed8c7dfeb6

Users now find that their column names are different and inconsistent between -P and -J, ranging from trivial renames like LOG-SEC becoming LOG_SEC, to larger changes like FSUSE% to FSUSE_PCT.

Can I propose that we restore the initial behaviour of -P to use their proper column names, like LOG-SEC, for maximum backward compatibility, and we add a new flag, such as:

```
-y --shell Used with --pairs to produce shell parsable output. The key (variable name) will be modified to contain only
           characters allowed for a shell variable identifiers, for example, MIN_IO and FSUSE_PCT instead of MIN-IO and FSUSE%.
```

The single letter choice is arbitrary, and can be substituted for another.

I am happy to write and submit a patch for this. The change in 58b510e is nicely wrapped up in its own function, fputs_shell_ident(), so we can add the command line switch easily with something like:

```
libsmartcols/src/print.c
-----------------------------------------
case SCOLS_FMT_EXPORT:
    if cmdline_shell_output {
        fputs_shell_ident(name, tb->out);
	if (endswith(name, "%"))
	    fputs("PCT", tb->out);
	fputc('=', tb->out);
    } else {
    	fprintf(tb->out, "%s=", name);
    }
```

and we just link up `cmdline_shell_output` to -y and --shell. 

Are you interested?

Thanks,
Matthew

**Comment by karelzak** [comment]
The behavior has been modified in v2.37, now we working on v2.38, so it's not so horrible. And people who already use (for example) lsblk in shell scripts probably do not use it with the column names which are not shell compatible, so they are not affected by the change in v2.37. I guess it's relatively safe to revert the change and implement it in another way. 

It will not be so simple as `if cmdline_shell_output`, we need to add some interface to libsmartcols to control this behavior. Probably add a new function scols_table_sanitize_colnames() or so. I'll implement it ...

Maybe the behavior should be independent of -P / --pairs, which means always when you use -y/--shell it will modify the column names independently on the output format. What do you think?

**Comment by matthewruffell** [comment]
Yes, I think making -y/--shell independent of -P/--pairs is the sensible thing to do. 

I think the current inconsistency with -P and -J having different column names is not ideal, and being able to set them both to always have the same column names, and using -y/--shell to toggle them, is a good thing.

Thank you for offering to implement it in libsmartcols. I'm happy to test any patches before you merge.
