### ISSUE TITLE
mkostemp: support check in entire source 

### ISSUE THREAD

**Issue by dharanlinux** [util-linux/util-linux#1596]
Hi Team,

    The below commit provide the fallback if mkostemp(3) missing in lib and libblkid directory.
https://github.com/util-linux/util-linux/commit/4d751c008e7c893c30eb7c9b04b21756ca806b67

But the mkostemp function call is available in other places too. Why we didn't provide the same fix to entire source directory.

Ex:
```
./util-linux-2.37.3/libmount/src/utils.c:925:	fd = mkostemp(n, O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC);
./util-linux-2.37.3/login-utils/last.c:942:	fd = mkostemp(name, O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC);
./util-linux-2.37.3/login-utils/last.c:944:		err(EXIT_FAILURE, "mkostemp() failed");
./util-linux-2.37.3/libfdisk/src/script.c:1537:	fd = mkostemp(name, O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC);
./util-linux-2.37.3/libfdisk/src/script.c:1539:		err(EXIT_FAILURE, "mkostemp() failed");
```

**Comment by karelzak** [comment]
Good catch, thanks!

Fixed by commit adcd2c322ce4b66f90cf423aad369643d49edd5d.
