### ISSUE TITLE
Utab: There are too many entries in /run/mount/utab, reaching millions.

### ISSUE THREAD

**Issue by hexiaowen** [util-linux/util-linux#1617]
There are too many entries in /run/mount/utab, reaching millions.

How to deal with this situation and who is responsible for cleaning up

**Comment by karelzak** [comment]
You have to provide more information. According to your comment in https://github.com/systemd/systemd/issues/15464 it seems like entries for NFS mounts.

Are all the mount points mounted? Do you see any change after umount? ... etc.

**Comment by hexiaowen** [comment]
The problem has been confirmed,
It is because the mount operation is performed on the host, the umount opteration is in the container, and /run/mount/utab is not mounted in the container, the utab is not refreshed when umount.

Thanks, I'll close this issue

**Comment by karelzak** [comment]
Yes, utab does not work as expected when namespaces or/and containers are in the game ...

It should be safe to remove the entries from the file manually.
