### ISSUE TITLE
wipefs re-read delay insufficient

### ISSUE THREAD

**Issue by winterqt** [util-linux/util-linux#1619]
util-linux 2.36.1, Linux 5.16.5

The `ioctl` call consistently return `EBUSY` enough times when running `wipefs` with a wildcard (i.e. `wipefs -a /dev/sda*`) to cause a bailout; maybe the delay should be longer?

**Comment by karelzak** [comment]
Excellent catch. We have everywhere 250000ms delay, but wipefs was 25000ms (I guess it was a typo).

So, thanks! :-)

**Comment by winterqt** [comment]
> We have everywhere 250000ms delay

250 seconds seems a bit extreme, no? Or is the unit not milliseconds?

**Comment by karelzak** [comment]
Sorry, no 'ms', it is in microseconds (usec).
