### ISSUE TITLE
lslocks fails to handle a /proc/locks with three digit minor numbers

### ISSUE THREAD

**Issue by siebenmann** [util-linux/util-linux#1633]
If you have enough mounted NFS filesystems (or probably other filesystems as well), the filesystem minor numbers go over 255 and so are represented in /proc/locks as three or more hex digits:

```
8: FLOCK  ADVISORY  READ  25613 00:1a9:1207 0 EOF
```
If you run lslocks on such a system with such an active lock, it reports `lslocks: failed to parse '00:1a9:1207'`. This is because the sscanf() in get_dev_inode() is only allowing a two-character minor field, with a sscanf format of  "%02x:%02x:%ju". I believe the second %02x should just be %x.

**Comment by karelzak** [comment]
IMHO there is no reason to use %02 at all, the separator between the numbers is good enough to keep make scanf() happy.
