### ISSUE TITLE
Convenient UID / GID mapping with mount(8)

### ISSUE THREAD

**Issue by quasicomputational** [util-linux/util-linux#1652]
Originally systemd/systemd#23056.

@poettering suggests that `mount(8)` growing a new options to conveniently express remapping of UIDs and GIDs at mount time is the best way to implement this, so that all programs that call `mount(8)` will benefit and not just systemd.

**Comment by poettering** [comment]
uidmaps can only be set during initial mount, and cannot be changed later.

I'd just do `-o X-mount.idmap=0:4711:15,999:0:16` 

this would move 15 uids/gids from 0 to 4711, and 16 uids/gids from 999 to 0. This option would change both uid and gid maps in one go.

And then, maybe optionally, also support X-mount.uidmap= and X-mount.gidmap= which would allow changing the maps individually for "u" and "g".

(I think in 99% of cases people probably want to shift uids and gids simultaneously, hence my suggestion to just use "X-mount.idmap=" as primary option, which changes both.

**Comment by brauner** [comment]
> Yes, this is something I assume. The question is how to implement it.
> 
> I'd like to add something like "mount modify --{set, clear}" to call mount_setattr() for attributes modification, but I guess for idmapping we need something else, probably a mount option. Maybe specifying an user namespace would be enough, something like
> 
> mount /mnt/sdc1 /mnt -o idmap=/proc/some/ns
> 
> @brauner any idea?

Good to hear!
I always envisioned we'd support two ways to idmap a mount:
- via a path to a user namespace
- by specifying mappings explicitly
Because there'll be users that want to use this for regular mounts on the host and then there will be users that will want to attach mounts to their containers.

I didn't know about the `X-mount.{suffix}` option before @poettering's comment but that seems like a decent approach to me.

However, I had originally envisioned this differently. In the tool that I wrote at:
https://github.com/brauner/mount-idmapped
I used the following syntax to specify explicit mappings:
```
{u,g,b}:<mount>:<host>:<range>,{u,g,b}:<mount>:<host>:<range>, [...]
```
For example,

```
--idmap=b:1000:0:1,u:2000:1:1,g:5000:3000:1
```

This particular mapping would map files owned by both uid and gid 1000 to 0 in the idmapped mount; a caller with id 0 would create files on-disk as id 1000.

**Comment by brauner** [comment]
I originally wrote `mount-idmapped` for the xfstests suite I added for idmapped mounts and it's upstream in:
https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git/tree/src/idmapped-mounts/mount-idmapped.c
and might be useful as a rough guide.

**Comment by poettering** [comment]
> --idmap=b:1000:0:1,u:2000:1:1,g:5000:3000:1

Making it a `--idmap=` switch means you cannot easily stick it in /etc/fstab, but I am pretty sure people want that.

(also if you make it a separate cmdline switch then systemd would need to learn about it too, and I'd rather avoid that. By making it a `X-mount.` mount option things will just work otoh, systemd doesn#t need to learn anything new)

**Comment by brauner** [comment]
The command line switch was just taken from the binary I wrote. For util-linux I would expect it to be what @karelzak proposed, i.e. `-o idmap` not `--idmap`.

**Comment by karelzak** [comment]
BTW, the latest unshare(1) supports ID mapping and it's done by newuidmap and newgidmap from shadow-utils (it's executed from child and it modifies parent's /proc/#/uid_map). The nice feature is that it supports also /etc/subuid for the ID definitions for --map-users=auto. But this is probably overkilling for suid mount(1), b:1000:0:1,u:2000:1:1,g:5000:3000:1 sounds good enough :-)

**Comment by brauner** [comment]
Ah, I see it landed [here](https://github.com/util-linux/util-linux/commit/ff5dc96ebf2bf83150ba1fa73f4498ed2210c29c).

Yes, I think we don't need to support `/etc/sub{g,u}id` for this. Out of curiosity, do you think you'll be able to work on this soon?

**Comment by karelzak** [comment]
@brauner if you want to work on this you can go ahead :-)

**Comment by brauner** [comment]
> @brauner if you want to work on this you can go ahead :-)

:) What did we end up preferring `-o idmap=` or `X-mount.idmap`?

**Comment by poettering** [comment]
I think `X-mount.`  is the namespace for mount tools own options, to not conflict with naming of options by kernel file systems. I mean, who knows, something like nfs4 might already have an option "idmap=", no? (and if it hasn't it might and the devs might not bother checking if /bin/mount already squatted the name)

**Comment by poettering** [comment]
(my comment regarding nfs is from the background that nfs knows a `rpc.idmapd` service, that's why I'd be careful with picking that specific name `idmap`)

**Comment by poettering** [comment]
Quoting `mount(8)`:

        X-*
           All options prefixed with "X-" are interpreted as comments or as userspace application-specific options. These options are not stored in user space (e.g., mtab file), nor sent to the mount.type helpers nor to the mount(2)
           system call. The suggested format is X-appname.option.

       x-*
           The same as X-* options, but stored permanently in user space. This means the options are also available for umount(8) or other operations. Note that maintaining mount options in user space is tricky, because it’s
           necessary use libmount-based tools and there is no guarantee that the options will be always available (for example after a move mount operation or in unshared namespace).

           Note that before util-linux v2.30 the x-* options have not been maintained by libmount and stored in user space (functionality was the same as for X-* now), but due to the growing number of use-cases (in initrd, systemd
           etc.) the functionality has been extended to keep existing fstab configurations usable without a change.

So this would suggest naming this "x-mount.idmap=", actually, with a lower-case x, given it probably makes sense to have this discoverable if you dump the mount table with /bin/mount?

**Comment by karelzak** [comment]
@poettering, x-* means that mount will write it to /run/mount/utab ... is it really something we need? I want to avoid it as it has all problems we had with the original /etc/mtab (not compatible with namespaces, containers, ...); empty utab is a good utab.

I guess /proc/#/uid_map is something we can read if necessary to display the mapping -- maybe it's something we can add to findmnt(8).

The other important thing is that our mount(8) specific imap= is not the only way to define the mapping. You can use mount_setattr() and points the mount to any existing user namespace (and maybe idmap=/proc/#/ns/user should be another way we want to support).

X-mount.idmap= sounds less problematic :-)

**Comment by poettering** [comment]
> I guess /proc/#/uid_map is something we can read if necessary to display the mapping -- maybe it's something we can add to findmnt(8).

To my knowledge there is simply no way to figure out the uidmap in effect for an established mount. There is not API for this. So unless you save the data yourself the data is just not available. @brauner, correct me if I am wrong.

**Comment by karelzak** [comment]
... but keep in userspace kernel data sucks, you know.

**Comment by brauner** [comment]
> Note, there is a patch to implement X-mount.{owner,group,mode}= options for mount(8). After successful mount(2), the idea is that it calls chown and chmod for the mountpoint directory (so, no namespaces in the game). I guess this patch is not in conflict with idmap, right?
> 
> https://lore.kernel.org/util-linux/20220406113814.twdo4mwkevwuayht@ws.net.home/T/#ma1da7aed9ad69dd3501fdfc2d2f4185c798c1466

No, they do not conflict each other. :)

They could be reasonably used together although I find this unlikely. If you're creating an idmapped mount and then immediately after you've created it you're chow() every singly file that sounds a bit pointless. So I might make them mutually exclusive until we have someone that uses it.

The advantage of supporting both in `mount(1)` that I can see is that on kernels that don't support `mount_setattr()` you get a minimal alternative. I say minimal, because you can only chown to one uid/gid.

**Comment by brauner** [comment]
> > I guess /proc/#/uid_map is something we can read if necessary to display the mapping -- maybe it's something we can add to findmnt(8).
> 
> To my knowledge there is simply no way to figure out the uidmap in effect for an established mount. There is not API for this. So unless you save the data yourself the data is just not available. @brauner, correct me if I am wrong.

We don't currently have a way. The reason is that `fsinfo()` never made it which was supposed to provide info like that. However, one possible solution Lennart and I came up with is to display the idmapping in `/proc/<pid>/fdinfo/<fd>` as that already contains a bunch of information. (Though I'd really prefer this to be part of something like `fsinfo()`.)

**Comment by poettering** [comment]
@brauner can't you serialize the uidmaps kernel-side into the mount options string? i.e. into the sixth column of /proc/self/mountinfo?

**Comment by poettering** [comment]
(or can't that string be remapped dynamically to whoever reads that file?)

**Comment by brauner** [comment]
> @brauner can't you serialize the uidmaps kernel-side into the mount options string? i.e. into the sixth column of /proc/self/mountinfo?

I thought about that originally but it's super disgusting.

**Comment by brauner** [comment]
This really wants to be part of a system call or set of system calls that allow you to query for detailed mount and/or filesystem info imho.

**Comment by karelzak** [comment]
> one possible solution Lennart and I came up with is to display the idmapping in `/proc/<pid>/fdinfo/<fd>` 

I'd suggest a new directory /proc/<pid>/nsinfo/ to export extra kernel configuration related to namespaces to userspace. It means  /proc/self/nsinfo/user (or user-uid-map) the mapping. This is not only about mount(8). It would be nice to have this additional namespace data and tools like lsns.

**Comment by brauner** [comment]
> > one possible solution Lennart and I came up with is to display the idmapping in `/proc/<pid>/fdinfo/<fd>`
> 
> I'd suggest a new directory /proc/#/nsinfo/ to export extra kernel configuration related to namespaces to userspace. It means /proc/self/nsinfo/user (or user-uid-map) for the mapping. This is not only about mount(8). It would be nice to have this additional namespace data and tools like lsns.

That's certainly additionally useful and something to consider. But it'd still be neat to retrieve idmapping info for a filesystem or mount directly through a system call like `fsinfo()` (or another version of it).

**Comment by karelzak** [comment]
> That's certainly additionally useful and something to consider. But it'd still be neat to retrieve idmapping info for a filesystem or mount directly through a system call like `fsinfo()` (or another version of it).

Definitely, you now how difficult is it with fsinfo()-like stuff in LKML ...

**Comment by brauner** [comment]
> > That's certainly additionally useful and something to consider. But it'd still be neat to retrieve idmapping info for a filesystem or mount directly through a system call like `fsinfo()` (or another version of it).
> 
> Definitely, you now how difficult is it with fsinfo()-like stuff in LKML ...

Tell me about it... :D/:(

**Comment by corsac-s** [comment]
> > --idmap=b:1000:0:1,u:2000:1:1,g:5000:3000:1
> 
> Making it a `--idmap=` switch means you cannot easily stick it in /etc/fstab, but I am pretty sure people want that.
> 
> (also if you make it a separate cmdline switch then systemd would need to learn about it too, and I'd rather avoid that. By making it a `X-mount.` mount option things will just work otoh, systemd doesn#t need to learn anything new)

Came accross idmaps after the LWN article on systemd 250 and if I understand correctly the feature, I'd likely use it as part of the fstab in LXC configurations to mount (or bind-mount) specific filesystems in containers and map files {u,g}id to the local ones in the container, so yeah, having a way to express that in fstab syntax (and with support to mount so it can be used by LXC) would be really nice.

**Comment by brauner** [comment]
@karelzak, I think we can close this issue. :)

**Comment by corsac-s** [comment]
> @karelzak, I think we can close this issue. :)

Does this mean it's now implemented?

**Comment by brauner** [comment]
Yeah, it's implemented and merged into master. A while ago, actually.
