### ISSUE TITLE
lsblk: by-id-based name hierarchy

### ISSUE THREAD

**Issue by Atemu** [util-linux/util-linux#1658]
Currently, lsblk can output the hierarchy of drives, partitions and nested DM targets via the `NAME` column. Like this:

```
NAME                          
sda                           
└─sda2                        
  └─18TB                      
    └─bcache1                 
sdb                           
├─sdb1                        
├─sdb2                        
│ └─SAMSUNG_MZ7LN256HCHP-crypt
│                             
│                             
│                             
│                             
└─sdb3                        
  └─TRION100-crypt            
    └─bcache1                 
sdc                           
└─sdc2                        
  └─ST1000DM003-crypt         
    └─bcache2               
...  
```

Depending on dev names is considered bad style as they might change across reboots. Therefore, I would like to see the `/dev/disk/by-id` names instead.

You can get something close via the `MODEL` column. However, it doesn't offer the tree-like hierarchy display and only spells out the device's model name on the line of the device which makes it look quite disconnected:

```
NAME                           MODEL
sda                            TOSHIBA MG09ACA18TE
└─sda2
  └─18TB
    └─bcache1
sdb                            SAMSUNG MZ7LN256HCHP-00000
├─sdb1
├─sdb2
│ └─SAMSUNG_MZ7LN256HCHP-crypt
└─sdb3
  └─TRION100-crypt
    └─bcache1
sdc                            ST1000DM003-9YN162
└─sdc2
  └─ST1000DM003-crypt
    └─bcache2
```

It's a relatively minor visual thing but seeing connections requires some mental steps to figure out things like which device bcache1 belongs to:

1. See that it's on sdb3
2. Follow sdb3 up to sdb
3. Follow the (invisible) line rightwards
4. Read model name

Dense layouts and long dm names might cause a user to accidentally skip a line here and wrongly associate a kname with a certain drive they know by model number:

```
NAME                                        MODEL
...
sdf                                         TOSHIBA MG09ACA18TE
├─sdf1
│ └─LOOOOOOOOOOOOOOOOOOOOOOOOOONG-DM-NAME-F
sdg                                         TOSHIBA MG09ACA18TE
├─sdg1
│ └─LOOOOOOOOOOOOOOOOOOOOOOOOOONG-DM-NAME-G
sdh                                         TOSHIBA MG09ACA18TE
├─sdh1
│ └─something else
sdi                                         SAMSUNG MZ7LN256HCHP-00001
├─sdi1
│ └─easy-to-confuse
sdj                                         SAMSUNG MZ7LN256HCHP-00002
├─sdj1
│ └─reall-want-this
sdk                                         SAMSUNG MZ7LN256HCHP-00003
├─sdk1
│ └─more-confusion
...
```

Confusing two drives can be very dangerous of course.

It'd be very useful to have a column which shows the by-id name together with the hierarchy:

```
ID
TOSHIBA_MG09ACA18TE-SERIALNO  
└─part2
  └─18TB
    └─bcache1
SAMSUNG_MZ7LN256HCHP-00000_SERIALNO
├─part1
├─part2
│ └─SAMSUNG_MZ7LN256HCHP-crypt
└─part3
  └─TRION100-crypt
    └─bcache1
ST1000DM003-9YN162_SERIALNO
└─part2
  └─ST1000DM003-crypt
    └─bcache2
```

To do the same task as before (get by-id device name of device containing bcache1), the user would now only have to follow the visual guides upwards which is very convenient and foolproof.

**Comment by Atemu** [comment]
> There is a command line option --tree=colname.

Oh! Didn't notice that before, thank you.

> MODEL or WWN is not defined for partitions

In `/dev/disk/by-id`, it simply postfixes the WWNs/full model ids with `-part1`, `-part2` etc.

In my example above, I applied the same principle.

> The only thing which is everywhere is NAME and MAJ:MIN ;-)

That's true.

It'd be great to have an option to display the (non-wwn) names used in `/dev/disk/by-id` sans `ata-` or `usb-` prefix. They're human-readable and unique.

**Comment by karelzak** [comment]
Maybe the best solution would be to introduce a new column that will strictly follow udev's /dev/disk/by-id and selects the shortest ID for the device, but it still has limited usability in some cases, for example for NVMe on my workstation:

/dev/nvme0n1p1  is

nvme-nvme.1987-35303032364237323832303336303144-4b494e4753544f4e20534b433130303032343047-00000001-part1

or 

nvme-KINGSTON_SKC1000240G_50026B728203601D-part1

It's a huge string to display on the terminal, but still better than nothing and it's the way how to make it more connected with udev. I'll think about it.

**Comment by karelzak** [comment]
Implemented as a new column `ID-LINK`, on my workstation (with excluded loop devices):
```
$ ./lsblk -oID-LINK,NAME,SIZE --tree=ID-LINK --exclude 7
ID-LINK                                            NAME        SIZE
wwn-0x50026b724b09a1ff                             sda       223.6G
├─wwn-0x50026b724b09a1ff-part1                     sda1        200M
├─wwn-0x50026b724b09a1ff-part2                     sda2          5G
├─wwn-0x50026b724b09a1ff-part3                     sda3      125.5G
├─wwn-0x50026b724b09a1ff-part4                     sda4         50G
└─wwn-0x50026b724b09a1ff-part5                     sda5       42.9G
ata-WDC_WD800JD-00MSA1_WD-WMAM9XE78956             sdb        74.5G
└─ata-WDC_WD800JD-00MSA1_WD-WMAM9XE78956-part1     sdb1       74.5G
scsi-333333330000036b0                             sdc         500M
├─scsi-333333330000036b0-part1                     sdc1        100M
└─scsi-333333330000036b0-part2                     sdc2        399M
ata-HL-DT-ST_DVD+_-RW_GH82N_K4LC2EC0449            sr0        1024M
nvme-KINGSTON_SKC1000240G_50026B728203601D         nvme0n1   223.6G
├─nvme-KINGSTON_SKC1000240G_50026B728203601D-part1 nvme0n1p1   7.8G
├─nvme-KINGSTON_SKC1000240G_50026B728203601D-part2 nvme0n1p2   200G
└─nvme-KINGSTON_SKC1000240G_50026B728203601D-part3 nvme0n1p3  15.8G
```

**Comment by karelzak** [comment]
Maybe we can use a better name for the column, ID-SYMLINK? Not sure.

**Comment by Atemu** [comment]
Amazing, thank you!

Udev calls this name pattern ID_SERIAL AFAICT and that seems like a fitting name to me aswell.

I don't think it should include the wwn devices though as lsblk already has a dedicated WWN column.

Would it also be possible to strip the `ata-`, `usb-`, `nvme-` etc. prefixes? That piece of information should probably also live in its own column.

**Comment by karelzak** [comment]
I have used directly "links" as stored in udevdb (udev_device_get_devlinks_list_entry()) and I think could be attractive for users (scripts) as it's compatible with /dev/disk/by-* content, so it's pretty easy to use lsblk to generate paths to access the devices. This is the reason why I'd like to keep it unchanged (with the prefixes). 

Maybe we can introduce another column "ID" where it will be without the prefix.
