### ISSUE TITLE
When moving a mounted tree, all mounted sub tree entries in utab should also be updated

### ISSUE THREAD

**Issue by fbuihuu** [util-linux/util-linux#1659]
To illustrate the problem, consider the following use case:

```
# mount -ox-initrd.mount /dev/vdb /mnt
# mount -ox-initrd.mount /dev/vdb /mnt/mnt/
# cat /run/mount/utab
SRC=/dev/vdb TARGET=/mnt ROOT=/	OPTS=x-initrd.mount
SRC=/dev/vdb TARGET=/mnt/mnt ROOT=/ OPTS=x-initrd.mount
# mount --move /mnt /opt
# cat /run/mount/utab
SRC=/dev/vdb TARGET=/opt ROOT=/	OPTS=x-initrd.mount
SRC=/dev/vdb TARGET=/mnt/mnt ROOT=/ OPTS=x-initrd.mount
```
Here we can see that the entry for the moved mounted tree `/mnt` has been correctly updated to the new target `/opt` however the target of the mounted sub tree `/mnt/mnt` remained unchanged whereas its new location is at `/opt/mnt`.

**Comment by fbuihuu** [comment]
I agree that mount ID is probably better.

However I think it would still make sense to fix the current code because switching to mount ID will require much more changes than https://github.com/util-linux/util-linux/pull/1660 requires. It will be easier for downstream to backport the minimal fix for already the current libmount releases until the use of mount IDs will be implemented, released and used by distros (which will take several months I guess).

**Comment by karelzak** [comment]
Yes, I plan to support both ways to make it backwardly compatible and to make libmount usable also on old systems without the new kernel stuff. I guess we can keep TARGET= in utab for some time (releases).

**Comment by fbuihuu** [comment]
@karelzak just in case but you probably already noticed, there's https://github.com/util-linux/util-linux/pull/1660 to fix the current code.
