### ISSUE TITLE
more: uninterruptable infinite loop with -s and blank line at end of file

### ISSUE THREAD

**Issue by hvdijk** [util-linux/util-linux#1669]
Test case:

    echo | more -s

This causes more to run at 100% CPU, not responding to Ctrl-C, Ctrl-\, Ctrl-Z, ....

The infinite loop comes from the `screen()` function:

```c
                while (num_lines > 0 && !ctl->is_paused) {
                        nchars = get_line(ctl, &length);
                        ctl->is_eof = nchars == EOF;
                        if (ctl->is_eof && ctl->exit_on_eof) {
                                if (ctl->clear_line_ends)
                                        putp(ctl->clear_rest);
                                return;
                        }
                        if (ctl->squeeze_spaces && length == 0 && prev_len == 0)
                                continue;
```

When the last line of input is blank, this will never terminate, `get_line()` will forever return `EOF` and set `length` to zero, causing the `if` to repeat the loop.

This part is easy to fix by adding a check for `ctl->is_eof`.

However, personally, I think the fact that at this time `more` is not responsive, that there is no clean way to get it to terminate or even suspend without going into another session, is an issue as well, and I suspect that requires a bit more than a simple one-line code change.

**Comment by karelzak** [comment]
Well, the problem is all the while() + continue. The suggested solution is good enough to break the while() and to call more_key_command() where it waits for the user's response.

**Comment by hvdijk** [comment]
Thanks for pushing the fix for the immediate problem.

For the larger problem, I was thinking more of what happens if a similar bug arises in the future. The ability to control processes with Ctrl-C, Ctrl-\, Ctrl-Z is a safety mechanism and I'm a bit worried that that safety mechanism is disabled in `more`. Bugs happen, so I see it as important that mechanisms to respond to bugs work. In `less`, Ctrl-C does not kill `less` but does interrupt whatever it is doing (in particular, calculating line numbers), and Ctrl-Z suspends not just whatever is piped into `less`, but also `less` itself. If `less` had had the same bug as `more`, Ctrl-C might have restored it to a good state, and even if not, I would have been able to use Ctrl-Z to get back to the parent shell and use that to kill it, as opposed to needing to find another shell to kill `more` from. Should I report that separately, or do you see that as a non-issue?
