### ISSUE TITLE
how not to scroll whole screen for small files with MORE

### ISSUE THREAD

**Issue by ynikitenko** [util-linux/util-linux#1674]
I use Arch Linux and `more` for a long time, and maybe this or last year the behaviour of `more` changed: before, for small files it printed them like `cat`, that is just printed them on the screen and returned to the terminal.

Now (I checked that I use `more` from your package) that behaves between `cat` and `less`: if a file is smaller than the whole screen, it prints it at the top of the screen and leaves all other screen blank; I have to press `q` to exit `more`.

What should I do to return the previous behaviour of `more`? I checked command line options and the `MORE` environmental variable (which is empty), but can't find that. I can't do a proper web search because I can't even formulate the question well (please edit if appropriate).

**Comment by chapmanjacobd** [comment]
[bat](https://github.com/sharkdp/bat) will print without a pager if the file is smaller than one screen

**Comment by ynikitenko** [comment]
Thanks. It is not installed by default for me. Anyway I'm very much used to `more`. `cat` would do what I want for small files, but I don't like that it outputs whole files for large ones - I loved `more` approach much... more!

**Comment by karelzak** [comment]
This is the controversial change we did in the last release ... 

Now, for better compatibility with POSIX, more does not exit by default, but it waits for the user's response. You can use -e, --exit-on-eof to revert this behavior. For example, you can define an alias in your profile file (alias more="more -e") to get the original behavior.

**Comment by ynikitenko** [comment]
Many thanks, this works exactly as I wanted (as before)!
