### ISSUE TITLE
Piping anything to `script` prevents subsequent interaction.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [util-linux/util-linux#1690]
Execution of `script -a | sudo clock` presents the consequence of execution of `sudo clock` but prevents subsequent interaction with the terminal. If this was invoked by a rescue tty as an erroneous method of attempting to timestamp output, the consequent prevention of subsequent interaction would necessitate a reboot, which might be undesirable.

I have solely evaluated this via [Konsole](http://src.fedoraproject.org/rpms/konsole) and [Alacritty](http://src.fedoraproject.org/rpms/rust-alacritty) via [Fedora Server Rawhide](http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/Server/x86_64/iso).

**Comment by mator** [comment]
does calling `reset` like 
```
script -a | sudo clock; reset
```
helps? `reset` is from `ncurses-bin` package in debian

**Comment by BEEDELLROKEJULIANLOCKHART** [comment]
@mator, invocation of `script -a | sudo clock; reset` does not appear to remediate the problem. However, if it invokes within any directory that the current user does not possess permission to modify, the command fails and quickly subsequently removes its output from the terminal.

**Comment by karelzak** [comment]
I have tried it on gnome-terminal and standard console and it works as expected. It prints timestamp and after CTRL+D it exists from the script(1). Not sure what we can improve here.
