### ISSUE TITLE
fstrim --dry-run does not display number of byte that would be trimmed

### ISSUE THREAD

**Issue by turboboost55** [util-linux/util-linux#1691]
Consider the following two commands run right after each other:
```
$ sudo fstrim -v -n /
/: 0 B (dry run) trimmed
$ sudo fstrim -v  /
/: 44.2 GiB (47429943296 bytes) trimmed
```
I was expecting the first command to say something like `44.2 GiB would be trimmed (dry run)`

My system specs:
Raspberry Pi 4
Raspberry Pi OS 64 bit
Samsung 870 EVO, USB attached

**Comment by karelzak** [comment]
Unfortunately, this is not possible. The userspace has no clue what and how the Linux kernel will trim data, so the number cannot be calculated, and the kernel returns the number only for real trim operation.
