### ISSUE TITLE
Is there anyway to build a rpm package ?

### ISSUE THREAD

**Issue by zhangguanzhang** [util-linux/util-linux#1693]
some depend error in my machine. I need build a rpm package for `libmount-devel`

**Comment by karelzak** [comment]
You need to write your own spec file or re-use some spec file from some rpm-based distro (Fedora, Suse, ...).

Our basic rule is distro neutrality; for this reason, spec files are not part of the upstream tree.  https://github.com/util-linux/util-linux/blob/master/Documentation/howto-contribute.txt#L38-L40
