### ISSUE TITLE
Documentation for -o incorrect?

### ISSUE THREAD

**Issue by jonjensen** [util-linux/util-linux#1699]
The man page reads:

```
       -o, --output-separator string
           Specify the columns delimiter for table output (default is two spaces).
```

That seems incorrect, since the default delimiter is tabs, not spaces, and seems to be at least 2 tabs, but more as needed for alignment.

I'm happy to submit a pull request for this if I'm understanding it right.

**Comment by karelzak** [comment]
For the --table mode the default output separator is really two spaces, try:
```
$ echo "AAA BBB CCC" | ./column --table | sed 's/ /./g'
AAA..BBB..CCC
```
I think the man page should be more explicit that --output-separator is only about --table. Maybe this is something we can make more obvious for readers.

**Comment by jonjensen** [comment]
@karelzak Ah, I see! I didn't understand that "table output" meant the `-t` option specifically, but it makes sense. Thanks!
