### ISSUE TITLE
Question. Can column use the full available width from bash terminal

### ISSUE THREAD

**Issue by mailsanchu** [util-linux/util-linux#1700]
Is it possible to add extra spaces and use the full available bash terminal width?Please see the attached image
![image](https://user-images.githubusercontent.com/32928538/171194664-1e685cf4-f400-48ae-9727-6b726071bebd.png)

**Comment by mailsanchu** [comment]
![image](https://user-images.githubusercontent.com/32928538/171195058-2b67e32c-329d-434b-b00c-164199b8785b.png)
Full Image

**Comment by karelzak** [comment]
For now, you have to specify --output-width (for example "--output-width $COLUMNS"), since the next release (v2.39) it will be possible to use "--output-width unlimited" to use all available space.

See also https://github.com/util-linux/util-linux/issues/1618.

**Comment by mailsanchu** [comment]
I am using the latest code. I want to fill(max width) the blue box in the screen show.
![image](https://user-images.githubusercontent.com/32928538/171407178-1427c5f2-cdd0-4777-a4c7-445d6e726c0f.png)

**Comment by mailsanchu** [comment]
I hope my question is clear

**Comment by mailsanchu** [comment]
The "unlimited" feature is not released yet (in git tree only) -- I check out the master and compiled it myself. I am not getting any error when I say --output-width unlimited.Adding --table option is not helping in this case
Thank you very much

**Comment by karelzak** [comment]
```
$ echo "A B C DD" | ./column --table
A  B  C  D

$ echo "A B C DD" | ./column --table --table-maxout
A                     B                    C                    D                  
```

The free space is distributed between all columns rather than keep after the last column.

**Comment by mailsanchu** [comment]
This worked perfectly for me

**Comment by karelzak** [comment]
> What do you think of having an option to right-align the last column @karelzak

You can use `--table-right number|name` for the column. See the man page for more details.

**Comment by mailsanchu** [comment]
Yes i  am aware of that.But you have to mention the list of column names to use that option right?

**Comment by karelzak** [comment]
It should be possible to use a number of column if you do not want to define names.
```
echo "A B C D" | column --table --table-maxout --table-right 4
```

**Comment by mailsanchu** [comment]
:) Any hidden variable that tells the no of columns available?

**Comment by karelzak** [comment]
It already supports placeholder "0" to address all columns, maybe we can introduce "-1" to address the last column.

**Comment by mailsanchu** [comment]
Ok so the command would be something like this if you implement that
`echo "A B C D" | column --table --table-maxout --table-right -1`

**Comment by mailsanchu** [comment]
svarkey@sanchu-Precision-7760:~$ echo "A B C D" | column --table --table-maxout --table-right 0
column: undefined column name '0'
svarkey@sanchu-Precision-7760:~$ 
Is this a bug? or not implemented yet

**Comment by karelzak** [comment]
Ooops, bug. Fixed.

**Comment by mailsanchu** [comment]
Let me rebuild. :)

**Comment by karelzak** [comment]
The problem (regression) with "0" placeholder has been introduced by commit b4526713bc90c5f18bb59ef5719debfc67f14430, originally it was without the error message.

**Comment by mailsanchu** [comment]
I can build it from master

**Comment by mailsanchu** [comment]
It worked 
![image](https://user-images.githubusercontent.com/32928538/172581725-7d6bdc0f-f2ae-43b7-b6ed-58fdf46775c7.png)

**Comment by mailsanchu** [comment]
NOw waiting for -1 :+1:  :)

**Comment by karelzak** [comment]
OK, rebuild ;-)

**Comment by mailsanchu** [comment]
Hi there, Is there an option to buy you a coffee? Something like this 
https://www.buymeacoffee.com/crispgm

**Comment by karelzak** [comment]
Sorry, fixed now. I have also added a regression test to avoid the problem in the future.
