### ISSUE TITLE
lscpu JSON output differs when piped

### ISSUE THREAD

**Issue by zorun** [util-linux/util-linux#1735]
Since version 2.37, lscpu outputs hierarchical data, which is nice:
```
$ ./lscpu -J
{
   "lscpu": [
      {
         "field": "Architecture:",
         "data": "x86_64",
         "children": [
            {
               "field": "CPU op-mode(s):",
               "data": "32-bit, 64-bit"
            },{
               "field": "Address sizes:",
               "data": "39 bits physical, 48 bits virtual"
            },{
               "field": "Byte Order:",
               "data": "Little Endian"
            }
         ]
      },
...
```

However, when the output is piped, it reverts back to a "flat" JSON format:

```
$ ./lscpu -J | cat
{
   "lscpu": [
      {
         "field": "Architecture:",
         "data": "x86_64"
      },{
         "field": "CPU op-mode(s):",
         "data": "32-bit, 64-bit"
      },{
         "field": "Address sizes:",
         "data": "39 bits physical, 48 bits virtual"
      },{
         "field": "Byte Order:",
         "data": "Little Endian"
      },
...
```

While this behaviour is documented for plain text output, having such a major format difference is quite unexpected and unwanted for JSON. For example, I'm using lscpu through Ansible and it gives a different result than running lscpu through the shell.

**Comment by karelzak** [comment]
Yes, this is stupid at first glance, but this is the price we pay for backward compatibility. The summary output by JSON has been released in Jun 2017. I don't think changing the format in the year 2022 is expected by users who have already used their scripts for years. 

But I see the pain, what about adding some option `--flat-summary [yes|no|auto]` where "auto" is the backwardly compatible default (where behavior depends on non/terminal) and this option will affect normal as well as JSON output. Does it make sense?

**Comment by karelzak** [comment]
And yes, it should be documented also for JSON too, this is a mistake.

**Comment by zorun** [comment]
Thanks, the new option looks good!

Now I understand the logic why you wanted to keep compatibility for non-terminal output: anybody parsing the output of lscpu will obviously fall in this category. I still find it confusing to have different output on terminal and non-terminal, but it's just a personal taste. I'm happy to have an option I can add to my scripts to control this.

By the way, the reason I'm interested in the hierarchical output is this: https://gist.github.com/zorun/35990c321bbb256f5ad4a585c1811ce0
It makes it easy to identify the two different subsets of CPU cores. With the "flat" output, I have no easy way to identify which field applies to which subset of CPU cores or if it applies globally.

**Comment by karelzak** [comment]
It seems we need to add columns MODEL, VENDOR, etc. to -e output. Now it contains only CPU (socket, etc.) numbers, but lscpu has internally more information.
