### ISSUE TITLE
lscpu --json values are inconsistently locale-sensitive

### ISSUE THREAD

**Issue by wjt** [util-linux/util-linux#1743]
In a locale where `,` rather than `.` is the decimal separator, floating-point fields in the `lscpu --json` output are inconsistent. Some use `.` as the decimal separator, others use `.`.

```
$ lscpu --version
lscpu from util-linux 2.36.1
```

Here is the output of `LANG=fr_FR.utf8 lscpu --json` with irrelevant fields removed:

```json
{
   "lscpu": [
      {"field":"Model name:", "data":"Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz"},
      {"field":"CPU MHz:", "data":"2000.000"},
      {"field":"CPU max MHz:", "data":"4600,0000"},
      {"field":"CPU min MHz:", "data":"400,0000"},
      {"field":"BogoMIPS:", "data":"3999.93"}
   ]
}
```

Note that `CPU MHz` and `BogoMIPS` have `.` as the separator, but `CPU max MHz` and `CPU min MHz` have `,`.

**Comment by karelzak** [comment]
"CPU MHz" should be already fixed in the recent version, BogoMIPS is fixed in the git tree.

Thanks for your report.

**Comment by wjt** [comment]
Thank you for the swift fix!
