### ISSUE TITLE
sfdisk script execution does not work with changed sector size

### ISSUE THREAD

**Issue by t-8ch** [util-linux/util-linux#1744]
When replicating the partition table (gpt) from a 4096 sector-size disk to a 512 sector-size disk via `sfdisk --dump > script` and `sfdisk < script` the sector counts were used verbatim. This made all the offsets off by a factor of 8.

Sfdisk should take into account both the sector size from the script and the sector size from the target disk and recalculate all them as needed.

**Comment by t-8ch** [comment]
Thanks!

I just found that the docs mentioned this, too.
So they probably need some changes:

sfdisk(8):

       sector-size
           Specify sector size. This header is informative only and it is not used when sfdisk creates a new partition table, in this case the real device specific value is always used and sector size from
           the dump is ignored.

**Comment by karelzak** [comment]
Good point, fixed.
