### ISSUE TITLE
Install util-linux-2.36 on CentOS5.8, I encountered problems.

### ISSUE THREAD

**Issue by evan853** [util-linux/util-linux#1755]
### **environment:**
gcc/g++: 5.5.0
make: 3.81
autoconf: 2.65
automake: 1.11.1
libtool: 2.4.6

When I do make, the following error occured.
below are logs, anyone who can give some suggestions?

### **LOG:**
make  all-recursive
make[1]: Entering directory `/var/chengdu-3part/third_code/util-linux-2.36'
Making all in po
make[2]: Entering directory `/var/chengdu-3part/third_code/util-linux-2.36/po'
make[2]: Leaving directory `/var/chengdu-3part/third_code/util-linux-2.36/po'
make[2]: Entering directory `/var/chengdu-3part/third_code/util-linux-2.36'
  CC     lib/libcommon_la-blkdev.lo
  CC     lib/libcommon_la-canonicalize.lo
  CC     lib/libcommon_la-crc32.lo
  CC     lib/libcommon_la-crc32c.lo
  CC     lib/libcommon_la-env.lo
  CC     lib/libcommon_la-idcache.lo
  CC     lib/libcommon_la-encode.lo
  CC     lib/libcommon_la-fileutils.lo
lib/fileutils.c: In function ‘dup_fd_cloexec’:
lib/fileutils.c:75:35: warning: unused parameter ‘lowfd’ [-Wunused-parameter]
 int dup_fd_cloexec(int oldfd, int lowfd)
                                   ^
  CC     lib/libcommon_la-ismounted.lo
  CC     lib/libcommon_la-color-names.lo
  CC     lib/libcommon_la-mangle.lo
  CC     lib/libcommon_la-match.lo
  CC     lib/libcommon_la-mbsalign.lo
  CC     lib/libcommon_la-mbsedit.lo
  CC     lib/libcommon_la-md5.lo
  CC     lib/libcommon_la-pager.lo
  CC     lib/libcommon_la-pwdutils.lo
  CC     lib/libcommon_la-randutils.lo
  CC     lib/libcommon_la-setproctitle.lo
  CC     lib/libcommon_la-strutils.lo
  CC     lib/libcommon_la-timeutils.lo
  CC     lib/libcommon_la-ttyutils.lo
  CC     lib/libcommon_la-exec_shell.lo
  CC     lib/libcommon_la-strv.lo
  CC     lib/libcommon_la-sha1.lo
  CC     lib/libcommon_la-signames.lo
  CC     lib/libcommon_la-caputils.lo
_lib/caputils.c: In function ‘cap_last_cap’:
**lib/caputils.c:34:9: error: ‘CAP_LAST_CAP’ undeclared (first use in this function)
   ret = CAP_LAST_CAP; /* guess */**
         ^_
lib/caputils.c:34:9: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [lib/libcommon_la-caputils.lo] Error 1
make[2]: Leaving directory `/var/chengdu-3part/third_code/util-linux-2.36'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/var/chengdu-3part/third_code/util-linux-2.36'
make: *** [all] Error 2

**Comment by karelzak** [comment]
CAP_LAST_CAP issue should eb already fixed by commit 5d95818757941bc609e5aeec5e2218f7d35a6e19.

The current upstream stable release is v2.38.
