### ISSUE TITLE
Bug in findmnt --output-all 

### ISSUE THREAD

**Issue by sideshowmel** [util-linux/util-linux#1757]
>findmnt --output-all 
findmnt: ACTION column is requested, but --poll is not enabled

>findmnt -V
findmnt from util-linux 2.37.2

Per man page:
--output-all
           Output almost all available columns. The columns that require --poll are not included.

>uname -a
Linux hpdw 5.15.0-41-generic #44-Ubuntu SMP Wed Jun 22 14:20:53 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

This happened after upgrading Ubuntu from 21.10 to 22.04.  

Last time I know I ran this command was 2022-01-31, presumably whatever version was current in Ubuntu 21.10 repos at the time, and it worked fine and output these columns (including SOURCE four times, I think):

SOURCE                                                   TARGET                                FSTYPE          OPTIONS                                                                                              VFS-OPTIONS                     FS-OPTIONS                                                                                  LABEL        UUID                                 PARTLABEL            PARTUUID                             MAJ:MIN SOURCE                                                   SOURCE                                                   SOURCE                                                     SIZE  AVAIL   USED USE% FSROOT  TID   ID OPT-FIELDS PROPAGATION FREQ PASSNO

Workaround:
findmnt -o TARGET,SOURCE,FSTYPE,OPTIONS,VFS-OPTIONS,FS-OPTIONS,LABEL,UUID,PARTLABEL,PARTUUID,MAJ:MIN,SIZE,AVAIL,USED,USE%,FSROOT,TID,ID,OPT-FIELDS,PROPAGATION,FREQ,PASSNO

**Comment by karelzak** [comment]
Upgrade to v2.38, already fixed by commit 68191a4117.
