### ISSUE TITLE
column: Issue with --table-columns-limit and leading whitespace

### ISSUE THREAD

**Issue by D1CED** [util-linux/util-linux#1763]
I am using util-linux version 2.38.

Example of the issue:

This works as expected 

    $ printf 'a b c\n1 2 3\n' | column -t -o '-' -l2
    a-b c
    1-2 3

but as soon as one introduces any amount of leading white space to any row the command breaks.

    $ #  two leading spaces
    $ #       vv
    $ printf '  a b c\n1 2 3\n' | column -t -o '-' -l2
    a-a
    1-2 3

The expected output would be the exact same as the case without leading white space.
Here the output changes based on the amount of leading white space.

The `-o '-'` part is here to clearly show the output columns and is not meaningful to the issue at hand.

**Comment by karelzak** [comment]
Thanks for your report! 

Should be fixed now in stable/v2.38 and the master branch.

**Comment by karelzak** [comment]
Hmm... something is still wrong with it.

**Comment by karelzak** [comment]
Should be fixed (added -o output separator to example to make it more readable):
```
$ printf 'a     b      c d e f g\n1  2  3  4   5   6 7\n' | ./column -t -l3 -o '|'
a|b|c d e f g
1|2|3  4   5   6 7
```

Sometimes the most effective way how to fix things is to delete complicated code :-) Now it works independently on the way how separator is defined and how the input is parsed by wcstok() and friends.
