### ISSUE TITLE
use mount-ID to manage utab in libmount

### ISSUE THREAD

**Issue by karelzak** [util-linux/util-linux#1765]
See https://github.com/systemd/systemd/pull/23168

Now utab is based on paths, it would be better to use mount IDs as it's not affected by MS_MOVE operation.

**Comment by dustymabe** [comment]
Hmm.. Was this implemented in https://github.com/karelzak/util-linux/commit/8cf6c5075780598fe3b30e7a7753d8323d093e22 ?

**Comment by karelzak** [comment]
Yes, thanks.

Also, a04149fbb7c1952da1194d1514e298ff07dbc7ca and 1ec32f426c0f4705ea4e6e33b812b3b4c2c47faa improve things.
