### ISSUE TITLE
RFE: add PARTN column to lsblk

### ISSUE THREAD

**Issue by marcosfrm** [util-linux/util-linux#1787]
`lsblk` already exposes a bunch of partition specific data. Device property `PARTN` from udev database would be welcome.

**Comment by karelzak** [comment]
The number is available by tree ways

1) PARTN in udevdb comes from kernel uevent
2) there is also  /sys/block/disk/partition/partition
3) libblkid provides ID_PART_ENTRY_NUMBER (stored in udevdb too); it reads it from the partition table

I have selected the last possibility.

**Comment by marcosfrm** [comment]
Thanks!
