### ISSUE TITLE
The lsmem and chmem commands of util-linux@2.38.1 are faulty in centos8_aarch64

### ISSUE THREAD

**Issue by Tom-python0121** [util-linux/util-linux#1791]
hello, I meet a problem:The lsmem and chmem commands of util-linux@2.38.1 are faulty in centos8_aarch64
### Steps to reproduce the issue

```console
[root@localhost util-linux]# ./lsmem
lt-lsmem: cannot open /sys/devices/system/memory: No such file or directory
[root@localhost util-linux]# ./chmem
chmem: Failed to read /sys/devices/system/memory: No such file or directory
```
I find that there is no memory folder, which is related to hot swap. The question is how to set the Linux system so that /sys/devices/system/memory can be displayed.

**Comment by karelzak** [comment]
Not sure, but I guess you need HW that supports memory hotplug (arm64 should be fine)  and kernel with enabled support. Try  to check your kernel configuration; for example:
```
# grep CONFIG_MEMORY /boot/config-4.18.0-422.el8.x86_64 
CONFIG_MEMORY_ISOLATION=y
CONFIG_MEMORY_HOTPLUG=y
# CONFIG_MEMORY_HOTPLUG_DEFAULT_ONLINE is not set
CONFIG_MEMORY_HOTREMOVE=y
CONFIG_MEMORY_BALLOON=y
CONFIG_MEMORY_FAILURE=y
```
and /sys/devices/system/memory is there available.

See also https://docs.kernel.org/admin-guide/mm/memory-hotplug.html

**Comment by Tom-python0121** [comment]
@karelzak You're right, but how do I start it?
### Steps to reproduce the issue

```console
[root@localhost ~]# grep CONFIG_MEMORY /boot/config-4.18.0-
config-4.18.0-193.el8.aarch64        config-4.18.0-348.2.1.el8_5.aarch64
[root@localhost ~]# grep CONFIG_MEMORY /boot/config-4.18.0-193.el8.aarch64
CONFIG_MEMORY_ISOLATION=y
# CONFIG_MEMORY_HOTPLUG is not set
CONFIG_MEMORY_BALLOON=y
CONFIG_MEMORY_FAILURE=y
# CONFIG_MEMORY is not set
```

**Comment by karelzak** [comment]
re-compile kernel with CONFIG_MEMORY_HOTPLUG=y, I guess ...

**Comment by Tom-python0121** [comment]
Thank you. According to the test, CONFIG_MEMORY_HOTPLUG needs to be enabled during kernel compilation. The test is passed,
I'll close the question right away.
