### ISSUE TITLE
Run CI tests for big-endian

### ISSUE THREAD

**Issue by t-8ch** [util-linux/util-linux#1808]
libblkid superblock probes do a lot of bit-fiddling.
It would be great to also validate them on big-endian.

**Comment by mator** [comment]
I do run tests sometimes on my BE machines (sparc64 and ppc64)... but CI would be nice to have...

**Comment by masatake** [comment]
When I got a bug report for lsfd from @mator, I recognized running a test target on BE machine was helpful for finding bugs.

So I introduced BE machine-based CI on my main project, ctags.
https://github.com/universal-ctags/ctags/blob/master/.github/workflows/testing-big-endian.yml is the one used in ctags.

**Comment by karelzak** [comment]
It would be nice to add Fedora to our GitHub actions and use it on s390x; what we need is:

- add .github/workflows/cibuild-setup-fedora.sh (see .github/workflows/cibuild-setup-ubuntu.sh)
- add a new "build-s390x" job to .github/workflows/cibuild.yml
- add CONFIGURE MAKE and CHECK steps (see the current build job)

Probably the most tricky is to create cibuild-setup-fedora.sh. The rest is copy & past.

Volunteers? ;-)
