### ISSUE TITLE
History of the write command

### ISSUE THREAD

**Issue by arabusov** [util-linux/util-linux#1817]
Write manual page (https://github.com/util-linux/util-linux/blob/master/term-utils/write.1.adoc) states that the write command first appeared in UNIX v6.  Meanwhile, I found that it does exist on the v5 disk and also referred in the v5 manual (see for example here: https://www.tuhs.org/Archive/Distributions/Research/Dennis_v5/)

**Comment by karelzak** [comment]
It seems you're right. 

BTW, an excellent document; the first sentence: "The number of UNIX installations is now above 50, and many more are expected." :-)
