### ISSUE TITLE
UUIDD_OP_RANDOM_UUID generates non-random UUIDs

### ISSUE THREAD

**Issue by jwilk** [util-linux/util-linux#1837]
https://github.com/util-linux/util-linux/commit/f27876f9c1056bf41fd940d5c4990b4277e0024f inadvertently changed `__uuid_generate_random` to `__uuid_generate_time`.
So now `uuidd` generates time-based UUIDs when asked for random-based ones:
```console
$ for i in {1..3}; do /usr/sbin/uuidd --random; done
f3f0939e-4866-11ed-b9b9-525400123456
f3f0fcc6-4866-11ed-b9b9-525400123456
f3f15b80-4866-11ed-b9b9-525400123456
```

**Comment by karelzak** [comment]
Oh, this is a pretty stupid bug. Thanks for your report!
