### ISSUE TITLE
Support BSD file lock in mkfs.{bfs,cramfs}

### ISSUE THREAD

**Issue by jiayi0118** [util-linux/util-linux#1842]
I found most of  fdisks-like and mkfs-like tools,  ```( cfdisk, sfdisk, fdisk, wipe fs, mkswap and mkfs.minix )```, have supported BSD file lock to avoid race condition with udevd. #921 

However, some mkfs-like tools ( ``` mkfs.bfs, mkfs.cramfs ``` ) are left out. Is there any reason not to apply BSD file lock mechanism for these two tools?

**Comment by karelzak** [comment]
No reason (well, the reason is limited human resources and bfs, and cramfs are not so critical). Send patch! ;-)

**Comment by jiayi0118** [comment]
okay, let me try to do this ;-)

**Comment by karelzak** [comment]
Fixed.
