### ISSUE TITLE
/etc/passwd was edited with the wrong shell path

### ISSUE THREAD

**Issue by shakai1** [util-linux/util-linux#1844]
Hi there,
I have just noticed this issue on chsh that I would like to report to you, including a solution that I would like to mention.
`# chsh  
Changing the login shell for root
Enter the new value, or press ENTER for the default
	Login Shell [/bin/zsh]: zsh
chsh: Warning: zsh does not exist
                                                                                
# exit
                                                                                
$ sudo chsh 
Password: 
chsh: PAM: Authentication failure`
After exiting "root" it is not possible to login back.
The solution is to edit /etc/passwd which now looks like this:
root:x:0:0:root:/root:zsh
to this:
root:x:0:0:root:/root:/bin/zsh

Maybe I am wrong, but I believe that this could be improved with something like the following, in order to check if zsh is installed first, before writing any changes to /etc/passwd.

This is an example in bash

`if ! command -v zsh
then
    #here editing the /etc/passwd part.
else 
   echo "zsh is not installed, please try another shell" 
    exit
fi`

Best regards.

Najib

**Comment by karelzak** [comment]
I'm not able to reproduce this problem:
```
# chsh
Changing shell for root.
New shell [/bin/bash]: bash
chsh: shell must be a full path name
```
It exits with an error if the shell specified by the user is not a full path.

And in the code we have
```C
static void check_shell(const char *shell)
{
        if (*shell != '/')
                errx(EXIT_FAILURE, _("shell must be a full path name"));
        if (access(shell, F_OK) < 0)
                errx(EXIT_FAILURE, _("\"%s\" does not exist"), shell);
        if (access(shell, X_OK) < 0)
                errx(EXIT_FAILURE, _("\"%s\" is not executable"), shell);
        if (illegal_passwd_chars(shell))
                errx(EXIT_FAILURE, _("%s: has illegal characters"), shell);
        if (!is_known_shell(shell)) {
#ifdef ONLY_LISTED_SHELLS
                if (!getuid())
                        warnx(_("Warning: \"%s\" is not listed in %s."), shell,
                              _PATH_SHELLS);
                else
                        errx(EXIT_FAILURE,
                             _("\"%s\" is not listed in %s.\n"
                               "Use %s -l to see list."), shell, _PATH_SHELLS,
                             program_invocation_short_name);
#else   
                warnx(_("\"%s\" is not listed in %s.\n"
                        "Use %s -l to see list."), shell, _PATH_SHELLS,
                       program_invocation_short_name);
#endif
        }      
}
```

Are you sure you have chsh from util-linux? (try chsh -v)

**Comment by shakai1** [comment]
I am using the chsh that 
chsh -v      
chsh: invalid option -- 'v'
Usage: chsh [options] [LOGIN]

Options:
  -h, --help                    display this help message and exit
  -R, --root CHROOT_DIR         directory to chroot into
  -s, --shell SHELL             new login shell for the user account

dpkg -l | grep util-linux
ii  util-linux                                       2.38.1-1                             amd64        miscellaneous system utilities
ii  util-linux-extra                                 2.38.1-1                             amd64        interactive login tools

**Comment by t-8ch** [comment]
Try `dpkg -S $(which chsh)`. On my Debian box `chsh` is provided by `passwd` and not `util-linux`

**Comment by shakai1** [comment]
Thank you for your replies. I have checked it. I was using chsh provided by passwd, and not util-linux. 
I have reported back to Debian the problem. I believe the solution would be that piece of code you guys here have posted.
