### ISSUE TITLE
unexpected reaction of rev to a string with \0

### ISSUE THREAD

**Issue by st-rafer** [util-linux/util-linux#1868]
Hi guys.

I have the current version 2.38.1 installed. I needed to reverse with `rev` a line where there were `\0` characters inside (this is a list of files obtained from `find` with `-print0`). I understood that `rev` considers only the usual `\n` characters as a string separator, but it suited me, I could process one long reversed string further in the pipeline. However, in the output from `rev`, I get only one first part of the string up to the first `\0` (although reversed).

I suspect that this is due to the special status of this character in strings in the C language in which the programs of this repository are written. However, is this a planned behavior (i.e. a feature), or is it more of a bug?

If this was not intended, then I see two solutions:
- either treat `\0` as ordinary characters;
- add the ability to set them as separators:
  -  in the form of a flag (such as `-z` for `cut`)
  -  the ability to define any separator at all (such as the `RS` variable for `awk`, for example).

In fact, the most ideal way would be to combine both ways — both processing as regular characters, and the ability to set as a line separator.

**Comment by karelzak** [comment]
All rev(1) code is based on strings (terminated by `\0`). It reads data from stdin/file as strings, etc. So, improving it means completely rewriting it.

I'm going to keep this issue open. Maybe some volunteers will happy to rewrite rev(1).
