### ISSUE TITLE
losetup: losetup  /dev/loop12345678 and lsblk incorrect display

### ISSUE THREAD

**Issue by zhangyao108** [util-linux/util-linux#1882]
![0DEF3626-874D-48D9-8BDB-C161529C364C](https://user-images.githubusercontent.com/110269838/200327013-039b4d74-b50c-445c-8a94-e11430ef3c60.png)
dd if=/dev/zero of=floppy.img bs=512 count=2880
losetup /dev/loop12345678 floppy.img
lsblk
display  error MAJ and MIN value.
![image](https://user-images.githubusercontent.com/110269838/200330150-4b7f859e-d6de-4a4e-a0a4-385901c0051e.png)
losetup can print error and return failure when loop number greater than the max value of MINOR

**Comment by karelzak** [comment]
lsblk uses /sys to get data from the kernel. If you see the device then the device very probably exists. Try
```
ls -la /sys/block/loop*
```
to see more details. 

On my system it ends with error:
```
# losetup /dev/loop12345678 floppy.img
losetup: /dev/loop12345678: failed to set up loop device: No such file or directory
```

**Comment by zhangyao108** [comment]
Thank you for your reply.
On my system it does exist:
`/sys/block/loop12345678 -> ../devices/virtual/block/loop12345678`

**Comment by karelzak** [comment]
It means that lsblk is right ;-)

**Comment by zhangyao108** [comment]
Yeah，It looks like different systems call losetup with different results。
On my system losetup /dev/loop12345678 floppy.img worked
