### ISSUE TITLE
DOS or MBR partition table

### ISSUE THREAD

**Issue by jonnygrant** [util-linux/util-linux#1890]
fdisk from util-linux 2.38

  o   create a new empty DOS partition table

May I ask if this could be clarified as :

 "o   create a new empty MBR partition table"

I've written lots of MBR and GPT partition table parsing drivers for embedded systems, but don't remember ever seeing them called DOS partition tables.

Microsoft and other documentation calls them MBR

https://learn.microsoft.com/en-us/windows-server/storage/disk-management/change-an-mbr-disk-into-a-gpt-disk

**Comment by karelzak** [comment]
For example, GNU Parted uses "msdos" for MBR.

**Comment by jonnygrant** [comment]
Hi. Yes, I saw Parted has msdos, more software calls it MBR, even Parted manual 2.4.2 says MBR.

gdisk man page only says MBR, it doesn't mention DOS at all.
https://man.archlinux.org/man/gdisk.8

Maybe both then, so it is clearer?
"o create a new empty DOS MBR partition table"
