### ISSUE TITLE
renice -n option does nothing

### ISSUE THREAD

**Issue by jengelh** [util-linux/util-linux#1892]
The `-n` option of util-linux's renice does not have any effect.

Background
=====

[O'Reilly documentation on Solaris 7](https://www.oreilly.com/library/view/solaristm-7-reference/0130200484/0130200484_ch17lev1sec12.html), published in 1999, mentions that Solaris 7 already had a renice -n option, and that it means to do an _increment_ (_relative_ priority). The absence of -n corresponds to an _absolute_ priority value.

FreeBSD added the -n option in 2002. The git commit log says "Implement POSIX -n option". So it seems -n has made it into POSIX since '97. The POSIX specs seem to [agree](https://pubs.opengroup.org/onlinepubs/007904975/utilities/renice.html) (date unknown) that -n is for relative priority values.

-n support was added in util-linux v2.14-420-g7cfbafda9 :

```
commit 7cfbafda9c484a8cadefc47ee115086e803d9391
Author: Karel Zak <kzak@redhat.com>
Date:   Mon Mar 9 21:09:50 2009 +0100

    renice: add -n option for compatibility with POSIX
    
    The -n option is required by POSIX.1-200x.
```

It has been "wrong" ever since.

Observed behavior
=====
```
21:44 f3:~ $ renice -n 2 $$
66328 (process ID) old priority 0, new priority 2
21:44 f3:~ $ renice -n 2 $$
66328 (process ID) old priority 2, new priority 2
21:44 f3:~ $ renice -n 2 $$
66328 (process ID) old priority 2, new priority 2
```

Expected behavior
=======
```
$ ssh root@192.168.217.16
OpenBSD 7.2 (GENERIC.MP) #758: Tue Sep 27 11:57:54 MDT 2022
-bash-5.1# renice -n 2 $$                                               
92353: old priority 0, new priority 2
-bash-5.1# renice -n 2 $$
92353: old priority 2, new priority 4
-bash-5.1# renice -n 2 $$
92353: old priority 4, new priority 6
```

**Comment by kraptor** [comment]
I sent a PR fixing this, but I'm not sure how impactful this will be, as there may be scripts relying on current behavior. I'll let `util-linux` maintainers decide what to do here.

**Comment by kraptor** [comment]
The PR was merged and I would close this bug. @jengelh, review al comments/discussions in the PR and also read about POSIXLY_CORRECT envvar, which will use the correct behavior for new versions should you rely on it. Unfortunately it's too late to change the behavior, but we implemented a workaround.
