### ISSUE TITLE
sfdisk: erroneous examples in the man page

### ISSUE THREAD

**Issue by Makiro** [util-linux/util-linux#1902]
Two examples are wrong in sfdisk man page.

Example 1:
`echo '+100M,' | sfdisk --move-data /dev/sdc -N 1 echo '2048,' | sfdisk /dev/sdc --append sfdisk /dev/sdc --reorder`
This should be on 3 different lines. The correct text is the same with line breaks:
`echo '+100M,' | sfdisk --move-data /dev/sdc -N 1`
`echo '2048,' | sfdisk /dev/sdc --append`
`sfdisk /dev/sdc --reorder`

Example 2:
`echo "," | sfdisk -N 3 --move-data /dev/sdc`
`Enlarge 3rd partition in both directions, move start to use free space before the partition and enlarge the size to use all free space after to the partition, and move partition data too.`
This command fails, saying `sfdisk: start of the partition has not been moved; ignoring --move-data`.
Tested with free space before and/or after the last partition of a disk.
Without `--move-data` sfdisk claim the partition table has been changed, but it has not.

**Comment by karelzak** [comment]
Ad example 2, you need `echo '+,+'` to enlarge the area.
