### ISSUE TITLE
mount and fstab link ntfs to ntfs3

### ISSUE THREAD

**Issue by Firestar-Reimu** [util-linux/util-linux#1905]
https://github.com/Paragon-Software-Group/linux-ntfs3/commit/1d07a9dfa19914ad27bdb9ec9ac0baa2329b2ae3

> When enabled, the windows_names mount option prevents the creation
of files or directories with names not allowed by Windows. Use
the same option name as NTFS-3G for compatibility.

ntfs3 added `windows_names` option and more compatible to NTFS-3G

for now mount still use ntfs-3g as ntfs default, and ntfs3 is more recommended for performance.

**Comment by sgn** [comment]
See also https://github.com/util-linux/util-linux/issues/1508
