### ISSUE TITLE
UUIDD Service fails on SUSE 15 SP4

### ISSUE THREAD

**Issue by lmvdz** [util-linux/util-linux#1907]
Issue: 

Nov 15 19:16:09 k2s systemd[1]: Starting Daemon for generating UUIDs...
Nov 15 19:16:09 k2s chown[17451]: /usr/bin/chown: cannot access '/var/lib/libuuid/clock.txt': No such file or directory
Nov 15 19:16:09 k2s systemd[1]: Started Daemon for generating UUIDs.
**Nov 15 19:16:09 k2s uuidd[17452]: /usr/sbin/uuidd: symbol lookup error: /usr/sbin/uuidd: undefined symbol: __uuid_generate_time_cont, version UUIDD_PRIVATE**
Nov 15 19:16:09 k2s systemd[1]: uuidd.service: Main process exited, code=exited, status=127/n/a
Nov 15 19:16:09 k2s systemd[1]: uuidd.service: Failed with result 'exit-code'.
Nov 15 19:16:09 k2s systemd[1]: uuidd.service: Start request repeated too quickly.
Nov 15 19:16:09 k2s systemd[1]: uuidd.service: Failed with result 'exit-code'.
Nov 15 19:16:09 k2s systemd[1]: Failed to start Daemon for generating UUIDs.

Fix:

Uninstalled uuidd-2.37.2-150400.8.8.1.x86_64
Installed uuidd-2.37.2-150400.6.5
`zypper install -f uuidd-2.37.2-150400.6.5`

> Reverting to an older version tells me this has something which changed in the newer version

**Comment by karelzak** [comment]
It seems you're mixing old libuuid and new (not yet released) uuidd. You must install also a new libuuid to use the current git tree.

**Comment by karelzak** [comment]
Or it seems you have an incomplete backport of "continuous clock handling" (commit 3cfba7d39b66eff4307218fefd8bb34bb1621f8).

**Comment by lmvdz** [comment]
Appreciate the quick response, not sure what I did wrong.

Normally I just do `zypper install uuidd`

perhaps something on AWS's end?

**Comment by karelzak** [comment]
Yes, please, report it to downstream (uuidd package provider). Thanks.
