### ISSUE TITLE
lscpu: How do you calculate the Thread(s) per CPU field (/sys/devices/system/cpu/cpu*/topology/thread_siblings)

### ISSUE THREAD

**Issue by TruncatedDinosour** [util-linux/util-linux#1919]
Hello, util-linux devs,

I am interested, after peeking into the source code of `lscpu`
spanning over 4 main files I'm confused, how does it get threads per core, I looked and found

https://github.com/util-linux/util-linux/blob/01cb80bae8e79b21067b4a85eb4f82b14104130c/sys-utils/lscpu-topology.c#L120..L121

to be probably the most important file for my goal, but for me they return `5` and `a` (I have 2 physical and 4 logical cores), which is not that related butttt using my brain I came up with this:

- `0xa` = 10 (hex -> dec)
- `0x5` = 5

So `10 / 5` is `2` meaning 2 threads per core, am I correct ?

But also questions:

- How do you deal with uneven core number (e.g. VMs), do you only read 2 ?
- How how you deal with the values at all

This is my output for `cat /sys/devices/system/cpu/cpu*/topology/thread_siblings`:

```
5
a
5
a
```

(`cpu{0..3}`)

Thanks for the answers in advance :)

**Comment by karelzak** [comment]
The `thread_siblings` is not a number of CPUs, it contains a mask where every set bit means one CPU, 0xa means CPU 1, and CPU 3. 

For humans, it's better to use CPU lists, for example, file `thread_siblings_list`.

Try `cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list`,  on my workstation I get:
```
cat /sys/devices/system/cpu/cpu*/topology/thread_siblings_list 
0,4
1,5
2,6
3,7
0,4
1,5
2,6
3,7
```
For example `0,4` means that logical CPU0 (thread) shares the physical core with CPU4, and so on. From this output it's obvious I have 4 cores (4 pairs of threads) and each has two threads.

**Comment by TruncatedDinosour** [comment]
> The `thread_siblings` is not a number of CPUs, it contains a bit mask where ever

thanks <3
