### ISSUE TITLE
This's official project to be at most Linux repo isn't it?

### ISSUE THREAD

**Issue by abdulbadii** [util-linux/util-linux#1925]
If yes,
Please correct this `mount` message/help as it is erroneous opposite direction
...
`
mount <operation> <mountpoint> [<target>]
`
...
i.e. illustrated as a point (of source)  -->  target

as it'd be the same pattern to `ln` illustrated in 

`
ln  <target>   <---  < point (of link, mount, source, etc) >
`
so one same pattern

and also (very likely) the preceding syntax lines
Please earnestly help, thanks before

**Comment by karelzak** [comment]
`mount --bind /mountpoint /target` is common and correct. We cannot change it after 20 years.
