### ISSUE TITLE
The rename command's bash-completion is --no-override instead of --no-overwrite

### ISSUE THREAD

**Issue by linjan2** [util-linux/util-linux#1928]
The bash completion for `rename --no-o<Tab><Tab>` is `--no-override`. I expected `--no-overwrite` since that's the option in the manpage. Running the command with `--no-override` prints:

```
rename: unrecognized option '--no-override'
Try 'rename --help' for more information.
```

https://github.com/util-linux/util-linux/blob/410b261cce8294653c03cb678f61512fa52e81e8/bash-completion/rename#L14

Using version 2.38.1 of util-linux.

**Comment by karelzak** [comment]
Thanks for your report, good catch!
