### ISSUE TITLE
Version of licenses not mentioned in some files

### ISSUE THREAD

**Issue by rahulmohang** [util-linux/util-linux#1932]
Hi,

The licenses of the following files are mentioned without the version information. 

https://github.com/util-linux/util-linux/blob/master/tests/helpers/test_byteswap.c
https://github.com/util-linux/util-linux/blob/master/tests/helpers/test_sigreceive.c
https://github.com/util-linux/util-linux/blob/master/tests/helpers/test_strerror.c
https://github.com/util-linux/util-linux/blob/master/tests/helpers/test_tiocsti.c
https://github.com/util-linux/util-linux/blob/master/sys-utils/zramctl.c

**Comment by karelzak** [comment]
See top-level project directory README.licensing file:
```
The ./COPYING file (GPL-2.0-or-later) is the default license for code without
an explicitly defined license.
```
but I agree that this is something we should fix and add to the files `SPDX-License-Identifier: GPL-2.0-or-later` line.

**Comment by rahulmohang** [comment]
Thank you.
