### ISSUE TITLE
libblkid: please define symbolic names (i.e. an enum) for blkid_do_safeprobe() return values

### ISSUE THREAD

**Issue by poettering** [util-linux/util-linux#1939]
As per: https://github.com/systemd/systemd/pull/25593

**Comment by karelzak** [comment]
Implemented.

The library internally already uses BLKID_PROBE_{OK,NONE}, so I have extended this functionality and moved it to the public library header.

**Comment by poettering** [comment]
Hmm, could you also add something like this immediately below the enum:
```c
#define BLKID_PROBE_OK BLKID_PROBE_OK
#define BLKID_PROBE_NONE BLKID_PROBE_NONE
…
```

i.e. define each enum also as a macro resolving to itself. Why? so that other codebases can use `#ifdef BLKID_PROBE_OK` to see if this new functionality is available or not.

In systemd we'd use that to define the four names on older versions of libblkid.

**Comment by poettering** [comment]
(also, should this appear somewhere in the gtkdocs?)

**Comment by karelzak** [comment]
@poettering, in this case, it would probably be better to use only #define rather than enum. The enum is nowhere used ad type (function argument, etc.).
