### ISSUE TITLE
blkdiscard -q for quiet and extra error code

### ISSUE THREAD

**Issue by psztoch** [util-linux/util-linux#1941]
1. New switch -q for quiet run is required for batch scripting.
These warnings should be silenced: 
```
warnx(_("Operation forced, data will be lost!"));
warnx("%s contains existing file system (%s).",path ,type);
warnx("%s contains existing partition (%s).",path ,type);
warnx("%s contains existing signature.", path);
```
Please add it.

2. Please add dedicated exit error code if discard command is unsupported by device.
This is important in scripts to distinguish whether the drive does not support TRIM or something else has gone wrong.
New error code should be documented in man for blkdiscard.
```
		case ACT_ZEROOUT:
			if (ioctl(fd, BLKZEROOUT, &range))
				 err(EXIT_FAILURE, _("%s: BLKZEROOUT ioctl failed"), path);
			break;
		case ACT_SECURE:
			if (ioctl(fd, BLKSECDISCARD, &range))
				err(EXIT_FAILURE, _("%s: BLKSECDISCARD ioctl failed"), path);
			break;
		case ACT_DISCARD:
			if (ioctl(fd, BLKDISCARD, &range))
				err(EXIT_FAILURE, _("%s: BLKDISCARD ioctl failed"), path);
			break;
```

**Comment by karelzak** [comment]
I agree that `Operation forced, data will be lost!` should be disabled by `--quiet`, but I'm not sure about the rest. 

The `contains existing ...` warnings are used before `This is destructive operation, data will be lost!` error (if --force not used). I have doubts the error before the previous warning about the content will make sense.

The dedicated exit error code makes sense.

**Comment by psztoch** [comment]
I will suggest hiding these warnings when there is -q and -f at the same time.
As I used force, it means that I take all risks on my chest.
But when I give -q it means I don't want warnings.

**Comment by psztoch** [comment]
Great job! We are now awaiting the Debian package update. :-)
