### ISSUE TITLE
hardlink: respect path components

### ISSUE THREAD

**Issue by brianjmurrell** [util-linux/util-linux#1942]
Much like the `--respect-name` option, it would be nice to be able to specify to respect the leading path components also under directories to link.  For example, I want to link across two directories, `foo/` and `bar/`, but I only want to link equal paths below those.  So if I invoke `hardlink --respect-path foo bar`, `foo/some/file` could be linked to `bar/some/file` but not `/bar/someother/file` since the leading paths are different.

**Comment by karelzak** [comment]
I have implemented it, but with a slight difference. Let's assume that the path has three fragments:

* root directory  (top-level dir) specified on hardlink command line; it's always ignored
* directory/directories, not ignored if  `--respect-dir` specified
* filename, not ignored if  `--respect-name` specified

It means your idea with --respect-path is possible by `hardlink --respect-dir --respect-name`.

Example (all files have the same content, two directories):
```
$ tree /tmp/foo /tmp/bar

/tmp/foo
└── some
    ├── A
    └── B

/tmp/bar
├── other
│   ├── A
│   └── B
└── some
    ├── A
    └── B
```
Classic --respect-name, link all the same files with the same names:
```
$ hardlink --respect-name --dry-run --ignore-time --verbose /tmp/foo /tmp/bar
[DryRun] Linking /tmp/foo/some/B to /tmp/bar/some/B (-5 B)
[DryRun] Linking /tmp/foo/some/B to /tmp/bar/other/B (-5 B)
[DryRun] Linking /tmp/foo/some/A to /tmp/bar/some/A (-5 B)
[DryRun] Linking /tmp/foo/some/A to /tmp/bar/other/A (-5 B)
```
New --respect-dir, link all files with the same directory name (`some` or `other`):
```
$ hardlink --respect-dir --dry-run --ignore-time --verbose /tmp/foo /tmp/bar
[DryRun] Linking /tmp/foo/some/B to /tmp/bar/some/B (-5 B)
[DryRun] Linking /tmp/foo/some/B to /tmp/foo/some/A (-5 B)
[DryRun] Linking /tmp/foo/some/B to /tmp/bar/some/A (-5 B)
[DryRun] Linking /tmp/bar/other/B to /tmp/bar/other/A (-5 B)
```
Both together, the same dirs and same filenames; note that `other` is ignored because
it contains A and B (different names) and dir name is not used for other files.
```
$ hardlink --respect-dir --respect-name --dry-run --ignore-time --verbose /tmp/foo /tmp/bar
[DryRun] Linking /tmp/foo/some/B to /tmp/bar/some/B (-5 B)
[DryRun] Linking /tmp/foo/some/A to /tmp/bar/some/A (-5 B)
```

**Comment by brianjmurrell** [comment]
Nice.  Is the search optimized and efficient for the `--respect-path` case?

So expanding on your example above, if we have two directories:

```
$ tree /tmp/foo /tmp/bar

/tmp/foo
├── other
│   ├── A
│   └── B
└── some
    ├── A
    └── B

/tmp/bar
├── other
│   ├── A
│   └── B
└── some
    ├── A
    └── B
```

does:

```
$ hardlink --respect-dir --dry-run --ignore-time --verbose /tmp/foo /tmp/bar
```

descend down `/tmp/foo/some` and `/tmp/bar/some` and then decide what can be linked across them before discarding all of the data in those two trees (since it's no longer needed due to `--respect-dir` and then descending down `/tmp/foo/other` and `/tmp/bar/other`, and so on?  Or does it still evaluate the entire two `/tmp/bar` and `/tmp/foo` directories together in their entirety before deciding what can be linked?

**Comment by karelzak** [comment]
The hardlink process involves two main steps. 
 
1) Scanning all directories and creating a binary tree from files, where each
node represents a specific size. Files with the same size are added to a linked
list within the same node, and these files are then ordered based on the
specified options such as --keep-*, number of links, time, etc. This order
determines which files will be used as the source and target for the links
(this order defines the priority of the files).
                                              
2) Traversing the tree and comparing the content of files with the same size.
If the content is identical, hardlinks are created between these files.

See also https://github.com/util-linux/util-linux/issues/3016. In the next release, the option --prioritize-trees will be available to prioritize trees according to the position specified on the command line.
