### ISSUE TITLE
chsh: About --help's Short Option

### ISSUE THREAD

**Issue by carbongreat13** [util-linux/util-linux#1947]
When I run `chsh --help`, I get the following message:

```
Usage:
 chsh [options] [<username>]

Change your login shell.

Options:
 -s, --shell <shell>  specify login shell
 -l, --list-shells    print list of shells and exit

 -u, --help           display this help
 -v, --version        display version

For more details see chsh(1).
```

On the other hand, in man chsh, the `--help` short option is considered `-h`, not `-u`.
Which is the correct short option?
Since `--help` and man say different things, I believe I need to make a correction.

**Comment by kraptor** [comment]
Sent PR to fix this: https://github.com/util-linux/util-linux/pull/1954

**Comment by karelzak** [comment]
It should be fixed now. Thanks!
