### ISSUE TITLE
hwclock: device search order

### ISSUE THREAD

**Issue by sodface** [util-linux/util-linux#1956]
I have a device with an rtc but no internal battery. On Alpine Linux, /dev/rtc0 is created for this device. I've added a battery backed rtc which is /dev/rtc1.

By default, at least on Alpine, /dev/rtc is a symlink to /dev/rtc0. After adding /dev/rtc1 just updating the symlink was not sufficient because /dev/rtc0 precedes /dev/rtc in the device search order:

> ... will use the first one found in this order: /dev/rtc0, /dev/rtc, /dev/misc/rtc.

I solved this by passing `--rtc=/dev/rtc1` to the init script but I'm curious about the logic of the search order and wonder if you would consider changing it to /dev/rtc first followed by /dev/rtc0?

**Comment by karelzak** [comment]
Unfortunately, this is not a good idea. 

The node 'rtc' is usually a classic device we do not want to use if possible, and preferred is `rtc0` as it's a new RTC framework node. This is the reason why the code uses:
```
       static const char *fls[] = {
#ifdef __ia64__
                "/dev/efirtc",
                "/dev/misc/efirtc",
#endif  
                "/dev/rtc0",
                "/dev/rtc",
                "/dev/misc/rtc"
        };
```

I think using `--rtc=` is the ideal solution if you do not need the default order.

**Comment by sodface** [comment]
Thank you for the explanation and consideration, closing.
