### ISSUE TITLE
po/LINGUAS does not have 'ko' although translation has been filled 

### ISSUE THREAD

**Issue by darkcircle** [util-linux/util-linux#1985]
Hello, This is Cho, Korean translator of util-linux.

I investigated my long time for this package, during any months,
some of translation seems to be applied,
but I found that  'ko' does not included in po/LINGUAS.

Could you add as a new locale?

**Comment by karelzak** [comment]
Thanks for your report and translations. The problem should be fixed now.

**Comment by darkcircle** [comment]
@karelzak Thank you for fixing. i love it.
