### ISSUE TITLE
`signame_to_signum` is incorrectly locale-sensitive

### ISSUE THREAD

**Issue by cgwalters** [util-linux/util-linux#1991]
The use of locale-sensitive functions like `strcasecmp` and `toupper` operating on ASCII data seems fairly pervasive in this project.

See https://github.com/ostreedev/ostree-rs-ext/pull/442 for a bug that was only triggered in the Turkish locale:

```
$ LANG=tr_TR.UTF-8 setpriv --pdeathsig TERM true
$ LANG=C.UTF-8 setpriv --pdeathsig SIGTERM true
$ LANG=tr_TR.UTF-8 setpriv --pdeathsig SIGTERM true
setpriv: bilinmeyen sinyal: SIGTERM
```

In glib there's [g_ascii_strcasecmp](https://developer-old.gnome.org/glib/stable/glib-String-Utility-Functions.html#g-ascii-strcasecmp) and in systemd `ascii_strcasecmp_n()` that should be used here.

**Comment by karelzak** [comment]
We already have include/cctype.h (for ctype.h like macros), I will implement strcasecmp too.
