### ISSUE TITLE
agetty: Add support for reading options from systemd credentials

### ISSUE THREAD

**Issue by DaanDeMeyer** [util-linux/util-linux#2012]
systemd uses agetty via a number of service units (getty@.service, serial-getty@.service, container-getty@.service, ...). To configure agetty in this setup, users have to override the `ExecStart=` line of these units to add or remove command line options for agetty. For mulitple reasons, this isn't exactly a streamlined way to configure agetty.

Instead, I would propose that we add support to read options from systemd credentials to agetty. https://systemd.io/CREDENTIALS/ contains more information on credentials. In short, when credentials are configured for a service, systemd will set the `CREDENTIALS_DIRECTORY` environment variable which contains files named after the credentials whose contents are the credential value. agetty would have to check if the environment variable is set, check if a file named after the credential we're trying to read exists, and read the file if it exists. agetty's command line options would still override any configured credentials.

Some examples of options that could be configured via credentials:
- autologin (`agetty.autologin`)
- baud rate (`agetty.baud_rate`)
- hangup (`agetty.hangup`)
- timeout (`agetty.timeout`)
- ...

Another advantage of credentials would be that it would be possible to configure agetty at system first boot instead of having to write a systemd dropin when building an image. systemd can read credentials from smbios so one could imagine the following qemu command line to configure the system at runtime to do autologin:

```
qemu ... -smbios type=11,value=io.systemd.credential:agetty.autologin=1 ...
```

This would work with any disk image without having to modify it upfront to add a dropin that adds --autologin to the agetty command line. Being able to configure agetty like this without having to modify the image would be extremely useful.

**Comment by karelzak** [comment]
Interesting. If I understand, then the application (agetty) will read 

   $CREDENTIALS_DIRECTORY/hangup
   $CREDENTIALS_DIRECTORY/autologin
 
to get the options. The names of the files (e.g. "autologin") are hardcoded in the application, right? 

And for example, the option "autologin" defines username, so "agetty.autologin=smith" (if we want to follow agetty command line)

Sound good. It should be pretty simple to implement (especially when we already have lib/path.c to read small files from a directory).

What about security? For example agetty.autologin= could be relatively dangerous if an unauthorized user will be able to specify it on system boot.

@poettering any comment?

**Comment by DaanDeMeyer** [comment]
> Interesting. If I understand, then the application (agetty) will read

> $CREDENTIALS_DIRECTORY/hangup
> $CREDENTIALS_DIRECTORY/autologin

It would be the following but yeah, the names would be hardcoded:

```
$CREDENTIALS_DIRECTORY/agetty.hangup
$CREDENTIALS_DIRECTORY/agetty.autologin
```

> What about security? For example agetty.autologin= could be relatively dangerous if an unauthorized user will be able to specify it on system boot.

You can already use the `tmpfiles.extra` credential to write arbitrary files using systemd-tmpfiles, which could theoretically be used to add a dropin for a agetty service to add --autologin to the CLI options. So by adding the `agetty.autologin` credential, you're not adding a new backdoor.

Credentials can be both trusted and untrusted, anything from the ESP is considered untrusted and has to be accessed explicitly using `LoadCredentialEncrypted` or using an explicit absolute path to the credential. Credentials from the VM manager or container manager can be considered trusted. In systemd, we'd make sure the credentials for agetty are only loaded from trusted sources.

**Comment by poettering** [comment]
> And for example, the option "autologin" defines username, so "agetty.autologin=smith" (if we want to follow agetty command line)
> 
> Sound good. It should be pretty simple to implement (especially when we already have lib/path.c to read small files from a directory).
> 
> What about security? For example agetty.autologin= could be relatively dangerous if an unauthorized user will be able to specify it on system boot.
> 
> @poettering any comment?

credentials are supposed to be "trusted", i.e. are only imported from trusted sources, and are strictly stored with restricted access (i.e. they are typically not transported via /proc/cmdline where they are world readable — except for debugging). hence, yes they should be safe for something like "agetty.autologin=".

systemd already does various hook-ups like this with major security implications if there was a way to set them from an untrusted source. hence if agetty did the same this wouldn#t add any real new security issues, it would be broken much worse by systemd already.

**Comment by poettering** [comment]
So yeah, would love this hook-up.

Note that creds must be explicitly imported from service manager to service via LoadCredentials=. Right now getty@.service unit file is maintained in systemd, but agetty binary in util-linux. So you'd have to ask us to add every single cred there.

That said, I figure we shold just add wildcard imports, i.e. `LoadCredentials=agetty.*` would import all of the relevant creds at once. and then you could add whatever cred you want with that as long as you stick to the `agetty.` prefix.

**Comment by DaanDeMeyer** [comment]
We're adding credential globbing support in https://github.com/systemd/systemd/pull/26059
