### ISSUE TITLE
logger: write log to a system log that has no permission

### ISSUE THREAD

**Issue by zhangyao108** [util-linux/util-linux#2014]
logger can write log to a system log that has no permission.
```
logger -id -p local1.error -t sysalarm "i am test "
```

sysalarm.log contains  "i am test" , but user no permission

**Comment by karelzak** [comment]
This is expected behavior -- logger(1) does not check any permissions. It just writes to /dev/log socket, and it's syslog (or journald) business to evaluate who and what.

Please, check your syslog or journald configuration for more details.
