### ISSUE TITLE
mount -T ignores "none" (needed for swap)

### ISSUE THREAD

**Issue by cryptarch** [util-linux/util-linux#2017]
Hey there,

My init scripts (gentoo) use `mount -vaT /etc/fstab.d/` to add some extra mounts late in the boot process. In particular, I want to set up swap this way, since it first requires a writable root filesystem to cryptsetup `/swapfile`. This means I can't put swap in the usual /etc/fstab, instead it needs to be staggered out until a later step.

I have other files under /etc/fstab.d and they are all mounting correctly. However, the swap configuration is skipped due to using `none` in the second field. I can reproduce the issue manually (eliding other irrelevant mountpoints):

```
# mount -vaT /etc/fstab.d/
...
none                     : ignored
...
```

More specifically:
```
# mount -vaT /etc/fstab.d/swap.fstab
none                     : ignored
```

Contents of the file:

```
# cat /etc/fstab.d/swap.fstab
/dev/mapper/swap none swap defaults,nofail 0 0
```

I also tried `auto` instead of none, and the output became `auto :ignored`.

Have I misconfigured something, or am I right in thinking that `mount` is not behaving correctly here?

**Comment by karelzak** [comment]
mount(8) does not activate swap areas -- you need to use swapon. 

Unfortunately, the current swapon does not accept `-T dir`; I'll improve it.

**Comment by karelzak** [comment]
Fixed. In the new version, you need to use `swapon --all --fstab /etc/fstab.d/` in your init scripts.

**Comment by cryptarch** [comment]
Hmm, okay, thanks. I already have a workaround which uses swapon.

I think it is usually possible to specify a swapfile in /etc/fstab, and I thought `mount` was the one who handles all those lines, regardless of whether they use swapon under the hood.
