### ISSUE TITLE
Enable to use both --ctime and --file options in the same commande 

### ISSUE THREAD

**Issue by marcoBros** [util-linux/util-linux#2020]
Ouput with `--file` option doesn't work properly. Some Spacing are added after the first log line :(

```
$ dmesg --file /var/log/dmesg.0
[    0.000000] kernel: microcode: microcode updated early to revision 0xf0, date = 2021-11-12
                              [    0.000000] kernel: KERNEL supported cpus:
                              [    0.000000] kernel:   Intel GenuineIntel
                              [    0.000000] kernel:   AMD AuthenticAMD
                              [    0.000000] kernel:   Hygon HygonGenuine
                              [    0.000000] kernel:   Centaur CentaurHauls
                              [    0.000000] kernel:   zhaoxin   Shanghai  
```

Then it's not possible to convert time with `--ctime`
```
$ dmesg --file /var/log/dmesg.0 --ctime
[mar. janv. 17 02:59:56 2023] kernel: microcode: microcode updated early to revision 0xf0, date = 2021-11-12
                              [    0.000000] kernel: KERNEL supported cpus:
                              [    0.000000] kernel:   Intel GenuineIntel
                              [    0.000000] kernel:   AMD AuthenticAMD
                              [    0.000000] kernel:   Hygon HygonGenuine
                              [    0.000000] kernel:   Centaur CentaurHauls
                              [    0.000000] kernel:   zhaoxin   Shanghai  
```

**Comment by karelzak** [comment]
It works for me.
```shell
$ /usr/bin/dmesg --raw > aaa
$ /usr/bin/dmesg -F aaa
```
don't forget that the input format has to be "raw" syslog format:
```
$ head -3 aaa
<6>[1249612.562594] Enabling non-boot CPUs ...
<6>[1249612.562630] x86: Booting SMP configuration:
<6>[1249612.562631] smpboot: Booting Node 0 Processor 1 APIC 0x2
```

**Comment by marcoBros** [comment]
@karelzak 

The issue is raised when both `--file` and `--ctime` options are used in the same command.
By the way, `--ctime` option works fine without `--file` option`.
And `--raw` cannot be used with `--ctime` option, but not sure it's an issue with `--raw`.

In definitive it's unpossible to convert time from a specified file...

**Comment by t-8ch** [comment]
@marcoBros How did you create the file `/var/log/dmesg.0`?
Can you show the first three lines directly from the file: `head -3 /var/log/dmesg.0`?

**Comment by marcoBros** [comment]
I did not created `/var/log/dmes.0`

Following this [thread](https://unix.stackexchange.com/questions/181067/how-to-read-dmesg-from-previous-session-dmesg-0) it's automatically rotated at end of boot :
> Towards the end of the boot process, dmesg is invoked to write the boot messages to /var/log/dmesg (with older versions of that file being rotated in the usual manner).

First 3 line of `/var/log/dmesg.0` looks okay :
```
$ head -3 /var/log/dmesg.0
[    0.000000] kernel: microcode: microcode updated early to revision 0xf0, date = 2021-11-17
[    0.000000] kernel: Linux version 5.15.0-58-generic (buildd@lcy02-amd64-101) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 (Ubuntu 5.15.0-58.64-generic 5.15.74)
[    0.000000] kernel: Command line: BOOT_IMAGE=/boot/vmlinuz-5.15.0-58-generic root=UUID=23242b17-85a8-4c85-a34f-92c9428404a3 ro quiet splash vt.handoff=7
```

The [thread](https://unix.stackexchange.com/questions/181067/how-to-read-dmesg-from-previous-session-dmesg-0) said as well :
>  `dmesg` does not read from `/var/log/dmesg`. It reads directly from the kernel ring buffer and gives you the most recent N messages

Probably dmesg has a different implementation between getting data from the kernel ring buffer and from a file, maybe ?

I guess that's why `dmesg` is not able to convert time with `--ctime` as data do not come from a buffer

**Comment by t-8ch** [comment]
Your file `/var/log/dmesg.0` is a file created by your syslog daemon. It's format has been defined by that daemon.

The `dmesg` tool itself can *only* parse its own "raw" format when reading data from a file.
Your log file does not have that format.

Please read the [first response](https://github.com/util-linux/util-linux/issues/2020?notification_referrer_id=NT_kwDOAAr0TbE1MzQ5NDM0MzQ1OjcxNzkwMQ#issuecomment-1385664957) again
