### ISSUE TITLE
RFE: blkid/libfdisk: automatically probe intended sector size of disk image

### ISSUE THREAD

**Issue by poettering** [util-linux/util-linux#2022]
When dissecting a disk image file both libblkid and libfdisk currently default to assume the image is intended for 512b sector disks. It would be great if it would be able to auto-detect the intended sector size. For GPT this should work really well. We added something like this recently to systemd:

https://github.com/systemd/systemd/pull/26092

I think it would make sense if this was done in libblkid/libfdisk instead.

(and even better would be if losetup one day could hook into libblkid to automatically attach such disk images with the right sector size if told so)

**Comment by poettering** [comment]
dang, seems i already asked for this before #1598. closing this one.

**Comment by karelzak** [comment]
Oh, I also forgot the old request. Sorry.
