### ISSUE TITLE
Script session logging

### ISSUE THREAD

**Issue by Izerrion** [util-linux/util-linux#2024]
Hello team!

Can you please provide an advice how to implement additional script command argument variable like "script -u <user_name> -I /proc/1/fd/1" that will append this <user_name> to every stdin log line, so it would look something like this:

...session started...
<user_name> | cmd1
<user_name> | cmd2
...session ended...

The reason why this useful is when you trying to pipe session logs directly to stdout for instant log collection and later audition.
While you can save logs to a file and name the file with specific user extension, the same can't be done if these logs piped directly to stdout. I assume some simple source code modifications are needed, can you provide directions where should I put what please?

Moreover, I want to apply the same fix for stdout stream as well if it is possible, e.g. marking each line of stdout with specific <user_name> preffix.

**Comment by karelzak** [comment]
I have doubts it's possible to implement it reliably. 

Remember that the log data are raw and without any formatting. Script (1) is not line-oriented; it's a continuous stream of bytes. For example, quotes (" " or ' ') allow you to use line breaks within the command, and how it's interpreted depends on the shell, etc. And it also records all control keys, backspace, etc. It's very complex to interpret correctly (like the terminal driver does). 

If you want to separate users, it would be better to use separate file descriptors, FD (e.g., FIFO) per user. I guess you can do it when you start the session.

**Comment by Izerrion** [comment]
FIFO will work as well as any "text header" prior to the connection that distinguishes the user. However I'm printing all script output to stdout of docker container for log collection as a first line of audit on ssh bastion host.  Problems arise when multiple users are connected at the same time, then these script sessions intersect, so you can't distinguish which user did what. Of course, you can save different sessions to different files and parse them separately, but it is not optimal approach to solving that issue. 

The somewhat solution that i've discovered is to use the following command:
script -a -q -O  /proc/1/fd/1   (yep, docker stdout)

As you can see it is called without "-f" flag to flush the written output and script only records output. 
Now the ssh sessions do not intersect, since they are printed  to docker stdout only when they are finished. Yep, it requires to force close all dangling ssh session that do some keep alive commands.  It serves its purpose, since we can only take the lines that start as "user@<hostname>:#" from connection header to another connection header.

I wonder if script binary can be patched that way, so we can only see exactly these lines of actual output, without keystrokes and all other terminal output.
