### ISSUE TITLE
Can fstrim add a new option to ignore some filesystem or partition?

### ISSUE THREAD

**Issue by Zesko** [util-linux/util-linux#2040]
I read some news about Kernel 6.2: The filesystem BTRFS enables `discard=async` by default. 
This is why fstrim does not need to be run again.

But I have multiple partitions EXT4 and BTRFS on the same Nvme SSD.
I need fstrim for EXT4 or other filesystems e.g. XFS on any SSD, not Btrfs.

I would like to add a new option `--ignore btrfs` or some other for fstrim that should not trim Btrfs.

________________

I am not sure, if fstrim and `discard=async` will run parallel on Btrfs without breaking

**Comment by karelzak** [comment]
You can add X-fstrim.notrim options to your fstab to disable the filesystem.

And I have added -t,--types to make fstrim compatible with mount(8) --all.

**Comment by Zesko** [comment]
Thanks!
