### ISSUE TITLE
Add --properties-by={udev,blkid,file} to lsblk

### ISSUE THREAD

**Issue by karelzak** [util-linux/util-linux#2047]
lsblk reads information from udev, and if unsuccessful, then from libblkid, if --sysroot specified, then from a file.

It would be nice for some use cases (https://github.com/coreos/fedora-coreos-config/pull/2181) to have a command line option to force lsblk to use non-default order how to get properties.

**Comment by sugartang105** [comment]
Hello, may I ask if the code for this issue has not been submitted yet? Are there any alternative workarounds?

**Comment by karelzak** [comment]
> Hello, may I ask if the code for this issue has not been submitted yet? Are there any alternative workarounds?

I have submitted it now :-)
