### ISSUE TITLE
util-linux/include/cctype.h license

### ISSUE THREAD

**Issue by hfuse** [util-linux/util-linux#2050]
Latest libblkid.so are created some files. And blkid/src/superblocks/iso9660.c is one of them.
We can find following lines in libblkid/src/Makefile.am

libblkid_la_SOURCES = \
        include/list.h \
        \
                     :
        libblkid/src/superblocks/iso9660.c \
                     :

And following commit added '#include "cctype.h"' line to iso9660.c

  - https://github.com/util-linux/util-linux/commit/dab6d75cfc344a9477889778fe3f84748c9742a8

Because  the license of "include/cctype.h" is GPLv2, latest license of libblkid.so is also GPLv2.
I also found COPYING file of libblkid which shows the license is LGPLv2.1.
Which one is correct?

**Comment by karelzak** [comment]
Good catch. This is a bug. I'll fix it. I guess it should be possible to get this code under LGPL from gnulib.
