### ISSUE TITLE
agetty: Screen cleared despite using --noclear

### ISSUE THREAD

**Issue by jimis** [util-linux/util-linux#2051]
I'm using agetty from util-linux-2.38.1-6.1.x86_64 package in OpenSUSE-Tumbleweed. Here is the agetty command line as listed in `ps`:
```
/sbin/agetty -o -p -- \u --noclear - linux
```

What I notice is that as boot finishes, `/etc/issue` is printed and the login prompt appears, but **a few seconds later** the screen is cleared and `issue` and login prompt are re-printed.

I believe this happens because my server boots very fast, and the network setup is finished **after** the login prompt.
It seems it's caused because my `issue` file contains `\4{interface_name}` and `\6{interface_name}`. If I remove these, the screen does not get cleared. And when the tty is not cleared, I notice that some extra kernel messages are printed right after the login prompt, that indicate network interface status changes (`IPv6: ADDRCONF(NETDEV_CHANGE)...`).

I open this bug because the terminal should never be cleared if `--noclear` is passed. Agetty could re-print the whole `issue` after a network status change, or only the relevant lines that contain `\[46]`.

**Comment by karelzak** [comment]
Note that you can force agetty to reload by `agetty --reload` from the normal session.

**Comment by karelzak** [comment]
Thanks for your report!

**Comment by jimis** [comment]
Thanks for fixing it so quickly!
