### ISSUE TITLE
making cal use terminal-colors.d

### ISSUE THREAD

**Issue by ftonneau** [util-linux/util-linux#2053]
On my system (Arch), the man page for **cal** says that 

output colorization is implemented by terminal-colors.d(5) functionality

Yet, the man page does not mention any logical name (e.g., "standout" or "current" or "day") that could be used in a **terminal-colors.d/cal.scheme** config file. As a result, it seems that cal cannot be colorized via terminal-colors.d. Is this a bug, or am I missing something?

**Comment by karelzak** [comment]
cal (1) uses standout mode (reverse color) for the current day. And it's hard coded. There is no possibility to set any other color by terminal-colors.d -- it only allows disable/enable colors.

I agree this is very limited support, and it would be nice to have support for a more rich scheme. My suggestion is to support logical names to colorize the current day, headers, weekend days, week numbers, etc.

**Comment by ftonneau** [comment]
Thanks a lot, adding actual support for logical names would be great! Meanwhile, we can do with a bit of piping and sed/awk :-).

**Comment by karelzak** [comment]
Implemented, thanks to @t-8ch. Closing ...
