### ISSUE TITLE
spelling mistake creates error when compiling

### ISSUE THREAD

**Issue by JohnCronk79** [util-linux/util-linux#2057]
Hello, I ran into an error while trying to compile this package. I am very very new to Linux, and Github, so please forgive me if I have the format of this bug report wrong.

### System Environment
- Asustor NAS running busybox
- downloaded with:  wget https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.38/util-linux-2.38.1.tar.gz
- configured with:  ./configure --docdir=/volume1/home/jcronk/Documents --disable-chfn-chsh --disable-login --disable-nologin --disable-su --disable-setpriv --disable-runuser --disable-pylibmount --disable-static --without-python --without-system --without-systemdsystemunitdir
- ran "make -j4"
- produced the following error:

```
libfdisk/src/gpt.c: In function 'gpt_read_entries':
libfdisk/src/gpt.c:1021:20: error: 'SSIZE_MAX' undeclared (first use in this function); did you mean 'SIZE_MAX'?
  if (sz > (size_t) SSIZE_MAX) {
                    ^~~~~~~~~
                    SIZE_MAX
libfdisk/src/gpt.c:1021:20: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:10754: libfdisk/src/la-gpt.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/bin/util-linux-2.38.1'
make[1]: *** [Makefile:15060: all-recursive] Error 1
make[1]: Leaving directory '/bin/util-linux-2.38.1'
make: *** [Makefile:6462: all] Error 2
```

### Proposed Solution
**Path**
     /bin/util-linux-2.38.1/libfdisk/src

**File** 
     gpt.c (line 1021, col 27)

**Current Content**
     if (sz > (size_t) SSIZE_MAX) {

**Research**
- searched the rest of the file for 'SSIZE_MAX' with no results
- searched the file for the probable solution 'SIZE_MAX' and found one reference on line 388 col 39

**Proposed Correction - Remove Extra "S" and save file**
     if (sz > (size_t) SIZE_MAX) {

### My Result
running 'make -j4' again continued the compile without fatal errors. However a few errors were noted which I have not looked into yet. Here is a copy of the end result of the 'make -j4':

```
make[4]: *** [Makefile:16775: install-exec-hook-wall] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/bin/util-linux-2.38.1'
make[3]: *** [Makefile:16039: install-exec-am] Error 2
make[3]: Leaving directory '/bin/util-linux-2.38.1'
make[2]: *** [Makefile:15378: install-am] Error 2
make[2]: Leaving directory '/bin/util-linux-2.38.1'
make[1]: *** [Makefile:15060: install-recursive] Error 1
make[1]: Leaving directory '/bin/util-linux-2.38.1'
make: *** [Makefile:15371: install] Error 2
root@JC-NAS-Server:/bin/util-linux-2.38.1 #
```

_Hope this helps. Much love from Canada, take care !!_

**Comment by karelzak** [comment]
SSIZE_MAX is no a typo; it's defined in /usr/include/bits/posix1_lim.h, but it seems we do not need it in code.
