### ISSUE TITLE
umount --quiet does not work when not superuser

### ISSUE THREAD

**Issue by Seneral** [util-linux/util-linux#2060]
The --quiet / -q option of umount does not take effect unless executed as superuser.

Example commands that exhibit this behaviour (all I tested):
```
umount -q /dev/sdb
umount -q /mnt/location
umount -q ~/test_image.img
```
Where the location is not a mounted device or a mounting point.

**Expected behaviour:**
No output.

**Observed behaviour:**
`umount: *****: not mounted.`

**Workaround:**
Execute as superuser (with sudo or as root) produces expected behaviour.
Redirecting output to /dev/null also supresses `not mounted` messages, but also other ones, especially the `must be superuser to unmount.` ones which I would like to pass on.

**Versions tested:**
umount from util-linux 2.37.2
umount from util-linux 2.38.1084-ce2d9 (current repository head)

**Comment by karelzak** [comment]
Good catch. Thanks for your report!
