### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by aixiaoxiaoyu** [util-linux/util-linux#2062]
Ubuntu2022.04

<img width="739" alt="image" src="https://user-images.githubusercontent.com/14014477/217754154-f9b78a10-c425-44e1-b1c0-114a9cf57d22.png">

**Comment by t-8ch** [comment]
Do you have the `msgfmt` tool available?
If not install the `gettext` package, delete the source tree and start from scratch.

**Comment by aixiaoxiaoyu** [comment]
Gettext package doesn't exist, so make failed!

**Comment by aixiaoxiaoyu** [comment]
> Do you have the `msgfmt` tool available? If not install the `gettext` package, delete the source tree and start from scratch.

Thank you.
