### ISSUE TITLE
mount: mount options is order-sensitive

### ISSUE THREAD

**Issue by fingolfin0** [util-linux/util-linux#2087]
I ran into this bug, to try to configure the mounting of the nfs4 share. Maybe the order of options in "-o" should be matter, but in particular my case it is a bug. So, let's try to mount an nfs4 share:
```bash
mount -t nfs4 my_host:/my_path/my_folder my_folder/ -o user,exec
mount | grep nfs4 | cut -d " " -f 6
# OUTPUT: (rw,nosuid,nodev,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.30,local_lock=none,addr=192.168.1.30,user)
```
This behavior is expected. But now let's try to change `user` and `exec` in places:
```bash
mount -t nfs4 my_host:/my_path/my_folder my_folder/ -o exec,user
mount | grep nfs4 | cut -d " " -f 6
# OUTPUT: (rw,nosuid,nodev,noexec,relatime,vers=4.2,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.1.30,local_lock=none,addr=192.168.1.30,user)
```
Please note that `noexec` has appeared in the mounting options, which should not happen. The same applies to the fstab file.

I checked this bug in versions 2.37.4 (in Gentoo) and 2.38.1 (in Manjaro).

**Comment by karelzak** [comment]
This is expected behavior. The last option always wins, and `user` is converted to `noexec,nodev,nosuid`, so in your example the command line is `-o exec,noexec,nodev,nosuid`.

I have added a note about it to the man page to make it more obvious.
