### ISSUE TITLE
more(1) assumes that all files end with newline

### ISSUE THREAD

**Issue by jidanni** [util-linux/util-linux#2108]
more(1) assumes that all files end with newline
pr(1) is smarter and takes no chances,
lest the header of the following file get knocked around.
Test with:
```
x=ooooooooooooooooooo
echo -n $x > a
echo    $x > b
echo    $x > c
more ? | cat
pr --form-feed ? | cat
```
Thus we are forced to pipe more(1)'s output through this repair filter:
```
perl -pwle 's/(.)(::::::::::::::)/$1\n$2/'
```
more from util-linux 2.38.1

**Comment by karelzak** [comment]
It should be fixed in v2.39 by 28b391ce7e58f8327c092b3911c05f526d0ad586.
