### ISSUE TITLE
Documentation/releases/v2.39-ReleaseNotes review and updates

### ISSUE THREAD

**Issue by karelzak** [util-linux/util-linux#2109]
Please, please, ... @t-8ch, @masatake, and others, review and update v2.39-ReleaseNotes.

The current version of the file in the git tree is very raw (I'll check it by spellchecker later), and I'm sure I have forgotten some important highlights, especially about lsfd ;-)

Thanks!

**Comment by t-8ch** [comment]
The last two points of `blkid(8)` are not written correctly.

Maybe the expansion of the CI to more architectures?

dmesg: level ranges?

meson: expansion of functionality

more translated manpages
