### ISSUE TITLE
Documentation glitch: SYNOPSIS line breaks lost

### ISSUE THREAD

**Issue by jimav** [util-linux/util-linux#2111]
The SYNOPSIS shows the 3 ways of calling `getopt` all run together.  It looks like line breaks were lost somewhere.

On a 125-column terminal, `man getopt` shows this:
```
SYNOPSIS
       getopt optstring parameters getopt [options] [--] optstring parameters getopt [options] -o|--options optstring
       [options] [--] parameters
```
And a screenshot:
![getoptman](https://user-images.githubusercontent.com/1262272/224466593-78a289eb-7d1c-4bf8-8e7a-9b552b090ec4.png)

util-linux 2.37.2 

Ubuntu 22.04.2 LTS

**Comment by karelzak** [comment]
Update to version >= 2.38, already fixed by commit 55bcc40952001c189f1aec865d30ad3f9536fe81.
