### ISSUE TITLE
How to compile fsck.ext4

### ISSUE THREAD

**Issue by MoonLight-SteinsGate** [util-linux/util-linux#2112]
Hi, I want to analyse the latest binary of fsck.ext4. But after compiling util-linux, I only found fsck, without fsck.ext4. How can I compile util-linux to get it?

**Comment by MoonLight-SteinsGate** [comment]
My compile configuration is:
```
./configure LDFLAGS=-static --without-python --without-tinfo --without-ncursesw --without-ncurses
```
Thanks a lot. I'm looking forward to the reply:)

**Comment by t-8ch** [comment]
fsck.ext4 is part of e2fsprogs:

https://github.com/tytso/e2fsprogs/blob/master/e2fsck/e2fsck.c

**Comment by karelzak** [comment]
Yes, see e2fsprogs. util-linux provides a generic fsck wrapper only.
