### ISSUE TITLE
nsenter --setuid and --setgid now require =

### ISSUE THREAD

**Issue by anitazha** [util-linux/util-linux#2143]
https://github.com/util-linux/util-linux/commit/597ae346491f142ff3bf00f07110f8de22121fd7 changed the format of arguments for `--setuid` and `--setgid` so that you have to pass `=` when supplying an argument. This broke one of our scripts which was using the previous format where space separation was allowed. Is this expected? What are the compatibility guarantees for stuff like this?

**Comment by karelzak** [comment]
@t-8ch maybe it would be better to introduce new options --follow-uid and --follow-gid to read the default from the target rather than modify existing --setuid and --setgid. 

What do you mean? (We already have --follow-context for Selinux).

**Comment by t-8ch** [comment]
@karelzak I would prefer `--setuid follow`.

**Comment by karelzak** [comment]
So, the argument will not be optional, but a "number" or "follow", OK.
