### ISSUE TITLE
false error from findmnt for ntfs3 in fstab 

### ISSUE THREAD

**Issue by gabmert** [util-linux/util-linux#2148]
Kernel Version: 6.2.8-1-MANJARO (64-bit)

I have this line in my `/etc/fstab`:
```
UUID=0123456789example                     /mnt/docdrive  ntfs3   rw,nosuid,nodev,relatime,prealloc,uid=1000,gid=1000,iocharset=utf8,windows_names,hide_dot_files,sys_immutable 0 2
```
options are taken from udisk2 and [Kernel-Doc](https://docs.kernel.org/filesystems/ntfs3.html).

This results in a fine boot, cf `mount`: `/dev/sda5 on /mnt/docdrive type ntfs3 (rw,nosuid,nodev,relatime,uid=1000,gid=1000,iocharset=utf8,sys_immutable,windows_names,hide_dot_files,prealloc`

But running `sudo findmnt --verify --verbose` results in:
```
/mnt/docdrive
   [ ] target exists
   [ ] VFS options: rw,nosuid,nodev,relatime
   [ ] FS options: prealloc,uid=1000,gid=1000,iocharset=utf8,windows_names,hide_dot_files,sys_immutable
   [ ] UUID=0123456789example translated to /dev/sda5
   [ ] source /dev/sda5 exists
   [E] ntfs3 does not match with on-disk ntfs

0 parse errors, 1 error, 0 warnings
```

So far I think this is an false error as `findmnt` isn't aware that the filesystem signature and the driver can be different, see [udisk2](https://github.com/storaged-project/udisks/issues/932). 
I am not sure where to post this, maybe it's part of #1508. I don't know about it's severity (likely low), but still I hope someone will care. Thank you for all your good work!

**Comment by karelzak** [comment]
It's probably overkilled to use "error" in this case. The situation with the filesystem name and on-disk stuff could be complicated. It seems better to use a warning in this case.
