### ISSUE TITLE
It doesn't look like flock can lock by a file descriptor

### ISSUE THREAD

**Issue by x-yuri** [util-linux/util-linux#2162]
In the [docs][a] I can see:

> shell> exec 4<>/var/lock/mylockfile; shell> flock -n 4
> 
> This form is convenient for locking a file without spawning a subprocess. The shell opens the lock file for reading and writing as file descriptor 4, then flock is used to lock the descriptor.

But it doesn't look like it can lock by a file descriptor:

```
$ exec 4<>a
$ ls
a
$ flock 4 echo done
done
$ ls
4  a
```

It appeared supposedly in the following [commit][b] ([flock.1][c]). And there's no indication that that was handled even [back then][d]. Which is strange.

[a]: https://github.com/util-linux/util-linux/blob/v2.38.1/sys-utils/flock.1.adoc
[b]: https://github.com/util-linux/util-linux/commit/baf39af15b1fe8570e6430788ec7cd4959fbc5d9
[c]: https://github.com/util-linux/util-linux/blob/baf39af15b1fe8570e6430788ec7cd4959fbc5d9/sys-utils/flock.1
[d]: https://github.com/util-linux/util-linux/blob/baf39af15b1fe8570e6430788ec7cd4959fbc5d9/sys-utils/flock.c#L205

**Comment by t-8ch** [comment]
You can't specify a command when specifying a fd number.

```
exec 4<>a
$ flock 4
```

And that then holds the lock while this shell is running (or the fd is closed), instead of while the command is running.

**Comment by x-yuri** [comment]
I see, [my bad][a].

[a]: https://github.com/util-linux/util-linux/blob/baf39af15b1fe8570e6430788ec7cd4959fbc5d9/sys-utils/flock.c#L217-L223
