### ISSUE TITLE
sulogin: display illegal character when LANG=zh_CN.UTF-8

### ISSUE THREAD

**Issue by zhangyao108** [util-linux/util-linux#2185]
Running sulogin 2.37.2 with the following script:
```
localectl set-locale LANG=zh_CN.UTF-8
sulogin
```
The output is:
```
?? root ?????
(?? Control-D ???):
```

**Comment by karelzak** [comment]
I guess we need something like:
```diff
diff --git a/login-utils/sulogin.c b/login-utils/sulogin.c
index e19a3b8b6..8ed589c56 100644
--- a/login-utils/sulogin.c
+++ b/login-utils/sulogin.c
@@ -250,6 +250,9 @@ static void tcinit(struct console *con)
                setlocale(LC_CTYPE, "POSIX");
                break;
        }
+
+       if (tio->c_iflag & IUTF8)
+               flags |= UL_TTY_UTF8;
 #else
        setlocale(LC_CTYPE, "POSIX");
 #endif
```
because otherwise `reset_virtual_console(tio, flags);` removes IUTF8 from the console setting.. But I have no time to test it now.

**Comment by zhangyao108** [comment]
Applying this patch doesn't to work, bucause the code jumps directly to `setattr`
https://github.com/util-linux/util-linux/blob/master/login-utils/sulogin.c#L237

**Comment by karelzak** [comment]
@marcosfrm Good catch. Thanks for the review. 

The bug was probably introduced when code has been copied from agetty, where it's ifdef-else, but KDGKBMODE is always called there.

**Comment by zhangyao108** [comment]
ioctl_console - ioctls for console terminal and virtual consoles
connected by SSH, it's a pseudo terminal, call ioctl(fd, KDGKBMODE, &mode) always failed.
so always run to this 
https://github.com/util-linux/util-linux/blob/10d477ac7849eee1ce6ac82b73d6f02ff6db701c/login-utils/sulogin.c#L142-L144
https://github.com/util-linux/util-linux/blob/10d477ac7849eee1ce6ac82b73d6f02ff6db701c/login-utils/sulogin.c#L149-L151
https://github.com/util-linux/util-linux/blob/10d477ac7849eee1ce6ac82b73d6f02ff6db701c/login-utils/sulogin.c#L237

**Comment by marcosfrm** [comment]
Yes, for PTYs it will not work. It should not assume serial line at least. This `is_pty()` from glibc can be useful:

https://github.com/bminor/glibc/blob/d1417176a35d27ffb8da0ffb1e33154163b6eeb2/sysdeps/unix/sysv/linux/ttyname.h#L24-L32

What is the use case for running `sulogin` in a SSH session?

**Comment by karelzak** [comment]
Well, sulogin is used when initd can't boot the system to ask for the root's password. And it gathers and opens consoles from the /dev, /sys, or kernel command line. There is really nothing like SSH in sulogin world ... (the same for agetty).

**Comment by zhangyao108** [comment]
> ok,thanks!
I have a new query: 
my locale set is LC_CTYPE="zh_CN.UTF-8", but call setlocale(LC_CTYPE, "C.UTF-8"); still display ?, if setlocale(LC_CTYPE, "POSIX.UTF-8");  display normal, why?

**Comment by karelzak** [comment]
Note that in some cases, sulogin can set LC_CTYPE="POSIX" while retaining the original LC_MESSAGES. In this scenario, the gettext() function may not work as intended. GNU gettext FAQ:

> This symptom occurs when the LC_CTYPE facet of the locale is not set; then gettext() doesn't know which character set to use, and converts all messages to ASCII, as far as possible.

This is why, in some cases, we see "???" in the sulogin output. I will fix it, as we need to set LC_MESSAGES to be the same as LC_CTYPE.
