### ISSUE TITLE
Bug: end of function can be reached with no return statement

### ISSUE THREAD

**Issue by Stefan-Radu** [util-linux/util-linux#2190]
In `login-utils/su-common.c` in `supam_conv`:

```c
	if (su->suppress_pam_info
	    && num_msg == 1
	    && msg && msg[0]->msg_style == PAM_TEXT_INFO)
		return PAM_SUCCESS;

#ifdef HAVE_SECURITY_PAM_MISC_H
	return misc_conv(num_msg, msg, resp, data);
#elif defined(HAVE_SECURITY_OPENPAM_H)
	return openpam_ttyconv(num_msg, msg, resp, data);
#endif
}
```

If neither the if condition nor the pre-processor directive checks hold, the function will exit without returning.

**Comment by Stefan-Radu** [comment]
I would fix this myself, but I'm not sure what should be the proper return code here.

**Comment by karelzak** [comment]
> I would fix this myself, but I'm not sure what should be the proper return code here.

Right now, I'm watching the code and asking the same :-) PAM_CONV_ERR probably according to `man pam_conv`.

**Comment by karelzak** [comment]
If you want to send a patch/PR than see also `git grep misc_conv` ;-)

**Comment by Stefan-Radu** [comment]
> If you want to send a patch/PR than see also git grep misc_conv ;-)

Okay, I will look into it and come back with a PR :)

**Comment by karelzak** [comment]
Fixed.
