### ISSUE TITLE
dmesg output sometimes truncated with a pager

### ISSUE THREAD

**Issue by arachsys** [util-linux/util-linux#2218]
I noticed that `dmesg` output from the HEAD of util-linux.git (built with clang 16.0.3 against musl 1.2.4) was sometimes truncated when the automatic pager support is used, e.g. with `dmesg -H`. When the kmsg ring buffer is in a state that triggers this bug, it is completely reproducible across multiple invocations of `dmesg`, but doesn't happen with a binary built from v2.38.1 nor with `dmesg | less` (for example).

I reproduced the problem with a script that does `head -n 1; sleep 1; cat` as PAGER to eliminate any strange behaviour from the pager from the mix, then bisected to commit 518a0ad4. This drops fflush(stdout) and fflush(stderr) from wait_for_pager() immediately before STDOUT_FILENO and STDERR_FILENO are closed.

Looks to me as if the patch is right in the sense that fflush() isn't async-signal-safe, but wrong in the sense that it closes the file descriptor without ensuring the output is flushed.

Given how close to release we are, I wonder if dropping stdout and stderr down to line-buffered in __setup_pager() might be a safer fix than restructuring pager.c so the flush and close can happen properly outside the signal handler? E.g. something like this:

```diff
diff --git a/lib/pager.c b/lib/pager.c
index 8f62310c0..1a87feb99 100644
--- a/lib/pager.c
+++ b/lib/pager.c
@@ -239,8 +239,11 @@ static void __setup_pager(void)

        /* original process continues, but writes to the pipe */
        dup2(pager_process.in, STDOUT_FILENO);
-       if (isatty(STDERR_FILENO))
+       setvbuf(stdout, NULL, _IOLBF, 0);
+       if (isatty(STDERR_FILENO)) {
                dup2(pager_process.in, STDERR_FILENO);
+               setvbuf(stderr, NULL, _IOLBF, 0);
+       }
        close(pager_process.in);

        memset(&sa, 0, sizeof(sa));
```

which I can confirm does actually fix the bug.

**Comment by karelzak** [comment]
@arachsys please, create a pull-request from your patch. 

(Although GitHub is useless today.)

**Comment by arachsys** [comment]
Will do, just wanted to check you were happy with that bodge before sending. 👍
