### ISSUE TITLE
Output of `hexdump --one-byte-char --canonical` is misaligned

### ISSUE THREAD

**Issue by tpwo** [util-linux/util-linux#2223]
Hello, I didn't find a duplicate of the reported problem in other issues what
surprised me a bit, as for me it seems to be one of the most natural `hexdump`
use cases.

I noticed that behavior of `hexdump` with flags `-cC` is a bit inconsistent, as
the output is misaligned, what can be demonstrated with a simple example:

```shell
$ hexdump --one-byte-char --canonical <<< 'Hi, hello world'
0000000   H   i   ,       h   e   l   l   o       w   o   r   l   d  \n
00000000  48 69 2c 20 68 65 6c 6c  6f 20 77 6f 72 6c 64 0a  |Hi, hello world.|
00000010
```

As you can see, ASCII characters are misaligned with two-byte representation of
them. I'd expect it to work like that, so it's much easier to tell which
corresponds to which:

```shell
$ ./hexdump --one-byte-char --canonical <<< 'Hi, hello world'
0000000   H   i   ,       h   e   l   l   o       w   o   r   l   d  \n
0000000  48  69  2c  20  68  65  6c  6c  6f  20  77  6f  72  6c  64  0a  |Hi, hello world.|
0000010
```

This output was generated by hexdump with this small patch applied in
[hexdump.c](https://github.com/util-linux/util-linux/blob/7d376eb903aa507259698e1ae2ea0e6932e4807e/text-utils/hexdump.c#LL95C1-L95C1):

```patch
diff --git a/text-utils/hexdump.c b/text-utils/hexdump.c
index 73b3a94a0..a5e6079ed 100644
--- a/text-utils/hexdump.c
+++ b/text-utils/hexdump.c
@@ -93,8 +93,8 @@ parse_args(int argc, char **argv, struct hexdump *hex)
                        add_fmt("\"%07.7_ax \" 16/1 \"%3_c \" \"\\n\"", hex);
                        break;
                case 'C':
-                       add_fmt("\"%08.8_Ax\n\"", hex);
-                       add_fmt("\"%08.8_ax  \" 8/1 \"%02x \" \"  \" 8/1 \"%02x \" ", hex);
+                       add_fmt("\"%07.7_Ax\n\"", hex);
+                       add_fmt("\"%07.7_ax \" 16/1 \" %02x \" ", hex);
                        add_fmt("\"  |\" 16/1 \"%_p\" \"|\\n\"", hex);
                        break;
                case 'd':
```

But the manpage explanation of `--canonical` flag sounds a bit scary for me to
treat this patch as the ultimate solution:

> Canonical hex+ASCII display. Display the input offset in hexadecimal,
> followed by sixteen space-separated, two-column, hexadecimal bytes, followed
> by the same sixteen bytes in %_p format enclosed in '|' characters. Invoking
> the program as hd implies this option.

Because of that, I wonder if there's a way to fix this problem by doing
something different from breaking change (by which I mean modifying the
behavior of "canonical" flag). For example, adding a new "canonical-inspired"
flag, which will be useful when combined with `--one-byte-char`.

I hope that this is the correct place to post this issue (I guess that the
alternative is `util-linux` mailing list).

Best regards,
Tomasz

**Comment by karelzak** [comment]
Yes, this is the correct place.

For backward compatibility it will be better to not touch any existing output format. And I don't think that the hardcoded formats have to be compatible with each other (for example --one-byte-char with --canonical).

Fortunatelly we have `-e, --format` command line option that you can use to define your custom format :-)

**Comment by tpwo** [comment]
I totally missed `-e, --format` option, thanks for that!

I noticed that `--canonical` is the only hard-coded format not aligned
with `--one-byte-char`, and that's why I didn't know if that was
intended:

```shell
$ hexdump \
  --one-byte-char \
  --cannonical \
  --one-byte-octal \
  --two-bytes-decimal \
  --two-bytes-octal \
  --two-bytes-hex \
  <<< 'Hi, hello world'
0000000   H   i   ,       h   e   l   l   o       w   o   r   l   d  \n
00000000  48 69 2c 20 68 65 6c 6c  6f 20 77 6f 72 6c 64 0a  |Hi, hello world.|
0000000 110 151 054 040 150 145 154 154 157 040 167 157 162 154 144 012
0000000   26952   08236   25960   27756   08303   28535   27762   02660
0000000  064510  020054  062550  066154  020157  067567  066162  005144
0000000    6948    202c    6568    6c6c    206f    6f77    6c72    0a64
0000010
```

But `-e` solves this issue for me :) I created a Bash function with "my
version" of `--canonical` if anyone reading would be interested in
something similar:

```bash
,hd() {
  hexdump \
    --one-byte-char \
    --format "\"%07.7_Ax\n\"" \
    --format "\"%07.7_ax \" 16/1 \" %02x \" " \
    --format "\"  |\" 16/1 \"%_p\" \"|\\n\"" \
    "$@"
} && export -f ,hd
```

I guess that we can close the issue? Or, do you think that adding a new
hardcoded format (e.g. `--one-byte-hex` without the ASCII part) would be worth the effort here?

**Comment by karelzak** [comment]
I like the idea of having both in the output -- classic hex (2 columns of 8 bytes) and human-readable bytes aligned to the hex. 

Send patch ;-)

**Comment by tpwo** [comment]
Ok, sure! I'll create a draft PR :D

**Comment by karelzak** [comment]
Implemented. Closing.
