### ISSUE TITLE
PGP key expired

### ISSUE THREAD

**Issue by thesamesam** [util-linux/util-linux#2234]
Would it be possible for the key at https://kzak.redcrew.org/ to be updated? I think the copy there is expired. I _think_ the copy on keyserver.ubuntu.com is expired too but I might have made a mistake.

Thank you!

**Comment by karelzak** [comment]
I updated the key yesterday, but it's not fully distributed on servers yet. Now, I have done some other server updates, including the Ubuntu and Debian servers.

Thanks for the hint about my Wiki page. I forgot the key is there ;-)

**Comment by thesamesam** [comment]
Thank you!
