### ISSUE TITLE
mount: noexec,nodev,nosuid automatically enabled 

### ISSUE THREAD

**Issue by hdejin** [util-linux/util-linux#2238]
On 2.39, mount automatically enables noexec,nodev,nosuid when the 'user' option is present in fstab.
even when 'exec' is explicitly requested for, it still gets mounted 'noexec'.

eg. in /etc/fstab
/dev/sdb1   /mnt  ext4    noauto,noatime,nodiratime,exec,user,errors=remount-ro     0  0

after mounted by user
/dev/sdb1 on /mnt type ext4 (rw,nosuid,nodev,noexec,noatime,nodiratime,errors=remount-ro,user=johndoe)

**Comment by douzzer** [comment]
Additional detail, from [https://bugs.gentoo.org/906797#c4](https://bugs.gentoo.org/906797#c4):

> Note also, with 2.39, fstab mount options `user,exec` is newly broken, failing incorrectly with "must be superuser to use mount.".  `users,exec` still works, but is not semantically identical (`user` confines permission-to-unmount to the mounting user, whereas `users` allows any user with parent directory read access to unmount it, even if no access to the rootdir of the mount, confirmed experimentally with 2.39).
> 
> The code around option evaluation was extensively reworked between 2.38 and 2.39, and this shows what's breaking in 2.39 with `user,exec`:
> ```
> 45519: libmount:  OPTLIST: merging
> L 328 outer: exec (0x5625c3ac82d0)
> L 334 inner: exec (0x5625c3ac7f50)
> L 342 remove duplicate exec
> 45519: libmount:  OPTLIST:  remove exec
> L 334 inner: noauto (0x5625c3ac7fb0)
> L 334 inner: user (0x5625c3ac8010)
> L 352 remove due to MNT_INVERT exec
> 45519: libmount:  OPTLIST:  remove user
> ```
> i.e. the `exec` flag is clearing the `user` flag.  With `exec,users` this doesn't happen.  And that's as far as I went root-causing this mess.

**Comment by karelzak** [comment]
Your fstab has to use "exec" after "user"; it means `noauto,noatime,nodiratime,user,exec,errors=remount-ro`. This is required by the old versions too. The evaluation rule is "the latest option wins".

Anyway, unfortunately, you're right, and there is also a bug in the v2.39. It incorrectly reorders the options when it reads options from fstab.

The problem will be fixed in v2.39.1.
