### ISSUE TITLE
Message recipient disconnected from message bus without replying

### ISSUE THREAD

**Issue by EmJotGeh** [util-linux/util-linux#2267]
Since the last update to version 2.39, I can no longer mount an external hard drive on my Arch Linux system via Dolphin as usual. 

A manual mounting of the hard disk was however possible.

The following error message appears: 
Message recipient disconnected from message bus without replying

A downgrade of util-linux and util-linux-libs to version 2.38.4 fixed the error for the time being.

Please have a look at the discussion in the Arch Linux Forum.

https://forum.archlinux.de/d/34860-message-recipient-disconnected-from-message-bus-without-replying

or 

https://bbs.archlinux.org/viewtopic.php?id=285996

**Comment by t-8ch** [comment]
It seems udisks segfaults. I can't reproduce this.

```
udisksd[8458]: udisksd: libmount/src/hook_mount.c:480: hook_attach_target: Assertionapi->fd_tree >= 0' failed.
```

**Comment by Balbao** [comment]
I have the same problem, but with Nemo. 
A downgrade of util-linux and util-linux-libs to version 2.38.4 fixed the error for the time being.

**Comment by t-8ch** [comment]
The failing log:

[udisks-mount.log](https://github.com/util-linux/util-linux/files/11557167/udisks-mount.log)

I guess if fsopen() fails with `ENODEV` but the helper is used successfully then its fine to have no `fd_tree`.

**Comment by t-8ch** [comment]
FYI udisks does not explicitly call `mnt_init_debug()`, so it's not possible to use `LIBMOUNT_DEBUG`. I think it needs some logic similar to libblkid to automatically initialize debugging.

**Comment by karelzak** [comment]
Sounds like https://bugzilla.redhat.com/show_bug.cgi?id=2189241 we have tried to debug last week with udisk maintainer.

https://github.com/storaged-project/libblockdev/pull/889 is plan to add LIBMOUNT_DEBUG= to udisks.

**Comment by karelzak** [comment]
CC @tbzatek

**Comment by t-8ch** [comment]
In #2269  is a simple reproducer without any dependency on udisks

**Comment by karelzak** [comment]
> mount -t ntfs3,ntfs /dev/sda1 /mnt/

Cook, I can finally reproduce it too :-)

**Comment by karelzak** [comment]
hook_attach_target() should not be executed if we use an external helper.

**Comment by karelzak** [comment]
We will need v2.39.1 ASAP -- probably next week. 

I'll backport the bugfix https://github.com/util-linux/util-linux/commit/f94a7760ed7ce81389a6059f020238981627a70d to Fedora.

**Comment by tbzatek** [comment]
Oh nice, I haven't been successful in reproducing this. I think I haven't tested the scenario where all supplied filesystem types are failed or were unavailable.

**Comment by EmJotGeh** [comment]
Version 2.39.3 solve the problem! Thank you to all devs :-) - Topic can be closed.

**Comment by rept0id** [comment]
Downgrading didnt fixed the bug for me

**Comment by rept0id** [comment]
Working from Kali Rolling, any details I could provide count me in

**Comment by jeddNjug** [comment]
> sudo apt-get install dosfstools mtools sudo apt-get install udisks2 udev
> 
> those lines did the trick for me, 99% the last one, seems like udisks2 (mostly) / udev are facing an issue at the same time

Thanks big

**Comment by cdrchops** [comment]
This issue is closed but I wanted to comment that the two lines worked for me as well
