### ISSUE TITLE
util-linux 2.39 seems to break old kernels like 5.10 and 5.4

### ISSUE THREAD

**Issue by qiujiangkun** [util-linux/util-linux#2270]
I upgraded to util-linux 2.39 on Manjaro, and found old kernels fail to boot. My root filesystem is btrfs.

![image](https://github.com/util-linux/util-linux/assets/33482468/e1003a31-3c61-4a40-b6ab-994add984ca6)

Similar case:
https://www.spinics.net/lists/util-linux-ng/msg17389.html

**Comment by karelzak** [comment]
The issue should be already fixed by https://github.com/util-linux/util-linux/pull/2248

**Comment by qiujiangkun** [comment]
Cool, can't wait for the release. I have to use old kernel because my 8814au can't compile for new kernels

https://github.com/morrownr/8814au/issues/109

**Comment by nsapse** [comment]
For us noobs, how would be go about upgrading to the fixed version from the emergency shell?

**Comment by bsdice** [comment]
mount: /boot: mount(2) system call failed: Function not implemented.

I just upgraded Arch and got a minor heart-attack. ;-) I also run 5.4. It seems advisable to:

1. Always keep a bootable USB-drive around. I installed Arch on it, which I rarely update. So I can boot a machine and arch-chroot into the root filesystem to roll back seriously broken packages.
2. Have more than one kernel installed, like latest "mainline", then "lts" and maybe even a very old kernel from AUR. Saved me here.

Pinging @eworm-de please update util-linux.

**Comment by eworm-de** [comment]
Should be fixed in `util-linux 2.39-4`.

**Comment by karelzak** [comment]
Closing.

**Comment by qiujiangkun** [comment]
![image](https://github.com/util-linux/util-linux/assets/33482468/3decd508-a8b6-4bb9-b2d2-df5d5eff29ff)
Now it's a different error on 5.4

trying a slightly newer version

**Comment by bsdice** [comment]
Try initramfs with compression XZ or gzip. You probably have a kernel without zstd support.
