### ISSUE TITLE
dmesg -r output is incorrect because syslog.h LOG_MAKEPRI macro requires facility left shifted by 3 bits

### ISSUE THREAD

**Issue by egchron** [util-linux/util-linux#2325]
Here is a git patch with a header that describes the problem and testing to show the bug and verify the proposed fix that we're currently using. The actual code change is trivial: 1 line added to two lines changed to use the one line macro added.

For your consideration.

Thank-you,
Edward Chron <echron@yahoo.com>
------------------------------------------------------------------------------------------------------------------------------------------------

From: Edward Chron <echron@arista.com>
Date: Mon, 19 Jun 2023 07:34:03 -0700
Subject: [PATCH] util-linux/sys-utils dmesg -r LOG_MAKEPRI needs fac << 3

Submission to Project: util-linux
Component: util-linux/sys-utils
File: dmesg.c
Code level patch applied against: 2.39 - latest code pulled from
           git.github.com:util-linux/util-linux.git
BUG: The facility field passed to macro from /usr/include/sys/syslog.h
     LOG_MAKEPRI(fac, pri) by dmesg -r needs to have fac argument
     shifted 3 bit to the left to return a valid raw valid. The lower
     3 bits for a raw value are used by the loglevel priority (pri)
     field, so the facility bits can only occupy the bits above the
     bits used to hold the pri field value.

The dmesg -r command produces the incorrect output for the raw value
for the or'ed combination of the facility | loglevel priority that gets
produced by the LOG_MAKEPRI macro. That macro is defined as:

    #define LOG_MAKEPRI(fac, pri) ((fac) | (pri))

which is defined in the current glibc code in /usr/include/sys/syslog.h
and is used only in the dmesg -r (raw output option) command to form the
raw value for facility or'ed with loglevel priority and displayed as:

    <#>[#######.######] ...

where the # in <#> contains the output from the LOG_MAKEPRI macro.

The lower 3 bits are reserved for the loglevel priority 0-7
and the bits above that are for the facility value, so the facility
index should be shifted to the left three bits and or'ed with the
loglevel priority.

In the glibc file: /usr/include/sys/syslog.h the macro LOG_MAKEPRI is
defined as:

        #define LOG_MAKEPRI(fac, pri) ((fac) | (pri)

and returns the wrong facility and loglevel priority values, ideally it
should be defined as:

        #define LOG_MAKEPRI(fac, pri) ((fac) << 3 | (pri))

to return the correct raw value.

We checked with glibc developement and the LOG_MAKEPRI macro is correct
as is and can't be changed as it used by *BSD as is so the solution for
dmesg -r is to shift the facility index left by 3 bits as input to the
LOG_MAKEPRI macro. That is what glibc development recommended.
(For reference, see glibc bugzilla Bug 30563)

We can front end the LOG_MAKEPRI macro with a macro that shifts the
facility by the needed 3 bits which we've added to dmesg.c:

    #define LOG_RAW_FAC_PRI(fac, pri) LOG_MAKEPRI((fac << 3), (pri))

This has been tested and works correctly to produce the correct raw
mode value for Facility or'ed together with Loglevel priority.

You can verify that this fix works correctly.

Without any fix you can test dmesg -r by adding several records to
/dev/kmsg like this:

        echo "<14> Test Message Facility 8 Logevel 6" >> /dev/kmsg
        echo "<15> Test Message Facility 8 Logevel 7" >> /dev/kmsg
        echo "<30> Test Message Facility 24 Loglevel 6" >> /dev/kmsg

these commands add 3 records to the dmesg buffer. Then when we print the
records using the dmesg command with the raw option:

Here is what dmesg erronously produces:
--------------------------------------
    [echron@capistano syslog_raw]$ dmesg -r | grep "Test Message Facility"
    <7>[1879346.077678]  Test Message Facility 8 LogLevel 6
    <7>[1880050.125549]  Test Message Facility 8 LogLevel 7
    <7>[1881313.244898]  Test Message Facility 24 LogLevel 6

However, if we run the dmesg -r command using the new front end macro
LOG_RAW_FAC_PRI(fac, pri) we get the correct output:

Here is the corrected output:
----------------------------
    [echron@capistano syslog_raw]$ dmesg -r | grep "Test Message Facility"
    <14>[1879346.077678]  Test Message Facility 8 LogLevel 6
    <15>[1880050.125549]  Test Message Facility 8 LogLevel 7
    <30>[1881313.244898]  Test Message Facility 24 LogLevel 6

shifting the facility index value by 3 bits in the LOG_RAW_FAC_PRI macro
provides the correct ouput as shown.

Signed-off-by: Edward Chron <echron@arista.com>
---
 sys-utils/dmesg.c | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/sys-utils/dmesg.c b/sys-utils/dmesg.c
index 717cc588b..02358e449 100644
--- a/sys-utils/dmesg.c
+++ b/sys-utils/dmesg.c
@@ -125,6 +125,7 @@ static const struct dmesg_name level_names[] =
  * shifted code :-)
  */
 #define FAC_BASE(f)>---((f) >> 3)
+#define LOG_RAW_FAC_PRI(fac, pri)>-----LOG_MAKEPRI((fac << 3), (pri))
.
 static const struct dmesg_name facility_names[] =
 {
@@ -968,7 +969,7 @@ static void print_record(struct dmesg_control *ctl,
 >------if (ctl->raw) {
 >------>-------ctl->indent = snprintf(tsbuf, sizeof(tsbuf),
 >------>------->------->-------       "<%d>[%5ld.%06ld] ",
->------>------->------->-------       LOG_MAKEPRI(rec->facility, rec->level),
+>------>------->------->-------       LOG_RAW_FAC_PRI(rec->facility, rec->level),
 >------>------->------->-------       (long) rec->tv.tv_sec,
 >------>------->------->-------       (long) rec->tv.tv_usec);
 >------>-------goto full_output;
@@ -1052,7 +1053,7 @@ full_output:
 >------>------->-------ul_jsonwrt_value_s(&ctl->jfmt, "fac", facility_names[rec->facility].name);
 >------>------->-------ul_jsonwrt_value_s(&ctl->jfmt, "pri", level_names[rec->level].name);
 >------>-------} else
->------>------->-------ul_jsonwrt_value_u64(&ctl->jfmt, "pri", LOG_MAKEPRI(rec->facility, rec->level));
+>------>------->-------ul_jsonwrt_value_u64(&ctl->jfmt, "pri", LOG_RAW_FAC_PRI(rec->facility, rec->level));
 >------}
.
 >------/* Output the timestamp buffer */
--.
2.41.0

**Comment by egchron** [comment]
May be able to work around this issue without changing the code by using facility macros. Looking to that.

**Comment by egchron** [comment]
Yeah, I think we can just use the facility macros to do the shift that we were expecting to see instead of just using the facility index. The syslog.h has those macros. Thanks.

**Comment by egchron** [comment]
So I went back and tested because I was concerned our testing missed testing the Syslog (dmesg -S) interface and that there the facility macros may have been used which means the fix we applied would break he dmesg -S -r output. However, it doesn't. Our testing shows that dmesg -S -r is not broken by our proposed fix.

Here is the testing I am doing:

Testing of the dmesg program without our proposed fix (i.e. current dmesg code):

-bash-4.2# echo "<14> Test Message Facility 8 Loglevel 6" >> /dev/kmsg
-bash-4.2# echo "<15> Test Message Facility 8 Loglevel 7" >> /dev/kmsg
-bash-4.2# echo "<30> Test Message Facility 24 Loglevel 6" >> /dev/kmsg
-bash-4.2# echo "<31> Test Message Facility 24 Loglevel 7" >> /dev/kmsg

-bash-4.2# cat /dev/kmsg | grep "Test Message Facility"
14,1114,495317239,-; Test Message Facility 8 Loglevel 6
15,1115,503340779,-; Test Message Facility 8 Loglevel 7
30,1116,643374764,-; Test Message Facility 24 Loglevel 6
31,1117,657165117,-; Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -r | grep "Test Message Facility"
<7>[  495.317239]  Test Message Facility 8 Loglevel 6
<7>[  503.340779]  Test Message Facility 8 Loglevel 7
<7>[  643.374764]  Test Message Facility 24 Loglevel 6
<7>[  657.165117]  Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -S -r | grep "Test Message Facility"
<14>[  495.317239]  Test Message Facility 8 Loglevel 6
<15>[  503.340779]  Test Message Facility 8 Loglevel 7
<30>[  643.374764]  Test Message Facility 24 Loglevel 6
<31>[  657.165117]  Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -x | grep "Test Message Facility"
user  :info  : [  495.317239]  Test Message Facility 8 Loglevel 6
user  :debug : [  503.340779]  Test Message Facility 8 Loglevel 7
daemon:info  : [  643.374764]  Test Message Facility 24 Loglevel 6
daemon:debug : [  657.165117]  Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -S -x | grep "Test Message Facility"
user  :info  : [  495.317239]  Test Message Facility 8 Loglevel 6
user  :debug : [  503.340779]  Test Message Facility 8 Loglevel 7
daemon:info  : [  643.374764]  Test Message Facility 24 Loglevel 6
daemon:debug : [  657.165117]  Test Message Facility 24 Loglevel 7

So only dmesg -x using /dev/kmsg interface is broken with the current code.

Now testing the dmesg program with our proposed fix:

-bash-4.2# ls -lt /usr/bin/dmesg
-rwxr-xr-x 1 root root 70952 Jun 19 17:14 /usr/bin/dmesg

-bash-4.2# echo "<14> Test Message Facility 8 Loglevel 6" >> /dev/kmsg
-bash-4.2# echo "<15> Test Message Facility 8 Loglevel 7" >> /dev/kmsg
-bash-4.2# echo "<30> Test Message Facility 24 Loglevel 6" >> /dev/kmsg
-bash-4.2# echo "<31> Test Message Facility 24 Loglevel 7" >> /dev/kmsg

-bash-4.2# cat /dev/kmsg | grep "Test Message Facility"
14,1118,991344796,-; Test Message Facility 8 Loglevel 6
15,1119,999663015,-; Test Message Facility 8 Loglevel 7
30,1120,1014768712,-; Test Message Facility 24 Loglevel 6
31,1121,1023116875,-; Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -r | grep "Test Message Facility"
<14>[  991.344796]  Test Message Facility 8 Loglevel 6
<15>[  999.663015]  Test Message Facility 8 Loglevel 7
<30>[ 1014.768712]  Test Message Facility 24 Loglevel 6
<31>[ 1023.116875]  Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -S -r | grep "Test Message Facility"
<14>[  991.344796]  Test Message Facility 8 Loglevel 6
<15>[  999.663015]  Test Message Facility 8 Loglevel 7
<30>[ 1014.768712]  Test Message Facility 24 Loglevel 6
<31>[ 1023.116875]  Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -x | grep "Test Message Facility"
user  :info  : [  991.344796]  Test Message Facility 8 Loglevel 6
user  :debug : [  999.663015]  Test Message Facility 8 Loglevel 7
daemon:info  : [ 1014.768712]  Test Message Facility 24 Loglevel 6
daemon:debug : [ 1023.116875]  Test Message Facility 24 Loglevel 7

-bash-4.2# dmesg -S -x | grep "Test Message Facility"
user  :info  : [  991.344796]  Test Message Facility 8 Loglevel 6
user  :debug : [  999.663015]  Test Message Facility 8 Loglevel 7
daemon:info  : [ 1014.768712]  Test Message Facility 24 Loglevel 6
daemon:debug : [ 1023.116875]  Test Message Facility 24 Loglevel 7

So as far as I can tell the fix we proposed is needed and valid, unless there are some test cases I'm missing.

I don't waste anyone's time but I'll reopen this issue and you can determine if this is correct or I am missing something.

Thank you for your consideration,

Edward Chron <yahoo.com>

**Comment by egchron** [comment]
I sent the patch upstream to util-linux@vger.kernel.org for consideration.

**Comment by karelzak** [comment]
> I sent the patch upstream to [util-linux@vger.kernel.org](mailto:util-linux@vger.kernel.org) for consideration.

I do not see any email/patch. You can also create a pull-request here on GitHub.

**Comment by egchron** [comment]
I am having email server issues so I resent the patch as an attachment, hope that is acceptable. Sorry for any inconvenience.

**Comment by colona** [comment]
I think vger discards email with html body as sent from Gmail by default.
Hopefully the inline version sent on Ed's behalf at https://lore.kernel.org/util-linux/20230622192235.GA8252@visor/T/#u is acceptable.

Thanks Karel,

**Comment by egchron** [comment]
I finally got my git send-email working again so I also sent the patch, sorry for any redundancy.

Thanks Karel and Ivan.

**Comment by karelzak** [comment]
The patch from the mailing list applied; thanks!
