### ISSUE TITLE
configure Insists on Running 'pkg-config' for the 'tinfo' Package for Static Builds

### ISSUE THREAD

**Issue by gerickson** [util-linux/util-linux#2327]
In util-linux 2.32.1 and 2.39, `configure` insists on running `pkg-config` for the `tinfo` package (and presumably others) even when `TINFO_CFLAGS` and `TINFO_LIBS` are set and `--disable-static` is asserted.

This manifests itself on a CI cross-compile build system in which `tinfo` is not installed for the native host as:

```
...
checking for TINFO... yes
configure: error: pkg-config description of tinfo, needed for static build, is not available
...
```

The help content for `TINFO_CFLAGS` and `TINFO_LIBS` cites:

```
 TINFO_CFLAGS  C compiler flags for TINFO, overriding pkg-config
 TINFO_LIBS    linker flags for TINFO, overriding pkg-config
```

that both _should_ override `pkg-config`.

**Comment by gerickson** [comment]
One potential patch for this might be:

```diff
% diff -aruN util-linux-2.32.1/m4/ul.m4 util-linux-2.32.1.N/m4/ul.m4
--- a/m4/ul.m4	2018-06-21 02:58:10.359568448 -0700
+++ b/m4/ul.m4	2023-06-21 11:02:44.823969239 -0700
@@ -30,10 +30,12 @@
 dnl Calls pkg-config --static
 dnl
 AC_DEFUN([UL_PKG_STATIC], [
-  if AC_RUN_LOG([$PKG_CONFIG --exists --print-errors "$2"]); then
-    $1=`$PKG_CONFIG --libs --static "$2"`
-  else
-    AC_MSG_ERROR([pkg-config description of $2, needed for static build, is not available])
+  if test "$enable_static" != xno; then
+    if AC_RUN_LOG([$PKG_CONFIG --exists --print-errors "$2"]); then
+      $1=`$PKG_CONFIG --libs --static "$2"`
+    else
+      AC_MSG_ERROR([pkg-config description of $2, needed for static build, is not available])
+    fi
   fi
 ])
 
```

**Comment by gerickson** [comment]
The following works around, but does not resolve, the issue by passing `PKG_CONFIG_LIBDIR` to `configure` where the location of the cross-compiled ncurses/tinfo `pkg-config` files are (assuming _ncurses_ was configured with `--with-pkg-config-libdir=/usr/share/pkgconfig`):

```
    $(Verbose)cd $(BuildDirectory) && \
        $(CURDIR)/$(PackageSourceDir)/configure -C \
...
        PKG_CONFIG_LIBDIR="$(call GenerateResultPaths,$(NCursesResultsDir),usr/share/pkgconfig)" \
...
```

**Comment by karelzak** [comment]
Please, send a pull request.  I'll backport it to v2.39.1 too (hopefully next Monday).

**Comment by karelzak** [comment]
Fixed.
