### ISSUE TITLE
logger --id sends random UID/GID

### ISSUE THREAD

**Issue by xhienne** [util-linux/util-linux#2336]
When `logger` is called with the `--id` parameter, the credentials (`struct ucred` ) that are sent through the Unix socket are not fully initialized:
- the `.pid` member is set to the value of the `--id` parameter as expected
- the `.uid` and `.gid` members are not initialized and thus are set to a random value, depending on what is on the stack

You can easily observe this with `strace`:
```sh
# strace -e sendmsg logger --id=$$ logger on AMD64
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="<13>Jun 24 16:45:06 root[3136737"...,
iov_len=35}, {iov_base="logger on AMD64", iov_len=15}], msg_iovlen=2,
msg_control=[{cmsg_len=28, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS,
cmsg_data={pid=3136737, uid=0, gid=124}}], msg_controllen=32, msg_flags=0}, MSG_NOSIGNAL) = 50
                        ^^^^^^^^^^^^^^

# strace -e sendmsg logger --id=$$ logger on ARM7
sendmsg(3, {msg_name=NULL, msg_namelen=0, msg_iov=[{iov_base="<13>Jun 24 16:42:21 root[14558]:"...,
iov_len=33}, {iov_base="logger on ARM7", iov_len=14}], msg_iovlen=2,
msg_control=[{cmsg_len=24, cmsg_level=SOL_SOCKET, cmsg_type=SCM_CREDENTIALS,
cmsg_data={pid=14558, uid=3069810076, gid=1025}}], msg_controllen=24, msg_flags=0}, MSG_NOSIGNAL) = 47
                      ^^^^^^^^^^^^^^^^^^^^^^^^
```

In both examples above, we would expect `cmsg_data.uid == cmsg_data.gid == 0`. The second example (on a 32-bit ARM platform) shows that the UID may be set to any 32 bit number.

This may actually be a big issue in combination with `systemd-journald`, when `Storage=persistent` and `SplitMode=uid`, because `journald` then creates a new journal file for each new UID, and you may end up with gazillions of files in `/var/log/journal`. Add to this that:
- `journald` does some provisioning and each journal file is made of (non-sparse) chunks of 8M bytes and thus uses at least 8M of disk space
- those user journals may not be properly removed with respect to the `SystemMaxUse` limit (see [this bug report](https://cdn.f5.com/product/bugtracker/ID867253.html))

... and you might have a /var/log partition that is full in a matter of minutes/hours, depending on how frequently you use `logger --id`

PS: this bug may also be the cause of strange issues that only occur in certain specific conditions, like [Ubuntu bug 1991436](https://bugs.launchpad.net/ubuntu/+source/util-linux/+bug/1991436) ("invalid argument" error from logger command when passing messages via STDIN)

**Comment by xhienne** [comment]
This patch fixes this issue:
```diff
diff --git a/misc-utils/logger.c b/misc-utils/logger.c
index e2b0b41ab..8174d55e0 100644
--- a/misc-utils/logger.c
+++ b/misc-utils/logger.c
@@ -471,7 +471,7 @@ static void write_output(struct logger_ctl *ctl, const char *const msg)
                union {
                        struct cmsghdr cmh;
                        char   control[CMSG_SPACE(sizeof(struct ucred))];
-               } cbuf;
+               } cbuf = { .control = { 0 } };
 #endif
 
                /* 4) add extra \n to make sure message is terminated */
```

**Comment by t-8ch** [comment]
This always send uid/gid of `0`.

If it is actively used by journal, would it make sense to send the concrete uid/gid of the logger process instead?

**Comment by xhienne** [comment]
According to `logger`'s manual, the `--id=NNN` parameter is ignored if you do not have root permissions (indeed, a few lines below this patch, sending credentials is enclosed in a `if (... geteuid() == 0 ...)`).

Considering this, and that it would be a very bad idea to make `logger` SUID root, it's safe to assume that UID/GID are null.

**Comment by karelzak** [comment]
Yes, writing/sending uninitialized content is always a bad thing. Thanks for your report.
