### ISSUE TITLE
Create a `mkswapfile` utility

### ISSUE THREAD

**Issue by nl6720** [util-linux/util-linux#2359]
Btrfs has a [`btrfs filesystem mkswapfile`](https://man.archlinux.org/man/btrfs.5#SWAPFILE_SUPPORT) command that simplifies swap file creation by allocating the file, setting permissions, etc. It would be nice if there were a generic `mkswapfile` command that could be used on other file systems.

And also a command switch, that would return a usable `resume_offset` for hibernation purposes, like [`btrfs inspect-internal map-swapfile`](https://man.archlinux.org/man/btrfs.5#HIBERNATION) does.

**Comment by karelzak** [comment]
Now sure, if we need extra util for this purpose, maybe it would be enough to have `mkswap --file`.

**Comment by nl6720** [comment]
`mkswap --file` sounds good too.

**Comment by chestnykh** [comment]
@karelzak  Is this still needed or has it already been done?

**Comment by karelzak** [comment]
> @karelzak Is this still needed or has it already been done?

I don't work on this feature and probably will not have time for this in the next weeks.

**Comment by endrift** [comment]
Looking at the source of `mkswap`, it looks like it might already support normal files? Or at the very least, has some handling for non-block device files.

**Comment by karelzak** [comment]
Yes, it supports non-device files, but you have to create the file in the right way (without holes, etc.). I thought the request was to make it easy for end-users. 

At least we need to update the mkswap man page and --help output, because it is not obvious that mkswap is able to use regular files.

**Comment by nl6720** [comment]
> I thought the request was to make it easy for end-users.

Yes, that's the idea. `mkswap` works on an existing file, but this request is for the ability to create the file and set correct permissions, etc.

**Comment by karelzak** [comment]
We can close this one (as the mkswap --file implements the requested feature).

**Comment by nl6720** [comment]
> And also a command switch, that would return a usable `resume_offset` for hibernation purposes, like [`btrfs inspect-internal map-swapfile`](https://man.archlinux.org/man/btrfs.5#HIBERNATION) does.

I opened a separate feature request for this: https://github.com/util-linux/util-linux/issues/2724
