### ISSUE TITLE
lsblk no longer considers devices with transport type mmc as hotplug

### ISSUE THREAD

**Issue by profi200** [util-linux/util-linux#2379]
Not sure when this appeared but currently running util-linux 2.39.1-1 and a SD card plugged in via the PCIe reader no longer is considered hotplug. I'm pretty sure it was hotplug before and i have a tool that relies on lsblk output which is now broken with native card readers.

Linux 6.1.38-1.

Hardware:
> 08:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS5227 PCI Express Card Reader (rev 01)

Current behavior:
> lsblk -dnr -oTYPE,HOTPLUG,TRAN,PHY-SEC /dev/mmcblk0
> disk 0 mmc 512

Expected behavior is to output 1 for the hotplug field.

**Comment by t-8ch** [comment]
Caused by  #2011 .

Previously all mmc disk where reported as hotpluggable.
This was incorrect for soldered eMMC cards.
Instead the kernel should report a proper per-disk value.

I'll see if I can find an sd card to reproduce.

**Comment by profi200** [comment]
Did you reproduce this yet? Unfortunately many PCs don't have these PCIe readers. Would not surprise me if yours doesn't.

**Comment by t-8ch** [comment]
@profi200
I have a

```
# lspci
02:00.0 Unassigned class [ff00]: Realtek Semiconductor Co., Ltd. RTS522A PCI Express Card Reader (rev 01)
```

That should be the correct thing. The problem is more to get the actual card to plug into it.
I should get one this week though.

**Comment by t-8ch** [comment]
util-linux was changed to properly use the kernels notion of hotplugging instead of using heuristics.
It turns out the kernel das not report hotpluggability for mmc devices.

There is now a patch for that:
https://lore.kernel.org/lkml/20230725-mmc-removable-v1-1-b2e0c4f18e6d@weissschuh.net/

Maybe you can test it.

**Comment by profi200** [comment]
Hmm, i don't have a setup for compiling Linux right now and no other device with PCIe reader i could test this on. So not sure how to test this at the moment.

**Comment by t-8ch** [comment]
No problem.

**Comment by profi200** [comment]
This issue seems to be solved now for me:

Linux 6.6.10-1.

> $ lsblk --version
> lsblk von util-linux 2.39.3
> $ lsblk -dnr -oTYPE,HOTPLUG,TRAN,PHY-SEC /dev/mmcblk0
> disk 1 mmc 512
