### ISSUE TITLE
column - hidden table column names still used in column size calculation

### ISSUE THREAD

**Issue by reefland** [util-linux/util-linux#2380]
Hidden table column names are still being used to calculate the width of a column.  If the column names are hidden I do not think it should be part of the calculation, it should only consider the data being displayed.

As an  exaggerated example, I added "XXs" to make some of the column names long:
```
 printf '%b' "$out" | column -t -s$',' -d --table-columns DEVICE,TEMP1XXXXXX,STATUS,DEVICE,TEMP2XXXXXX,STATUS --table-right TEMP1XXXXXX,TEMP2XXXXXX 
```

Then the output of the columns reflects the size of the hidden column names:
```
disk status:
  HP_SSD_EX950_512GB_0716 (nvme0n1):           91F  passed [97%]   WDC_WD120EFBX-68B0EN0_U62B (sda):            95F  without error  
  WDC_WD80EFAX-68KNBN0_0Y5G (sdb):            102F  without error  WDC_WD80EFZZ-68BTXN0_40NK (sdc):             95F  without error  
  WDC_WD80EFZZ-68BTXN0_9YVK (sdd):             93F  without error  Samsung_SSD_860_EVO_1TB_249Y (sde):         105F  passed [87%]   
  Samsung_SSD_860_EVO_1TB_043Z (sdf):         102F  passed [87%]                                                                    
```

It should only consider the size of the data (at most 4 characters in this example) when the column names are hidden.

---

My real world issue, is that while you can have two columns named `TEMP`, I could not find a way to make both of them right justified (neither `--table-right TEMP` nor `--table-right TEMP,TEMP ` worked) .  It would only right justify the 1st instance of the column name.  So I had to name them `TEMP1` and `TEMP2` and because that was ugly, I hid the column names.

But now the temperature columns are too wide.  To get the proper column width and right justified, had to use `TMP1` and `TMP2` which is even uglier workaround.  But it works:
```
disk status:
  HP_SSD_EX950_512GB_0716 (nvme0n1):    91F  passed [97%]   WDC_WD120EFBX-68B0EN0_U62B (sda):     95F  without error  
  WDC_WD80EFAX-68KNBN0_0Y5G (sdb):     102F  without error  WDC_WD80EFZZ-68BTXN0_40NK (sdc):      95F  without error  
  WDC_WD80EFZZ-68BTXN0_9YVK (sdd):      93F  without error  Samsung_SSD_860_EVO_1TB_249Y (sde):  105F  passed [87%]   
  Samsung_SSD_860_EVO_1TB_043Z (sdf):  102F  passed [87%]                                                             
```

---

Ubuntu 22.04.2:
```
$ column --v
column from util-linux 2.37.2
```

**Comment by reefland** [comment]
Also reproduced issue with newer version on Arch:
```
$ column --v
column from util-linux 2.39.1
```

**Comment by mator** [comment]
@t-8ch , sorry for posting in a closed issue, but 58a8c9284d625347db86970af90a88f5d6c9f7cd does not include fix for tests/expected/fincore/count.65536 (need to strip leading whitespace characters), but only for tests/expected/fincore/count.4096

**Comment by t-8ch** [comment]
Ah, indeed I missed it.
Could you send a patch for it? You seem to have the hardware to test it properly.

**Comment by karelzak** [comment]
> @t-8ch , sorry for posting in a closed issue,

@mator btw, we have https://github.com/util-linux/util-linux/discussions where is possible to discuss. We should use it more often :-)
