### ISSUE TITLE
systemd new udev rules break losetup

### ISSUE THREAD

**Issue by montag451** [util-linux/util-linux#2385]
As asked by @karelzak in https://github.com/systemd/systemd/issues/28475, I open an issue to signal that the changes introduced by https://github.com/systemd/systemd/commit/5ac52d1f7b7cd11cad8b5c2e9812d7ee7560a517 breaks losetup. The `systemd` maintainers have reverted the commit for the moment to let `losetup` maintainers find a solution (see https://github.com/systemd/systemd/pull/28476 and https://github.com/systemd/systemd/pull/28478).

**Comment by bluca** [comment]
The new links directory has been renamed in a way that does not clash with losetup, so this can be closed now
