### ISSUE TITLE
2.39 breaks "user" option when used "exec" also given.

### ISSUE THREAD

**Issue by neilbrown** [util-linux/util-linux#2392]
If I have mount options "user,exec" then I cannot mount the filesystem as a non-root user.
If I instead have "exec,user", then I can.

In the failing case mnt_optlist_merge_opts() notices that both of these options have  ent->id of 8 and that for "exec" MNT_INVERT is set. So it removes the second of these two keeping only the first.

Both MNT_MS_USER and MS_NOEXEC are 8, and somehow these collide.

**Comment by t-8ch** [comment]
Both options are in different option maps.
I guess this should have been fixed with c0267687fd7b41b00d523d1985182d7eb574effd which unfortunately didn't make it into 2.39 yet.

**Comment by t-8ch** [comment]
The commit is actually released in 2.39.1 as 6fa034d0a99cc4e5a11f21ebf03b974134b734d0

**Comment by neilbrown** [comment]
Great - thanks for that!
