### ISSUE TITLE
error: 'struct statx' has no member named 'stx_mnt_id'; did you mean 'stx_uid'

### ISSUE THREAD

**Issue by pyrates999** [util-linux/util-linux#2415]
This happens while compiling util-linux 2.39.1.  here is the output while compiling:

`  CC       libmount/src/la-hook_mount.lo
libmount/src/hook_mount.c: In function 'hook_create_mount':
libmount/src/hook_mount.c:293:40: error: 'struct statx' has no member named 'stx_mnt_id'; did you mean 'stx_uid'?
  293 |                 cxt->fs->id = (int) st.stx_mnt_id;
      |                                        ^~~~~~~~~~
      |                                        stx_uid
make[3]: *** [Makefile:11300: libmount/src/la-hook_mount.lo] Error 1`

This also happens while compiling util-linux 2.39.

It did not happen while compiling util-linux 2.38.x and earlier.

**Comment by karelzak** [comment]
Can you check your /usr/include/linux/stat.h for STATX_MNT_ID and stx_mnt_id? Strangely, it reports a missing struct member but no STATX_MNT_ID. What version of the kernel headers do you use?

Anyway, the statx() call should be covered by #ifdef in case the function is unavailable. In this case, the call is optional.

**Comment by pyrates999** [comment]
Linux kernel version used is 5.15.23, coming from toolchain compiler crosstool-ng 1.25.0.

I found the file path/to/staging/usr/include/linux/stat.h

That file does have this in it:
`struct statx {
	/* 0x00 */
	__u32	stx_mask;	/* What results were written [uncond] */
	__u32	stx_blksize;	/* Preferred general I/O size [uncond] */
	__u64	stx_attributes;	/* Flags conveying information about the file [uncond] */
	/* 0x10 */
	__u32	stx_nlink;	/* Number of hard links */
	__u32	stx_uid;	/* User ID of owner */
	__u32	stx_gid;	/* Group ID of owner */
	__u16	stx_mode;	/* File mode */
	__u16	__spare0[1];
	/* 0x20 */
	__u64	stx_ino;	/* Inode number */
	__u64	stx_size;	/* File size */
	__u64	stx_blocks;	/* Number of 512-byte blocks allocated */
	__u64	stx_attributes_mask; /* Mask to show what's supported in stx_attributes */
	/* 0x40 */
	struct statx_timestamp	stx_atime;	/* Last access time */
	struct statx_timestamp	stx_btime;	/* File creation time */
	struct statx_timestamp	stx_ctime;	/* Last attribute change time */
	struct statx_timestamp	stx_mtime;	/* Last data modification time */
	/* 0x80 */
	__u32	stx_rdev_major;	/* Device ID of special file [if bdev/cdev] */
	__u32	stx_rdev_minor;
	__u32	stx_dev_major;	/* ID of device containing file [uncond] */
	__u32	stx_dev_minor;
	/* 0x90 */
	__u64	stx_mnt_id;
	__u64	__spare2;
	/* 0xa0 */
	__u64	__spare3[12];	/* Spare space for future expansion */
	/* 0x100 */
};

/*
 * Flags to be stx_mask
 *
 * Query request/result mask for statx() and struct statx::stx_mask.
 *
 * These bits should be set in the mask argument of statx() to request
 * particular items when calling statx().
 */
#define STATX_TYPE		0x00000001U	/* Want/got stx_mode & S_IFMT */
#define STATX_MODE		0x00000002U	/* Want/got stx_mode & ~S_IFMT */
#define STATX_NLINK		0x00000004U	/* Want/got stx_nlink */
#define STATX_UID		0x00000008U	/* Want/got stx_uid */
#define STATX_GID		0x00000010U	/* Want/got stx_gid */
#define STATX_ATIME		0x00000020U	/* Want/got stx_atime */
#define STATX_MTIME		0x00000040U	/* Want/got stx_mtime */
#define STATX_CTIME		0x00000080U	/* Want/got stx_ctime */
#define STATX_INO		0x00000100U	/* Want/got stx_ino */
#define STATX_SIZE		0x00000200U	/* Want/got stx_size */
#define STATX_BLOCKS		0x00000400U	/* Want/got stx_blocks */
#define STATX_BASIC_STATS	0x000007ffU	/* The stuff in the normal stat struct */
#define STATX_BTIME		0x00000800U	/* Want/got stx_btime */
#define STATX_MNT_ID		0x00001000U	/* Got stx_mnt_id */

#define STATX__RESERVED		0x80000000U	/* Reserved for future struct statx expansion */
`
I used these options when running configure as well:

`	CFLAGS="--sysroot path/to/staging -fstack-protector-all -Ipath/to/staging/usr/include" \
	CPPFLAGS="--sysroot path/to/staging -fstack-protector-all -Ipath/to/staging/usr/include" \
`

**Comment by pyrates999** [comment]
Thank you very much!  That patch fixed it!
