### ISSUE TITLE
losetup JSON report wrong

### ISSUE THREAD

**Issue by socketpair** [util-linux/util-linux#2460]
`losetup -l --json --output-all`:

```JSON
{
   "loopdevices": [
      {
         "name": "/dev/loop0",
         "autoclear": true,
         "back-file": "/tmp/test.dat",
         "back-ino": 37320,
         "back-maj:min": "       0:41 ",   # <------- extra spaces here
         "maj:min": "  7:0  ",     # <------- extra spaces here
         "offset": 0,
         "partscan": false,
         "ro": true,
         "sizelimit": 0,
         "dio": false,
         "log-sec": 512
      }
   ]
}
```

```
$ LANG=C losetup --version
losetup from util-linux 2.38.1
```

**Comment by socketpair** [comment]
Also, I would suggest: 
1. using `_` instead of `-` for JS. in JS you can use `result.back_file` instead of `result['back-file']`
2. split major:minor fields to two separate fields (like "maj" and "min").
3. possibly `{ back: { maj: xx, min: yyy, file: zzz, ino: rrr}}`

For backward compatibility, you may add new fields, and retain old fields for some time.

**Comment by karelzak** [comment]
Adding extra struct "back" for JSON is impossible because libsmartcols and it generates the output uses one "flat" table in this case.

**Comment by socketpair** [comment]
@karelzak is it possible to change field names at least ? i.e. backMaj (better) or back_maj (worse) ?

**Comment by karelzak** [comment]
@socketpair, it's MAJ and MIN for the device and BACK-MAJ and BACK-MIN for the backing file.

**Comment by karelzak** [comment]
Note that all libsmartcols-based tools use the JSON fields with the same names as the standard output columns. It only escapes problematic chars in the strings and converts all to lowercase, nothing else.

Maybe we can add a format optimization (tweaks) to modify field names (something like `--json=prettyNames[,etc]`) to automatically convert things like BACK-MAJ to `backMaj`, or log-sec `logSec`.
