### ISSUE TITLE
Obtain KNAME and PKNAME via <blkid.h> and partititons.c example

### ISSUE THREAD

**Issue by unixpro1970** [util-linux/util-linux#2463]
Hello blkid team,

Compiled the example blkid partitions.c (iink is below) which works well for obtaining the UUID.  However, I also would like to obtain KNAME and PKNAME for each entry.   When I attempt to modify the partitions.c code, I am unable to obtain KNAME and PKNAME.

How can I obtain KNAME and PKNAME by modifying the following partitions.c example.  lsblk.c does it, but requires functions that don't appear to part of <blkid.h> and I am sure what to do?

https://github.com/util-linux/util-linux/blob/master/libblkid/samples/partitions.c

Thanks

**Comment by karelzak** [comment]
libblkid returns information about block devices' content, nothing else.

lsblk gets KNAME and PKNAME from /sys/block/.
