### ISSUE TITLE
where is defined &conv in auth.c ? (Util-linux-2.39)

### ISSUE THREAD

**Issue by AlexeiKharchev** [util-linux/util-linux#2472]
Hi! I have problem with util-linux compiling. My Linux Mint description is attached [my_system.txt](https://github.com/util-linux/util-linux/files/12471176/my_system.txt)

tar xvf util-linux-2.39.2.tar.xz

cd util-linux-2.39.2

install -v -d mybuild

cd mybuild

meson setup --prefix=/tools/util-linux-2.39.2 --default-library=shared --debug --buildtype=debugoptimized ..
ninja
[3/604] Compiling C object chfn.p/login-utils_auth.c.o
FAILED: chfn.p/login-utils_auth.c.o
ccache gcc -Ichfn.p -I. -I.. -Iinclude -I../include -Ilibblkid -I../libblkid -I../libblkid/src -Ilibsmartcols -I../libsmartcols -I../libsmartcols/src -Ilibmount -I../libmount -I../libmount/src -Ilibfdisk -I../libfdisk -I../libfdisk/src -I../libuuid/src -Isys-utils -I../sys-utils -I/usr/local/include/ncursesw -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O2 -g -D_GNU_SOURCE -include /mnt/Git/apt-build/build/util-linux-2.39.2/mybuild/config.h -fno-common -Waddress-of-packed-member -Wdiscarded-qualifiers -Wformat-security -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-missing-field-initializers -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wsign-compare -Wstrict-prototypes -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -MD -MQ chfn.p/login-utils_auth.c.o -MF chfn.p/login-utils_auth.c.o.d -o chfn.p/login-utils_auth.c.o -c ../login-utils/auth.c
../login-utils/auth.c: In function ‘auth_pam’:
../login-utils/auth.c:41:48: error: ‘conv’ undeclared (first use in this function)
   41 |   retcode = pam_start(service_name, username, &conv, &pamh);
      |                                                ^~~~
../login-utils/auth.c:41:48: note: each undeclared identifier is reported only once for each function it appears in
[4/604] Compiling C object chsh.p/login-utils_auth.c.o
FAILED: chsh.p/login-utils_auth.c.o
ccache gcc -Ichsh.p -I. -I.. -Iinclude -I../include -Ilibblkid -I../libblkid -I../libblkid/src -Ilibsmartcols -I../libsmartcols -I../libsmartcols/src -Ilibmount -I../libmount -I../libmount/src -Ilibfdisk -I../libfdisk -I../libfdisk/src -I../libuuid/src -Isys-utils -I../sys-utils -I/usr/local/include/ncursesw -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O2 -g -D_GNU_SOURCE -include /mnt/Git/apt-build/build/util-linux-2.39.2/mybuild/config.h -fno-common -Waddress-of-packed-member -Wdiscarded-qualifiers -Wformat-security -Wimplicit-function-declaration -Wmissing-declarations -Wmissing-parameter-type -Wmissing-prototypes -Wnested-externs -Wno-missing-field-initializers -Wold-style-definition -Wpointer-arith -Wredundant-decls -Wsign-compare -Wstrict-prototypes -Wtype-limits -Wuninitialized -Wunused-but-set-parameter -Wunused-but-set-variable -Wunused-parameter -Wunused-result -Wunused-variable -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -MD -MQ chsh.p/login-utils_auth.c.o -MF chsh.p/login-utils_auth.c.o.d -o chsh.p/login-utils_auth.c.o -c ../login-utils/auth.c
../login-utils/auth.c: In function ‘auth_pam’:
../login-utils/auth.c:41:48: error: ‘conv’ undeclared (first use in this function)
   41 |   retcode = pam_start(service_name, username, &conv, &pamh);
      |                                                ^~~~
../login-utils/auth.c:41:48: note: each undeclared identifier is reported only once for each function it appears in
[8/604] Compiling C object last.p/login-utils_last.c.o
ninja: build stopped: subcommand failed.

**Comment by karelzak** [comment]
It seems meson does not find security/pam_misc.h header file. So, HAVE_SECURITY_PAM_MISC_H is not defined, the code is:

```C
#ifdef HAVE_SECURITY_PAM_MISC_H
                struct pam_conv conv = { misc_conv, NULL };
#elif defined(HAVE_SECURITY_OPENPAM_H)
                struct pam_conv conv = { openpam_ttyconv, NULL };
#endif                      

```
The *conv points to the PAM library-defined function.
