### ISSUE TITLE
Run wdctl (read-only) change the behavior of kernel panic

### ISSUE THREAD

**Issue by tduf** [util-linux/util-linux#2543]
Running the `wdctl` tool without arguments (so in read-only mode) changes the behaviour of a kernel panic. If `wdctl` is executed, the system reboot after a kernel panic. This is not the case if the kernel panic is triggered before `wdtcl`.

### Bug reproduction
 * Run wdctl
```
# wdctl
Device:        /dev/watchdog0
Identity:      imx2+ watchdog [version 0]
Timeout:       60 seconds
Pre-timeout:    0 seconds
FLAG           DESCRIPTION               STATUS BOOT-STATUS
KEEPALIVEPING  Keep alive ping reply          1           0
MAGICCLOSE     Supports magic close char      0           0
PRETIMEOUT     Pretimeout (in seconds)        0           0
SETTIMEOUT     Set timeout (in seconds)       0           0
```
 * Trig a kernel panic (need to enable the ONFIG_MAGIC_SYSRQ kernel conf)
```
# echo c > /proc/sysrq-trigger
[  701.497686] sysrq: Trigger a crash
[  701.501110] Kernel panic - not syncing: sysrq triggered crash
[  701.506859] CPU: 2 PID: 426 Comm: sh Not tainted 5.15.32-lts-next+g95c146e1eb7d #1
[  701.514432] Hardware name: CompuLab SB-IOTGIMX8 board + IED-BASE extension (DT)
[...]
```
 * A reboot of the system is observed after the "timeout" (60s).

### Expected
I will assume that only *showing the status of the hardware watchdog* with wdctl does not modify the state of the watchdog.

### Proposal
Use the sysfs API before the device API in read-only mode in the `read_watchdog` function.

Bonus:
 * It *could* also avoid issue (can not stop the watchdog) when CONFIG_WATCHDOG_NOWAYOUT is set. TBC.

```diff
diff --git a/sys-utils/wdctl.c b/sys-utils/wdctl.c
index 8de5d5a..306482a 100644
--- a/sys-utils/wdctl.c
+++ b/sys-utils/wdctl.c
@@ -494,10 +494,10 @@ nosysfs:
 
 static int read_watchdog(struct wd_device *wd)
 {
-       int rc = read_watchdog_from_device(wd);
+       int rc = read_watchdog_from_sysfs(wd);
 
-       if (rc == -EBUSY || rc == -EACCES || rc == -EPERM)
-               rc = read_watchdog_from_sysfs(wd);
+       if (rc)
+               rc = read_watchdog_from_device(wd);
 
        if (rc) {
                warn(_("cannot read information about %s"), wd->devpath);
```

### Information
* Built with Yocto Kirkstone (util-linux 2.37.4)
* Kernel 5.15 (lf-5.15.y from nxp-imx)
* arm64 (IMX8MM)
* The watchdog is "enable" in the dts but not activated/feeded.

**Comment by t-8ch** [comment]
FYI "options" and "fw_version" are only reported through sysfs in fairly recent kernels.

**Comment by karelzak** [comment]
Is there any way we can detect enabled CONFIG_WATCHDOG_NOWAYOUT to avoid open(/dev/watchdog)?

**Comment by t-8ch** [comment]
Check for bit `WDOG_NO_WAY_OUT` (1) in the status via sysfs?
But sysfs is optional and then we can read it via sysfs in the first place.

Another possibility would have been to treat read-only opens of /dev/watchdog specially in the kernel.
But that would break userspace so it's not an option.

Or try sysfs and if sysfs is missing some data fall back to /dev/watchdog.

**Comment by karelzak** [comment]
> Or try sysfs and if sysfs is missing some data fall back to /dev/watchdog.

This sounds like a plan. We can skip the fallback to /dev/watchdog when /sys/dev/char/.../nowayout is non-zero in sysfs. 
```
if (wd->nowayout == 0 && (rc || something_is_missing()))
   rc = read_watchdog_from_device(wd);
```
Do you want to prepare a patch? :-)

**Comment by t-8ch** [comment]
I can prepare a patch.

But in general it seems unfortunate to open /dev/watchdog at all.
It triggers stuff inside the watchdog core and only one process can ever do it at the same time.

Would it be to much of a change gate the opening of /dev/watchdog behind a CLI flag?

Or at least add a flag to prevent it.
