### ISSUE TITLE
lscpu 2.37.4 parse output now delimiting on comma and not colon

### ISSUE THREAD

**Issue by msenizai** [util-linux/util-linux#2544]
Man page says using this will delmit with colon, but has changed to a comma.
"If the list argument is used, cache columns are separated with a colon (:)."

lscpu --parse=cache delimits with : on all but one system we use

[root@hostname ~]# lscpu --version
lscpu from util-linux 2.37.4
[root@hostname ~]# lscpu --parse=cache |tail -n 1
407,407,407,50

[root@hostname ~]#  lscpu --version
lscpu from util-linux 2.32.1
[root@hostname ~]# lscpu --parse=cache |tail -n 1
191:191:191:23

**Comment by karelzak** [comment]
Use `--extended` or `--caches `it's based on libsmartcols, supports JSON, etc. 

Frankly, I think we should mark the old horrible `--parse` as deprecated in favor of `--extended`.

**Comment by msenizai** [comment]
--caches is not useful, we have a number of different AMD CPU's and use this to determine the number of L3 Caches, and the number of cores per L3 Cache (4, 8, 12 caches, 2 4 6 8 16 CPU's per cache) to evenly distribute full or under-subscribed workloads across all CCD's for maximum cache and memory bandwidth utilization depending on the application and application model.  

--extended is fine, but we still have to modify our scripts to parse out the 4th field, the issue is the behavior changed and is different from the documentation.
