### ISSUE TITLE
cfdisk: resizing incorrectly calculates free space when partitions are out of order

### ISSUE THREAD

**Issue by t-8ch** [util-linux/util-linux#2580]
Consider the following disk layout:
```
label: gpt
label-id: DC2E6ABF-5C86-4DAD-8FF4-592B000F4F56
device: disk.img
unit: sectors
first-lba: 2048
last-lba: 40926
sector-size: 512

disk.img1 : start=        8192, size=        4097, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=E5629758-47D7-42F7-9A29-FC9E4E0D6585
disk.img2 : start=        2048, size=        6144, type=0FC63DAF-8483-4772-8E79-3D69D8477DE4, uuid=40DA19C9-53E6-4F4E-9D77-0114B52AF237
```

Partition one is physically after partition two.
When trying to resize partition one to make it larger, cfdisk does not recognize that there is plenty of space left after the partition.

**Comment by karelzak** [comment]
The question is if we want to support any advanced operations with such a layout ;-) 

You will always see "table entries are not in disk order" when you print the PT, and there is a way how to sort the table before you do anything else. 

Maybe all we need is to call fdisk_table_wrong_order() and reject resize if not in the expected order.

**Comment by karelzak** [comment]
I have no time right now to test where the problem is, but see libfdisk/src/partition.c:recount_resize(), it sorts PT and free-space by start sector:

```C
        rc = fdisk_get_partitions(cxt, &tb);
        if (!rc) {
                /* For resize we do not follow grain to detect free-space, but
                 * we support to resize with very small granulation. */
                unsigned long org = cxt->grain;
                 
                cxt->grain = cxt->sector_size;
                rc = fdisk_get_freespaces(cxt, &tb);
                cxt->grain = org;
        }        
        if (rc) {
                fdisk_unref_table(tb);
                return rc;
        }        
                 
        fdisk_table_sort_partitions(tb, fdisk_partition_cmp_start);
```

**Comment by t-8ch** [comment]
Yeah, but in cfdisk.c it figures out the next partition like this:
```c
next = fdisk_table_get_partition(cf->table, cf->lines_idx + 1);
```

> I have no time right now

It's really not urgent, and the ticket is mostly a reminder for myself.
