### ISSUE TITLE
column: support an option to avoid treating consecutive delimiters as a single delimiter

### ISSUE THREAD

**Issue by sbraz** [util-linux/util-linux#2591]
Hi,
I noticed that Debian used to ship a modified BSD `column` with this patch: https://salsa.debian.org/meskes/bsdmainutils/-/blob/debian/11.1.2/debian/patches/column_nomerge.diff

It added a very useful option to avoid treating consecutive delimiters as one delimiter. Would it please be possible to implement something similar for util-linux's `column`?
The option couldn't be mapped to `-n` as it is already used, but maybe `--separator-no-merge` (or `--no-merge`) with a shorthand of `-M` or `-S`?

For reference, I learnt about this option via https://unix.stackexchange.com/questions/496193/print-table-with-empty-columns-for-consecutive-delimiters.

**Comment by t-8ch** [comment]
In util-linux column this is determined by the `greedy` mode.
`greedy` mode is on by default, but as soon as an explicit separator is specified it is disabled.

The example from your link:

```sh
$ echo -e 'a\tb\tc\nd\t\tf' | ./column -t 
a  b  c
d  f  
$ echo -e 'a\tb\tc\nd\t\tf' | ./column -t -s $'\t'
a  b  c
d     f
```

**Comment by sbraz** [comment]
Hi, you're absolutely right. I don't know why I didn't notice this. I'll close the issue, thanks.
