### ISSUE TITLE
RFE: lsblk: add --list-columns, add columns datatype to output

### ISSUE THREAD

**Issue by karelzak** [util-linux/util-linux#2595]
Let's follow lsfd and split --help output and move the list of the columns to --list-columns, add datatype, like:
```
     SOURCE  <string>  file system, partition, or device containing file
```

**Comment by masatake** [comment]
See #2602.

**Comment by masatake** [comment]
See #2831 for lsns.

**Comment by masatake** [comment]
lsblk has the --list-columns option already.
