### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [util-linux/util-linux#2619]
On create github release entry is created email notification to those whom have set in your repo the web UI Watch->Releases.
gh release can contain additional comments (li changelog) or additional assets like release tar balls (by default it contains only assets from git tag) however all those part are not obligatory.
In simplest variant gh release can be empty because subiekt of the sent email contains git tag name.

I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.
Probably other people may be interested to be instantly informed about release new version as well.

Documentation and examples of generate gh releases:
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://cli.github.com/manual/gh_release_upload/
https://github.com/jbms/sphinx-immaterial/pull/282
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026
tox target to publish on pypi and make gh release https://github.com/jaraco/skeleton/blob/928e9a86d61d3a660948bcba7689f90216cc8243/tox.ini#L42-L58

**Comment by eli-schwartz** [comment]
More documentation and examples:

https://github.com/mesonbuild/meson-python/issues/484

Please stop harassing projects about this! Thank you!

**Comment by kloczek** [comment]
Yep .. meson is another project which I've POLITELY only ASKED to start make gh releases.

**Comment by kloczek** [comment]
Just fresh example that some other maintainers are not looking on such RFE as harassment
https://github.com/open-mpi/hwloc/issues/625

**Comment by Conan-Kudo** [comment]
> I'm asking because my automation process uses those email notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.

As has been suggested in https://github.com/openSUSE/libsolv/issues/547, please just use the API from release-monitoring.org or subscribe to its messages on the fedora-messaging message bus instead of spamming every project with this request.

**Comment by karelzak** [comment]
The official and primary location for util-linux releases is kernel.org. It's also the location for the primary git repository. It provides a safe and verified way to distribute tarballs and other resources. 

I don't plan to use GitHub for releases.

We use GitHub as an excellent collaboration tool, but nothing else.
