### ISSUE TITLE
misleading warning, suggested improvement for warn_size(...) in losetup.c

### ISSUE THREAD

**Issue by moefear85** [util-linux/util-linux#2689]
In the file [losetup.c:532](https://github.com/util-linux/util-linux/blob/master/sys-utils/losetup.c#L532C1-L532C1), the warning message is ambiguous, especially for a noob. May I suggest:

```
"%s: Warning: file does not end on a 512-byte sector; "
		        "the last sector of the file will be ignored."
```

**Comment by karelzak** [comment]
For fdisk-like tools, we use a "sector boundary" term. What about:

   `Warning: file does not end on a 512-byte sector boundary; the remaining end of the file will be ignored.`

?

**Comment by moefear85** [comment]
that would be even better thx.
