### ISSUE TITLE
blkid false positive identification of hfsplus

### ISSUE THREAD

**Issue by huww98** [util-linux/util-linux#2692]
We've hit false positive identification of hfsplus multiple times on random data (from new encrypted disk from cloud provider).

It seems the possibility of false positive can be improved. For example, I made up this test data to fool blkid:
```
$ xxd -a pkg/blkid/test.img 
00000000: 0000 0000 0000 0000 0000 0000 0000 0000  ................
*
00000400: 482b 0000 0000 0000 0000 0000 0000 0000  H+..............
00000410: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000420: 0000 0000 0000 0000 0000 0200 0000 0000  ................
00000430: 0000 0000 0000 0000 0000 0000 0000 0000  ................
*
00000520: 0005 0000 0000 0000 0000 0000 0000 0000  ................
00000530: 0000 0000 0000 0000 0000 0000 0000 0000  ................
*
00001ff0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
$ blkid pkg/blkid/test.img
pkg/blkid/test.img: BLOCK_SIZE="512" TYPE="hfsplus"
```
The necessary conditions are:
* signature: H+/HX
* blocksize: >= 512 (almost certainly true for random data)
* extents[0].start_block: larger than disk size (very possible for random data)

Can we change this line (and similar lines) to return 1 ?
https://github.com/util-linux/util-linux/blob/aa88815653145b7e2b27fbb8a808971d779c2e05/libblkid/src/superblocks/hfs.c#L256

Or is it intentional to return success for incomplete block device?

**Comment by karelzak** [comment]
@huww98, please test the pull request https://github.com/util-linux/util-linux/pull/2693
