### ISSUE TITLE
libblkid：Ext4 is incorrectly probed  as drbd.

### ISSUE THREAD

**Issue by zhangyao108** [util-linux/util-linux#2701]
A piece of data is 0x83740267 in the last sector. result in libblkid probe error.
![image](https://github.com/util-linux/util-linux/assets/110269838/c5db3f28-3f5b-4422-bcb2-1921228b5ada)
https://github.com/util-linux/util-linux/blob/489b175c11cee48a4a2ee094075d0ff2a4da0024/libblkid/src/superblocks/drbd.c#L32C11-L32C11

**Comment by biubiuzy** [comment]
I wonder if we can make the detection file system more robust, especially the raid file system type, because it has different super block addresses from other file system types.

**Comment by karelzak** [comment]
Not sure if I understand what you mean. The library cares about the offsets.

Anyway, I guess we can close this drbd issue.

**Comment by biubiuzy** [comment]
> Not sure if I understand what you mean. The library cares about the offsets.
> 
> Anyway, I guess we can close this drbd issue.

I mean, is it possible to modify other probe file system functions(e.g probefunc) to reduce false positives?

**Comment by t-8ch** [comment]
It is always possible.
Unfortunately the proprietary RAID formats are not documented, so it's hard to write better probe functions
