### ISSUE TITLE
V2.31.1 make is failing

### ISSUE THREAD

**Issue by GoreshM** [util-linux/util-linux#2715]
Hi,
I have clone of repo for version 2.31.1, it is failing to compile when i perform make on linux aarch64 system.

I tried the same with x64 host the issue is not seen on x64. So its something with related to ARM
make 
make  all-recursive
make[1]: Entering directory '/tmp/build/Repos/libuuid/util-linux/build'
Making all in po
make[2]: Entering directory '/tmp/build/Repos/libuuid/util-linux/build/po'
test ! -f ../../po/util-linux.pot || \
  test -z "../../po/ca.gmo ../../po/cs.gmo ../../po/da.gmo ../../po/de.gmo ../../po/es.gmo ../../po/et.gmo ../../po/eu.gmo ../../po/fi.gmo ../../po/fr.gmo ../../po/gl.gmo ../../po/hr.gmo ../../po/hu.gmo ../../po/id.gmo ../../po/it.gmo ../../po/ja.gmo ../../po/nl.gmo ../../po/pl.gmo ../../po/pt_BR.gmo ../../po/ru.gmo ../../po/sl.gmo ../../po/sv.gmo ../../po/tr.gmo ../../po/uk.gmo ../../po/vi.gmo ../../po/zh_CN.gmo ../../po/zh_TW.gmo" || make ../../po/ca.gmo ../../po/cs.gmo ../../po/da.gmo ../../po/de.gmo ../../po/es.gmo ../../po/et.gmo ../../po/eu.gmo ../../po/fi.gmo ../../po/fr.gmo ../../po/gl.gmo ../../po/hr.gmo ../../po/hu.gmo ../../po/id.gmo ../../po/it.gmo ../../po/ja.gmo ../../po/nl.gmo ../../po/pl.gmo ../../po/pt_BR.gmo ../../po/ru.gmo ../../po/sl.gmo ../../po/sv.gmo ../../po/tr.gmo ../../po/uk.gmo ../../po/vi.gmo ../../po/zh_CN.gmo ../../po/zh_TW.gmo
make[3]: Entering directory '/tmp/build/Repos/libuuid/util-linux/build/po'
cd ../../po && : --update --no-wrap --lang=ca ca.po util-linux.pot
cd ../../po && rm -f ca.gmo && : -c --statistics --verbose -o ca.gmo ca.po
mv: cannot stat 't-ca.gmo': No such file or directory
make[3]: *** [Makefile:548: ../../po/ca.gmo] Error 1
make[3]: Leaving directory '/tmp/build/Repos/libuuid/util-linux/build/po'
make[2]: *** [Makefile:586: stamp-po] Error 2
make[2]: Leaving directory '/tmp/build/Repos/libuuid/util-linux/build/po'
make[1]: *** [Makefile:12401: all-recursive] Error 1
make[1]: Leaving directory '/tmp/build/Repos/libuuid/util-linux/build'
make: *** [Makefile:5426: all] Error 2

Top of git:
![image](https://github.com/util-linux/util-linux/assets/134932652/23bb4650-71ca-4939-b0e3-f0bc42dff68e)

autogen output
![image](https://github.com/util-linux/util-linux/assets/134932652/d9c06b15-be75-4307-a5aa-5a85fb0e1e6d)

Configure output
![image](https://github.com/util-linux/util-linux/assets/134932652/716a5b52-b3e2-465f-9cb6-f75025695dd0)

make output
![image](https://github.com/util-linux/util-linux/assets/134932652/a7ed2ee1-c25c-42ae-98d3-4d5ba76a440f)

[logs.zip](https://github.com/util-linux/util-linux/files/13975856/logs.zip)
Adding the _out file of each step for reference

**Comment by karelzak** [comment]
You have reported 7 years old release. ... The only question is if you can reproduce the issue with the current git tree or the latest stable release (v2.39.3).

**Comment by sagarsahu27** [comment]
@GoreshM please close the issue we found the rootcause. No action needed here

**Comment by GoreshM** [comment]
Looking more into the errors, it looked to be issue with missing `xgettext` binary was missing.
Not entirely sure why was it missing as the `gettext` was available.
On reinstalling gettext package, the issue is no longer seen.
