### ISSUE TITLE
wrong transaltion for chfn manpage header in ft.po

### ISSUE THREAD

**Issue by t-8ch** [util-linux/util-linux#2731]
The following entry from `fr.po` leads to the generation of the manpage as `chfm.1`, so it won't be found by users.
Furthermore it leads to spurious rebuilds in the build system.

```
#. type: Plain text
#: ../login-utils/chfn.1.adoc:20
msgid "chfn - change your finger information"
msgstr "chfm - changer vos informations d'identification"
```

Cc @fmarchal-dojo

**Comment by fmarchal-dojo** [comment]
This issue was reported and fixed on January 8th.

The current translation is here:

https://translationproject.org/PO-files/fr/util-linux-man-2.39-rc3.fr.po

Frederic

**Comment by karelzak** [comment]
I merged the new po-man translation 1 hour ago :-) The issue seems fixed.

**Comment by t-8ch** [comment]
Hm, I rechecked it after your merge and thought it was still there.
But it isn't. Sorry for the noise.

**Comment by karelzak** [comment]
Anyway, during work on 2.40-rc2 we can fix all such issues.

**Comment by karelzak** [comment]
Hmm.. 
```
git grep -C2 "chfn - change your finger information"
```
seems interesting., I found another issue:
```
po-man/pt_BR.po-#: ../login-utils/chfn.1.adoc:20
po-man/pt_BR.po-#, fuzzy
po-man/pt_BR.po:msgid "chfn - change your finger information"
po-man/pt_BR.po-msgstr "Altere sua informação de finger.\n"
po-man/pt_BR.po-
--

```
