### ISSUE TITLE
Memory leak in function 'add_line_to_table'

### ISSUE THREAD

**Issue by JoraGevorgyan** [util-linux/util-linux#2736]
The memory leak is found by a static analyzer developed at [CAST]( https://www.linkedin.com/company/cast-center/).

The memory allocated [at line 558](https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/text-utils/column.c#L558) will left without free in case of exit from [macro](https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/text-utils/column.c#L562).

**Comment by karelzak** [comment]
Well, in util-linux, we do not use free-before-exit.
