### ISSUE TITLE
Memory leak in function 'load_xinfo_from_proc_netlink'

### ISSUE THREAD

**Issue by JoraGevorgyan** [util-linux/util-linux#2737]
The memory leak is found by a static analyzer developed at [CAST]( https://www.linkedin.com/company/cast-center/).

The memory allocated [at line 1896](https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L1896) is getting lost in each iteration.

**Comment by masatake** [comment]
Thank you. I will look into this.

**Comment by masatake** [comment]
I read my code carefully. However, I could not find leaks about the line.

**Comment by masatake** [comment]
The calloc'ed value is freed at https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L275 .

**Comment by JoraGevorgyan** [comment]
As I can see the  [calloc function call](https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L1896) is in a while loop and there's no trace to [free](https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L270C13-L270C28), but if you're sure that it's a false positive, please let me see the trace. Thanks in advice.

**Comment by masatake** [comment]
The value returned from calloc is stored to xinfo_tree (https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L66) via add_sock_info (https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L1905).

The xinof_tree is destroyed at https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L283 .

At https://github.com/util-linux/util-linux/blob/27eec306df02e2235788833423f6dd994a96f76c/misc-utils/lsfd-sock-xinfo.c#L275 in free_sock_xinfo that is called from destroy, the calloc'ed value is free'ed.

**Comment by masatake** [comment]
Now, I have found a way to leak. The situation is the same as that of #2736.
The answer is also the same: "Well, in util-linux, we do not use free-before-exit.".

**Comment by JoraGevorgyan** [comment]
Now I got that '&nl->sock' <=> '&nl'. Thanks a lot.

**Comment by masatake** [comment]
@JoraGevorgyan Could you close this?
