### ISSUE TITLE
taskset hangs with -c 0-18446744073709551615

### ISSUE THREAD

**Issue by sanjacob** [util-linux/util-linux#2748]
### Description

I was testing taskset until I bumped into this by accident.
I don't know whether it has been fixed yet, but I could not find any evidence
pointing towards this being a known bug. If it is, then I apologise.

Using taskset with the cpu list option set to specifically ` n-18446744073709551615`
will prevent the program from ever returning (while using 100% CPU). 

Most likely related to #775 (`-c 0--1`).

### Steps to Reproduce
```
taskset -c 0-18446744073709551615 true
```

### System Information

```
taskset from util-linux 2.36.1
Linux 5.10.0-27-amd64 (debian)
```

**Comment by t-8ch** [comment]
I can reproduce it, but it is just doing a lot of looping in
https://github.com/util-linux/util-linux/blob/master/lib/cpuset.c#L328

The code should probably validate that the number is not larger than what fits into the cpuset anyways.

**Comment by sanjacob** [comment]
Just for the record I found this while doing a take home assignment for a position at Canonical, which I didn't end up getting 😂
