### ISSUE TITLE
ERROR: C symbol SO_PASSCRED not found in header sys/socket.h

### ISSUE THREAD

**Issue by eworm-de** [util-linux/util-linux#2750]
I am trying to build `v2.40-rc1` for Arch Linux, but it fails:

```
util-linux/meson.build:761:22: ERROR: C symbol SO_PASSCRED not found in header sys/socket.h
```

Bisected this to commit 6240e4458cdf5a17c7b795def33b81cb5a987aed, though I can not yet explain what's the problem there.

CC @t-8ch

**Comment by eworm-de** [comment]
Reverting that commit makes the build succeed.

**Comment by t-8ch** [comment]
Do you have a reproduction command?

**Comment by eworm-de** [comment]
Currently away from keyboard, will have to look up the details later.

**Comment by t-8ch** [comment]
I can now reproduce it.
Plymouth support needs to be enabled explicitly.
