### ISSUE TITLE
BAD_COPY_PASTE  in libfdisk/src/table.c

### ISSUE THREAD

**Issue by AlexRudyuk** [util-linux/util-linux#2759]
[libfdisk/src/table.c](https://github.com/util-linux/util-linux/blob/fafb9123f2248159b8e483cd4782c4cfe04395fd/libfdisk/src/table.c#L793)

https://github.com/util-linux/util-linux/blob/fafb9123f2248159b8e483cd4782c4cfe04395fd/libfdisk/src/table.c#L793
in line 793:
Based on the structure of conditional constructions and clear repetition, it can be concluded that there is indeed a typo in line 793 and `pa` needs to be replaced with `pb`.

Found by Linux Verification Center ([portal.linuxtesting.ru](https://portal.linuxtesting.ru/)) with SVACE.
Author A. Slepykh ([a.slepykh@fobos-nt.ru](mailto:a.slepykh@fobos-nt.ru)).

**Comment by karelzak** [comment]
I have already seen this from some static analyzers (Coverity?). And it's a false positive ;-)
