### ISSUE TITLE
lsclocks -c displays wall-clock time, not cpu time

### ISSUE THREAD

**Issue by alanc** [util-linux/util-linux#2761]
The lsclocks man page says that the -c option prints the CPU clock of the specified process - but instead it prints the wall clock time:

```
   3161             cpu  1707001150.300113040   1ns 2024-02-03T22:59:10.300113040-08:00
```

This simple patch changes it to print the CPU time used by the specified process instead:

```
--- a/misc-utils/lsclocks.c
+++ b/misc-utils/lsclocks.c
@@ -505,7 +525,7 @@ static void add_cpu_clock(struct libscols_table *tb,
        struct clockinfo clockinfo = {
                .type = CT_CPU,
                .name = name,
-               .no_id = true,
+               .id = clockid,
        };
        add_posix_clock_line(tb, columns, ncolumns, &clockinfo);
 }
```

as seen here:
```
18446744073709526322 3161             cpu          47.963983654   1ns 1970-01-01T00:00:47.963983654-08:00
```

(The `.no_id = true` line can be left in place if you don't want to see the very large clock id used for this clock.)

**Comment by t-8ch** [comment]
Looks good. I'd like to keep the `no_id` as the id has no meaning for the user.

Do you want to open a PR?

**Comment by alanc** [comment]
Oh, I only got email for the "Do you want to open a PR?" update and didn't see another PR was already open before I submitted mine.  Either one works.

**Comment by t-8ch** [comment]
Let's use yours.
