### ISSUE TITLE
`dmesg` gives different `--show-delta` values for the same message, depending on whether `--since` is used

### ISSUE THREAD

**Issue by calestyo** [util-linux/util-linux#2770]
Hey there.

I noticed the following behaviour (which may not necessarily be a bug):
```
# t="$(date +%s)"
# echo 3 >|/proc/sys/vm/drop_caches
```
If one now does:
```
# dmesg --nopager --color=never --decode --show-delta --kernel --since "@$t"
```
one will get e.g.:
```
kern  :info  : [245941.414414 <    0,000000>] bash (104225): drop_caches: 3
```

If one lists the same message without `--since` like in:
```
# dmesg --nopager --color=never --decode --show-delta --kernel | tail -n 1
```
one gets:
```
kern  :info  : [245941.414414 <  640,137117>] bash (104225): drop_caches: 3
```
which is the above messsage, but the actual delta to the previous message.

Now one could of course argue, that in the first case the ` 0,000000` is correct, as there is no previous message (and thus no delta)... but actually there is one, it's just not shown.

In any case, it would be nice if this behaviour could be documented in either `--since`  and/or `--show-delta`, unless it's considered a "bug" and fixed.

Cheers,
Chris.

**Comment by karelzak** [comment]
I'll fix it; we can remember the time from the last rejected message.

**Comment by karelzak** [comment]
And I will fix more bugs related to the deltas.
