### ISSUE TITLE
New UUID formats

### ISSUE THREAD

**Issue by t-8ch** [util-linux/util-linux#2771]
There are efforts underway [0] to specify new types of UUIDs. These efforts are close to result in an RFC.
I have implementations for UUIDv6, UUIDv7 and what can be implemented for UUIDv8.

As always the problem is in the naming.
Currently libuuid uses function names like `uuid_generate_time()` which are named after some property of the generated UUID.

However V6 and V7 are als time based.
Using something like `uuid_generate_time_gregorian_sortable()` seems unwieldy and also non-obvious to a user who just wants to generate a UUIDv6.

Afaik outside of libuuid it is more common to refer to UUID types through their number.

I therefore propose to provide a new API for libuuid based on the version number and always with a return value. This should also apply to the existing functionality.
(With compat wrappers of course).

Example: `int uuid_generate_v4()`.

This new API can then be used for the new UUID types easily and uniformly.

[0] https://datatracker.ietf.org/doc/draft-ietf-uuidrev-rfc4122bis/14/

**Comment by sergeyprokhorenko** [comment]
@t-8ch
You can use these names for functions that generate UUIDs:

- `uuidv7()`
- `uuidv7(timestamp_shift)`

See the examples:

- [For JavaScript](https://www.npmjs.com/package/uuidv7)
- [For PostgreSQL](https://www.postgresql.org/message-id/attachment/155245/v17-0001-Implement-UUID-v7.patch)

**Comment by t-8ch** [comment]
@sergeyprokhorenko 

I think we need to keep the `uuid_generate_` prefix for namespacing purposes.

**Comment by karelzak** [comment]
We already have uuid_generate_sha1() or uuid_generate_md5(), so why not uuid_generate_timev7()?

 I think uuid_generate_v7() is also usable but less readable.

BTW, it's a mistake that the library does not use any handler. The ideal solution would be:
```
struct libuuid_context cxt = uuid_new_context();

/* v7 */
uuid_context_set_version(cxt, UUID_VERSION_7);   
uuid_generate_uuid(cxt, &uuid);

/* md5 based */
uuid_context_set_version(cxt, UUID_VERSION_MD5);
uuid_context_set_ns(cxt, "dns");
uuid_context_set_name(cxt, "foo.com"
uuid_generate_uuid(cxt, &uuid);
```

**Comment by t-8ch** [comment]
> so why not uuid_generate_timev7()?

Sounds good, will do.

> The ideal solution would be:

Do you want to add this API,
Or is it more wishful  thinking?

**Comment by sergeyprokhorenko** [comment]
uuid_generate_**uuidv7**() is better, because uuidv7 is an official name of the UUID Version 7 in the new RFC
