### ISSUE TITLE
"libmount: don't canonicalize symlinks for bind operation" (1b2d818) caused problems with btrfs targets

### ISSUE THREAD

**Issue by AdamWill** [util-linux/util-linux#2773]
Reported downstream (Fedora): https://bugzilla.redhat.com/show_bug.cgi?id=2262892

When util-linux 2.40 rc1 landed in Fedora Rawhide, it broke default installs of Fedora Silverblue (our immutable desktop version). There's a point when installing such payloads where anaconda (the Fedora/RHEL installer) does a bunch of bind mounts, and with the new util-linux one of them fails:

    11:34:00,709 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:Running... mount --bind /mnt/sysimage/home /mnt/sysroot/home
    11:34:00,720 WARNING org.fedoraproject.Anaconda.Modules.Payloads:INFO:program:mount: /mnt/sysroot/home: wrong fs type, bad option, bad superblock on /mnt/sysimage/home, missing codepage or helper program, or other error.

In a default configuration, both of those are backed by a btrfs subvolume. The bug does not happen if I tweak the install configuration to *not* use btrfs. /mnt/sysroot/home is a symlink pointing to var/home (so, to /mnt/sysroot/var/home ).

I bisected this down to https://github.com/util-linux/util-linux/commit/1b2d8187360157b00b47f52522fc039d82e34e6b . It seems maybe bind mounting over symlinks doesn't work on btrfs, or something? Maybe util-linux needs to still resolve symlinks in that case, or maybe there's a kernel bug to report here?

**Comment by AdamWill** [comment]
I don't honestly know the whole story of what the heck is going on with `/mnt/sysimage` and `/mnt/sysroot`, if it's relevant, it seems pretty weird on this path. (On various other paths with different payloads than "an ostree", they are different things, it's kind of an internal abstraction interface for anaconda, in a way). But here's what we can see from the logs:

    Feb 06 18:12:51 fedora org.fedoraproject.Anaconda.Modules.Storage[2199]: INFO:program:Running... findmnt -rn /mnt/sysroot
    Feb 06 18:12:51 fedora org.fedoraproject.Anaconda.Modules.Storage[2199]: INFO:program:Running... mount --rbind /mnt/sysimage /mnt/sysroot
    Feb 06 18:18:24 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... findmnt -rn /mnt/sysroot
    Feb 06 18:18:24 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:/mnt/sysroot /dev/vda3[/root] btrfs rw,relatime,seclabel,compress=zstd:1,discard=async,space_cache=v2,subvolid=258,subvol=/root
    Feb 06 18:18:24 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --make-rprivate /mnt/sysroot
    Feb 06 18:18:24 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... umount --recursive /mnt/sysroot
    Feb 06 18:18:24 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --rbind /mnt/sysimage/ostree/deploy/fedora/deploy/75ba65dc9f92c2717bf687f0ad06f1bad270ec4ab4119ecc99e4efabe81d8398.0 /mnt/sysroot
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... cp -r -p /mnt/sysroot/usr/lib/ostree-boot/efi /mnt/sysimage/boot
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --bind /mnt/sysroot/usr /mnt/sysroot/usr
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --bind -o remount,ro /mnt/sysroot/usr /mnt/sysroot/usr
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --rbind /mnt/sysimage/dev /mnt/sysroot/dev
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --rbind /mnt/sysimage/proc /mnt/sysroot/proc
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --rbind /mnt/sysimage/run /mnt/sysroot/run
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --rbind /mnt/sysimage/sys /mnt/sysroot/sys
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --bind /mnt/sysimage/var /mnt/sysroot/var
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/home
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/roothome
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/opt
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/srv
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/usrlocal
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/mnt
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/media
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/spool
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... systemd-tmpfiles --create --boot --root=/mnt/sysroot --prefix=/var/spool/mail
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --bind /mnt/sysimage/boot /mnt/sysroot/boot
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:Running... mount --bind /mnt/sysimage/home /mnt/sysroot/home
    Feb 06 18:18:25 fedora org.fedoraproject.Anaconda.Modules.Payloads[2212]: INFO:program:mount: /mnt/sysroot/home: wrong fs type, bad option, bad superblock on /mnt/sysimage/home, missing codepage or helper program, or other error.

so early in install it actually bind mounts `/mnt/sysimage` to `/mnt/sysroot`, then it umounts that and bind mounts something else there, then it embarks on the long list of bind mounts for child directories that eventually fails when it hits the one whose target is a symlink.

**Comment by cgwalters** [comment]
I can't imagine that's the only regression from this. I would argue for a revert, and the introduction of a new `--canonicalize-target` argument for example.

Or `--mount-on-symlink`?

**Comment by karelzak** [comment]
I'll revert the commit. 

For v2.41, we will need to implement something smarter, probably a mount option, something like `x-mount.symlink={target,source,...}` to make it possible to use symlinks also in fstab.

There are more areas where we have no userspace interface for the current kernel's ability to work with symlinks (FSPICK_SYMLINK_NOFOLLOW, MOVE_MOUNT_T_SYMLINKS, MOVE_MOUNT_F_SYMLINKS, etc,).
