### ISSUE TITLE
"script" utility does not respect --quiet flag when logging start messages with SCRIPT_FMT_RAW

### ISSUE THREAD

**Issue by resolritter** [util-linux/util-linux#2783]
# Problem

This is related to `log_start`  of `term-utils/script.c`

https://github.com/util-linux/util-linux/blob/26e778a790fb016f639af5919d08f9affa677f23/term-utils/script.c#L370

When `log->format` is `SCRIPT_FMT_RAW`, `log_start` always writes the "Script started on..." message even if `ctl->quiet` (--quiet CLI flag) is `true`

https://github.com/util-linux/util-linux/blob/26e778a790fb016f639af5919d08f9affa677f23/term-utils/script.c#L399

That behavior seems wrong because, if --quiet is provided through the CLI, no start message should be written.

https://github.com/util-linux/util-linux/blob/26e778a790fb016f639af5919d08f9affa677f23/term-utils/script.1.adoc?plain=1#L115-L116

# Suggestion

In https://github.com/util-linux/util-linux/blob/26e778a790fb016f639af5919d08f9affa677f23/term-utils/script.c#L393

Change to:

```diff
	switch (log->format) {
	case SCRIPT_FMT_RAW:
	{
+    if (!ctl->quiet) {
+       // log "Script started on %s..."
+    }
```

**Comment by karelzak** [comment]
I cannot reproduce this problem. `script --quiet` or `script --quiet anyfile` works for me.

What version of the script do you have? And can you provide any example?

**Comment by resolritter** [comment]
> I cannot reproduce this problem. `script --quiet` or `script --quiet anyfile` works for me.
> 
> What version of the script do you have?

@karelzak

The version of script I was using is `2.39.3`.

>  And can you provide any example?

Since this ticket is about logging, you can try it it `--log-in` or `--log-out`. For example, `script --quiet --log-out /path/to/file`. You'll notice that the "Script started on ..." message is **always** appended at the start of the log regardless of `--quiet`. There's not really any special step in order to reproduce this, other than using the logging options and observing the log.

I've applied a patch locally which dealt with the problem. I no longer see the "Script started on ..." message appear in the logs after that. The basic idea is to wrap the logging in `log_start` with an `if` statement, like so:

```diff
diff --git a/term-utils/script.c b/term-utils/script.c
index 3457ac8..9cce9b4 100644
--- a/term-utils/script.c
+++ b/term-utils/script.c
@@ -391,30 +391,32 @@ static int log_start(struct script_control *ctl,
 	switch (log->format) {
 	case SCRIPT_FMT_RAW:
 	{
-		int x = 0;
-		char buf[FORMAT_TIMESTAMP_MAX];
-		time_t tvec = script_time((time_t *)NULL);
+		if (!ctl.quiet) {
+			int x = 0;
+			char buf[FORMAT_TIMESTAMP_MAX];
+			time_t tvec = script_time((time_t *)NULL);
 
-		strtime_iso(&tvec, ISO_TIMESTAMP, buf, sizeof(buf));
-		fprintf(log->fp, _("Script started on %s ["), buf);
+			strtime_iso(&tvec, ISO_TIMESTAMP, buf, sizeof(buf));
+			fprintf(log->fp, _("Script started on %s ["), buf);
 
-		if (ctl->command)
-			x += fprintf(log->fp, "COMMAND=\"%s\"", ctl->command_norm);
+			if (ctl->command)
+				x += fprintf(log->fp, "COMMAND=\"%s\"", ctl->command_norm);
 
-		if (ctl->isterm) {
-			init_terminal_info(ctl);
+			if (ctl->isterm) {
+				init_terminal_info(ctl);
 
-			if (ctl->ttytype)
-				x += fprintf(log->fp, "%*sTERM=\"%s\"", !!x, "", ctl->ttytype);
-			if (ctl->ttyname)
-				x += fprintf(log->fp, "%*sTTY=\"%s\"", !!x, "", ctl->ttyname);
+				if (ctl->ttytype)
+					x += fprintf(log->fp, "%*sTERM=\"%s\"", !!x, "", ctl->ttytype);
+				if (ctl->ttyname)
+					x += fprintf(log->fp, "%*sTTY=\"%s\"", !!x, "", ctl->ttyname);
 
-			x += fprintf(log->fp, "%*sCOLUMNS=\"%d\" LINES=\"%d\"", !!x, "",
-					ctl->ttycols, ctl->ttylines);
-		} else
-			fprintf(log->fp, _("%*s<not executed on terminal>"), !!x, "");
+				x += fprintf(log->fp, "%*sCOLUMNS=\"%d\" LINES=\"%d\"", !!x, "",
+						ctl->ttycols, ctl->ttylines);
+			} else
+				fprintf(log->fp, _("%*s<not executed on terminal>"), !!x, "");
 
-		fputs("]\n", log->fp);
+			fputs("]\n", log->fp);
+		}
 		break;
 	}
 	case SCRIPT_FMT_TIMING_SIMPLE:
```

I can submit a PR for the patch if it looks acceptable.

**Comment by karelzak** [comment]
But it's not expected that `--quite` suppress anything in the log, man script:
```
      -q, --quiet
           Be quiet (do not write start and done messages to standard output).
```

**Comment by resolritter** [comment]
> But it's not expected that `--quite` suppress anything in the log, man script:
> 
> ```
>       -q, --quiet
>            Be quiet (do not write start and done messages to standard output).
> ```

Got it. I thought that `--quiet` would also apply to logging messages. If that is not the case, then sorry for bothering. I'll go ahead and close this.
