### ISSUE TITLE
lsns terminates with exit status 1 giving no error message.

### ISSUE THREAD

**Issue by joshiste** [util-linux/util-linux#2799]
I encounter (especially under high cpu load) that the lsns is exiting with an exit code = 1 without providing any error message.

I tried to debug this, and it appears that this happens every time a process is removed while iterating the processes in `read_processes`. 
I've traced it down to [this fstatat](https://github.com/util-linux/util-linux/blob/master/sys-utils/lsns.c#L297) or [this openat](https://github.com/util-linux/util-linux/blob/master/sys-utils/lsns.c#L306) failing with `ESRCH`.
So I wonder whether `ESRCH` has also to [be ignored (like ENOENT) here](https://github.com/util-linux/util-linux/blob/master/sys-utils/lsns.c#L548)

**Comment by masatake** [comment]
@karelzak Could you assign me to this issue? 
@joshiste sorry to be late to reply. Is the issue still reproducible in the latest code?

**Comment by joshiste** [comment]
Haven't tried it yet. Looking at the code imho `read_process` may still return `ESRCH` when the process dies just before the `openat` call...

**Comment by karelzak** [comment]
I agree that read_processes() should be more robust and ignore (continue) situations when the process dies.

**Comment by joshiste** [comment]
That's what I had in mind...

**Comment by masatake** [comment]
I'm working on making a pull request.

**Comment by karelzak** [comment]
I want to release the `stable/v2.40` branch as v2.40.3 in the next few days (including this bug fix) and v2.41 in January.
