### ISSUE TITLE
blkid_get_library_version(NULL,NULL) returns different values when using different build systems

### ISSUE THREAD

**Issue by WAAutoMaton** [util-linux/util-linux#2802]
When using the meson build system (e.g. `util-linux` package in [Arch Linux](https://gitlab.archlinux.org/archlinux/packaging/packages/util-linux/-/blob/main/PKGBUILD) ), the return value of `blkid_get_library_version(NULL,NULL)` will be `110`.

When using autotools (e.g. `libblkid-dev` package in Ubuntu), the return value of `blkid_get_library_version(NULL,NULL)` will be `2XXY`.

Is there something wrong with meson?

**Comment by karelzak** [comment]
Yes, something is wrong there:
 
./blkid -V; ./build/blkid -V
blkid from util-linux 2.40-rc1-129-cc64-dirty  (libblkid 2.40.0, 24-Jan-2024)
blkid from util-linux 2.40-rc1-129-cc64  (libblkid 1.1.0, 01-Jun-2021)
