### ISSUE TITLE
lsblk --json uses a list with one 'null' item to represent "none"

### ISSUE THREAD

**Issue by 2xsaiko** [util-linux/util-linux#2871]
You can see this in the fsroots and mountpoints values (other values omitted):

```json
{
   "blockdevices": [
      {
         "children": [
            {
               "fsroots": [
                   null
               ],
               "mountpoints": [
                   null
               ],
            },{
               "fsroots": [
                   "/store", "/persist/var", "/persist/etc", "/"
               ],
               "mountpoints": [
                   "/nix/store", "/var", "/etc", "/nix"
               ],
            }
         ]
      }
   ]
}
```

I would expect `[]` instead of `[null]` here.

lsblk from util-linux 2.39.3.

**Comment by karelzak** [comment]
The output passes JSON verifications, and 'null' is valid according to JSON specification.

**Comment by 2xsaiko** [comment]
The problem is with the data rather than the validity of the syntax. If there's no mountpoints, why is there one item in the list? What is the significance of it? Can the list ever be empty? Can there be more than one null item?

If the only time a null value is used here is in `[null]` to mean "no mountpoints", this is usually not how lists are used, and this state would be better represented by an empty list. Doing it like this just means additional processing for those who want to consume the data.

**Comment by karelzak** [comment]
OK, understand.

**Comment by 2xsaiko** [comment]
Thank you!
