### ISSUE TITLE
2.40: Release tarball is missing pam_lastlog2/meson.build file

### ISSUE THREAD

**Issue by jwillikers** [util-linux/util-linux#2875]
Building with the 2.40 release tarball with Meson produces the following error:

```
../src/meson.build:952:0: ERROR: Nonexistent build file 'pam_lastlog2/meson.build'
```

The file is indeed missing.

**Comment by satmandu** [comment]
I noticed this too. The git tag tarball has the file though: https://github.com/util-linux/util-linux/archive/refs/tags/v2.40.tar.gz

**Comment by milkylainen** [comment]
Yeah. I'm not able to use the release tarball at all.
Even if I disable liblastlog2 and the pam_lastlog2 option, it still produces the same error.
