### ISSUE TITLE
colrm BOMbs out upon BOM 

### ISSUE THREAD

**Issue by jidanni** [util-linux/util-linux#2909]
[BOM (0xFEFF)](https://en.wikipedia.org/wiki/Byte_order_mark) causes `colrm` to  BOMb out, without a peep even. Just stone cold dead.
```
$ head -n 1 $@|wc
      1      52     522
$ head -n 1 $@|colrm 11|wc
      0       0       0
```
colrm from util-linux 2.39.3

**Comment by t-8ch** [comment]
Can you provide an example file, version of libc and locale information?

**Comment by jidanni** [comment]
```
$ perl -wle 'print pack("CCC",0xef,0xbb,0xbf), 1 x 22;'|env - LC_CTYPE=zh_TW.UTF-8 colrm 11|wc
      1       1      14
$ perl -wle 'print pack("CCC",0xef,0xbb,0xbf), 1 x 22;'|env - colrm 11|wc
      0       0       0
```

**Comment by t-8ch** [comment]
According to the BOM your file is UTF-16LE. While your locale is UTF-8.
I'm not sure the widechar routines handle automatic conversion.

(I'll see why no error is reported)

**Comment by jidanni** [comment]
Should I report a file(1) bug? It says it's UTF-8:
```
$ perl -wle 'print pack("CCC",0xef,0xbb,0xbf), 1 x 22;'|env - file -
/dev/stdin: Unicode text, UTF-8 (with BOM) text
```

**Comment by t-8ch** [comment]
No, I misunderstood it. In your original ticket you showed 0xFEFF which is UTF-16LE.
But the reproducer uses 0xEF 0xBB 0xBF which is UTF-8.

**Comment by t-8ch** [comment]
But this also means that you will need to remove the BOM before feeding the file to colrm.
At least now there is an error.

**Comment by BrianInglis** [comment]
Utilities including rev(1) also used to just quit without any message. 
I think it might be better to allow that to be handled by a utility as a warning, and allow the utility to just copy the *byte* from input to output as appropriate?
