### ISSUE TITLE
fdisk refuses to create partition starting at 0 sector even in advanced mode

### ISSUE THREAD

**Issue by Selorax** [util-linux/util-linux#2916]
The problem is that some partition layouts have filesystem starting at sector 0, but the file system format has several free blocks at the start, which can be used to keep the partition table. 

The most common case is isohybrid where iso filesystem starts at sector 0, but a certain file it contains starts at some other sector.

fdisk should allow creating overlapping partitions if user knows what they are doing, especially the most common case when partition needs to start at LBA 0.

**Comment by karelzak** [comment]
You need 'b' command from the advanced menu.

```
Device     Boot Start    End Sectors Size Id Type
/dev/sdc1        2048 204799  202752  99M 83 Linux
...
Command (m for help): x

Expert command (m for help): b
Selected partition 1
New beginning of data (0-204799, default 2048): 0

...

Device     Boot Start    End Sectors  Size Id Type
/dev/sdc1           0 204799  204800  100M 83 Linux
```

**Comment by Selorax** [comment]
https://github.com/util-linux/util-linux/commit/03c3aae63cbe33a7c595b759cd65d1fc35450db7#diff-2b754558eaf51353c12c4ea30417337845c16c13de9cdd8fab96a349c32fab0bR2639

It seems that this was fixed Jul 27, 2021

**Comment by Selorax** [comment]
@karelzak 

I don't know if I should open a bug report on this, but I cannot create a BIOS Boot partition on an GPT disklabel. It is supposed to take space between GPT and first real partition (starting from 2048 as usual). I mean, it is possible when I reserve partition number 1 for that and start creating other, and I did make such partition before but this time around I get:

```
Command (m for help): n
Partition number (3-128, default 3): 
First sector (15726592-15728606, default 15726592): 64
Value out of range.
```
