### ISSUE TITLE
util-linux-script  2.37.4 left after  ssh session disconnected

### ISSUE THREAD

**Issue by az1minami** [util-linux/util-linux#2946]
At first, I thought it was an SSH problem, but ,
It looks like util-linux-script.　
I also asked about Rocky linux, so here is the background: ROCKY LINUX　Forums.

https://forums.rockylinux.org/t/strange-behavior-of-ssh-rocky-9-3-vs-cent-os-7-9/13442

windows/MAC terminal -> SSH ->  node A ( Jump server)   (script command logging ssh operetion to node B) ->  node B  (less  file )
Wifi disconnect a while. windows terminal met  “client_loop: send disconnect: Connection reset" 

using  script version  2.2.32 was  closed all ssh session on node A 
using  version  2.37.4  left script command  process .
so, I scp from 2.2.32  image on my local file and  tested ./script  , wifi disconnect , all session was closed with time out 

regards! 
/minami

script -V
script from util-linux 2.37.4 ( Rocky)
./script -V ( Coped from Linux (centos 7.9.2009)
script from util-linux 2.23.2

**Comment by karelzak** [comment]
It seems like an issue that has been addressed by commit 90ebcedb8701322685abaec76213dfba21757272. It should be already fixed in release v2.40.

**Comment by az1minami** [comment]
Thanks  karelzak-san

we can wait Rocky-linux formal update.

Thansk & regards!
