### ISSUE TITLE
dmesg -H output broken

### ISSUE THREAD

**Issue by zeha** [util-linux/util-linux#2951]
Debian bug https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1068831 was reported by "pdormeau", see below. I can confirm this problem:

---

After upgrading to 2.40-5, I have output like this when typing dmesg -H :

```
ESC[32m[  +0,000529] ESC[0mNo NUMA configuration found
ESC[32m[  +0,000001] ESC[0mFaking a node at [mem 0x0000000000000000-0x0000000c5f7fffff]
ESC[32m[  +0,000008] ESC[0mNODE_DATA(0) allocated [mem 0xc5f7d5000-0xc5f7fffff]
ESC[32m[  +0,000242] ESC[0mZone ranges:
ESC[32m[  +0,000001] ESC[0m  DMA      [mem 0x0000000000001000-0x0000000000ffffff]
ESC[32m[  +0,000002] ESC[0m  DMA32    [mem 0x0000000001000000-0x00000000ffffffff]
ESC[32m[  +0,000002] ESC[0m  Normal   [mem 0x0000000100000000-0x0000000c5f7fffff]
ESC[32m[  +0,000002] ESC[0m  Device   empty
ESC[32m[  +0,000001] ESC[0mMovable zone start for each node
ESC[32m[  +0,000002] ESC[0mEarly memory node ranges
ESC[32m[  +0,000000] ESC[0mESC[33m  node   0: ESC[0m[mem 0x0000000000001000-0x000000000009efff]
ESC[32m[  +0,000002] ESC[0mESC[33m  node   0: ESC[0m[mem 0x0000000000100000-0x000000008c36efff]
ESC[32m[  +0,000001] ESC[0mESC[33m  node   0: ESC[0m[mem 0x0000000091fff000-0x0000000091ffffff]
ESC[32m[  +0,000001] ESC[0mESC[33m  node   0: ESC[0m[mem 0x0000000100000000-0x0000000c5f7fffff]
ESC[32m[  +0,000004] ESC[0mInitmem setup node 0 [mem 0x0000000000001000-0x0000000c5f7fffff]
```

Reverting to 2.39.3-6 solves the issue.

---

To be clear, the `ESC[32m[` things are indeed shown as is on the screen. `dmesg` is still fine (with colors), but `dmesg -H` shows no colors and the broken escape sequences.

**Comment by t-8ch** [comment]
@zeha I can't reproduce this.

What is your terminal and `$TERM`?

**Comment by zeha** [comment]
> What is your terminal and `$TERM`?

`xterm-256color` or `screen-256color` are both affected.

I'll note that `dmesg -H` starts `pager` for me, which in turn is: less 590 (GNU regular expressions).

Replacing `pager` with `more` (from util-linux) **works**, actually better because the colors work.

Additional observation: `dmesg -H | less` is color-less, but also no `ESC` sequences are shown.

---
`dmesg -H` from u-l 2.40 (Debian unstable), internally starting `less` (via `sensible-pager` and `pager`):
<img width="790" alt="Screenshot 2024-04-12 at 12 50 08" src="https://github.com/util-linux/util-linux/assets/26175/8cb22846-8636-4786-a00d-51be4218696a">

`dmesg -H` from u-l 2.40 (Debian unstable), internally starting `more` (via `sensible-pager` and `pager`):
<img width="658" alt="Screenshot 2024-04-12 at 12 50 26" src="https://github.com/util-linux/util-linux/assets/26175/04dcd211-37d8-4b0c-90fb-13851b29983c">

`dmesg -H` from u-l 2.38.1 on Debian stable (with less):
<img width="750" alt="Screenshot 2024-04-12 at 12 50 42" src="https://github.com/util-linux/util-linux/assets/26175/a2b9a14a-19cd-47bf-be37-26159b031c73">

I'm having some trouble replicating Debian unstable + u-l 2.39 at this time, but the original submitter said this also works.

**Comment by zeha** [comment]
(My guess is color support detection going wrong somewhere?)

**Comment by t-8ch** [comment]
Now I can reproduce it.

`PAGER=/usr/bin/less dmesg -H` has the issue.
`PAGER=less dmesg -H` doesn't.

**Comment by zeha** [comment]
> Looks like [c10ad97](https://github.com/util-linux/util-linux/commit/c10ad975895372122f72c8d9da089b6ea69f778b) which only applies the `less` quirks when `PAGER=less`

Hmm, that will never work in a default Debian setup, which has less, but less is actually invoked via a number of aliases/wrappers. Not saying that any of the aliasing/wrapping is a great idea, but it is what it is.

**Comment by t-8ch** [comment]
IMO the patch can be reverted, it's only a cleanup and its assumptions don't hold.
