### ISSUE TITLE
2.40 make error

### ISSUE THREAD

**Issue by funnymayo** [util-linux/util-linux#2998]
Centos7.9 

after autogen.sh,I just run ./configure,and it seems good and remain me to type make to complete.
when I run make,it was error.

libblkid/src/probe.c: In function 'blkid_probe_log_csum_mismatch':
libblkid/src/probe.c:1974:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < hex_size; i+=2) {
  ^
libblkid/src/probe.c:1974:2: note: use option -std=c99 or -std=gnu99 to compile your code

show I do something different in ./configure or make? or ./autogen.sh

**Comment by t-8ch** [comment]
Try "CFLAGS=-std=c99 ./configure"

**Comment by funnymayo** [comment]
> Try `CFLAGS="-std=c99" ./configure`

thanks for answer

I have try the option like "make CFLAGS="-std=c99"",and it can make now,but new error become.

and I found it was gcc version too low which cause the error.  Centos7.9 gcc is 4.8.5,I have try gcc 7.3,now I can run autogen.sh configure make sucessfully.But after I run "make install" and reboot,the system can not work any more.

I think is something change in kennel make this~

**Comment by t-8ch** [comment]
> But after I run "make install" and reboot,the system can not work any more.

`util-linux` is an important system component.
Manually installing another version of it into an existing system is risky.

**Comment by funnymayo** [comment]
I think you are right~

Thank you very much~
