### ISSUE TITLE
Build issue 2.40.1

### ISSUE THREAD

**Issue by milkylainen** [util-linux/util-linux#3034]
../util-linux-2.40.1/meson.build:910:23: ERROR: <PythonExternalProgram 'false' -> ['/usr/bin/false']> is not a valid python or it is missing distutils

It is working with the same configuration line for 2.40.
Tbh, not sure what the error is trying to tell me.
/usr/bin/false is perfectly fine, as it's always been.

**Comment by karelzak** [comment]
I guess https://github.com/util-linux/util-linux/pull/3039 fixes python related issues in v2.40 branch

**Comment by milkylainen** [comment]
Confirmed. Changes in #3039 fixes my build issue.
