### ISSUE TITLE
command "lscpu -e" hangs/loops when output column width greater than tty column width

### ISSUE THREAD

**Issue by mimu001** [util-linux/util-linux#3046]
My assumption is that the behaviour which was introduced with commit:

846ae2dcf libsmartcols: make columns reduction more backward compatible

was not intended.

It can be reproduced with:

git checkout 846ae2dcf
make clean && ./autogen.sh && ./configure && make lscpu

run a command that has a column width larger than tty columns available in the tty

stty cols 80
lscpu -e=BOGOMIPS,CPU,CORE,SOCKET,DRAWER,BOGOMIPS,BOGOMIPS,BOGOMIPS,BOGOMIPS,BOGOMIPS,BOGOMIPS

-> hang/loop on scols_print_table()

and 

stty cols 100
lscpu -e=BOGOMIPS,CPU,CORE,SOCKET,DRAWER,BOGOMIPS,BOGOMIPS,BOGOMIPS,BOGOMIPS,BOGOMIPS,BOGOMIPS

works without problem

The issue surfaced on arch s390x as the default width for "lscpu -e" is greater 80.
But it can be reproduced on x86_64 with the above shown commands.

**Comment by karelzak** [comment]
Good catch, thanks!

**Comment by mimu001** [comment]
Thanks for caring promptly!
