### ISSUE TITLE
Rename command sets basename of file to zero length if a rename of the suffix is attempted

### ISSUE THREAD

**Issue by FaradayLight** [util-linux/util-linux#3071]
When attempting a rename of the suffix of a file thus:

``
rename -v .htm .html *.htm
``

The file name is changed thus:

``
`test_03.htm'` -> `.html'
``

Issue is apparent in:

``
% rename -V
rename from util-linux 2.40.1
``

The issue appears to have been introduced with version 2.40.0 based on the date (prior to the release of 2.40.1) at which I first became aware of the issue.

Platform:
% sw_vers 
ProductName:            macOS
ProductVersion:         14.5
BuildVersion:             23F79

Util-linux package installed using MacPorts:
``
MacPorts 2.9.3
``

Ports package version:
``
util-linux @2.40.1 (devel)
``

**Comment by karelzak** [comment]
It works for me (on Linux):
```
$ touch test_0{1,2,3,4,5}.htm
$ ls -la
total 0
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_01.htm
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_02.htm
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_03.htm
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_04.htm
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_05.htm

$ rename -v .htm .html *.htm
`test_01.htm' -> `test_01.html'
`test_02.htm' -> `test_02.html'
`test_03.htm' -> `test_03.html'
`test_04.htm' -> `test_04.html'
`test_05.htm' -> `test_05.html'

$ ls-la
total 0
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_01.html
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_02.html
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_03.html
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_04.html
-rw-r--r-- 1 kzak kzak 0 Jun  3 09:42 test_05.html
```

**Comment by ryandesign** [comment]
I can reproduce the problem on macOS 12 with util-linux 2.40.1 installed by MacPorts. Here is the corresponding MacPorts issue: https://trac.macports.org/ticket/70186

**Comment by ryandesign** [comment]
I confirmed the issue occurs when building master manually outside of MacPorts. I confirmed v2.39.4 does not have the issue when built the same way. I am now running `git bisect` to find out when it broke.

**Comment by ryandesign** [comment]
It broke in 7b67193a53209907f84a6253dcf3aceaf2eb8da1. Reverting this on top of master fixes the problem.

```
% cat try.sh
#!/bin/sh
dir=$(cd "$(dirname "$0")" && pwd)
./autogen.sh || exit 125
CFLAGS="-Wno-implicit-function-declaration -Wno-int-conversion" ./configure --disable-silent-rules || exit 125
make clean || exit 125
make -j8 rename || exit 125
rm -rf /tmp/test
mkdir /tmp/test || exit 125
cd /tmp/test
touch foo.htm || exit 125
"$dir"/rename -v .htm .html *.htm || exit 125
test -e foo.html
% git bisect start
% git bisect bad master
% git bisect good v2.39.4
% time git bisect run ./try.sh
...
7b67193a53209907f84a6253dcf3aceaf2eb8da1 is the first bad commit
commit 7b67193a53209907f84a6253dcf3aceaf2eb8da1
Author: Thomas Weißschuh <thomas@t-8ch.de>
Date:   Tue Dec 5 00:06:59 2023 +0100

    rename: properly handle directories with trailing slash
    
    Instead of hand-rolling a basename() function use the standard one which
    provides the functionality that we want to use.
    
    Also add a testcase.
    
    Fixes #2569
    Signed-off-by: Thomas Weißschuh <thomas@t-8ch.de>

 misc-utils/rename.c         | 8 ++------
 tests/expected/rename/basic | 1 +
 tests/ts/rename/basic       | 4 ++++
 3 files changed, 7 insertions(+), 6 deletions(-)
bisect found first bad commit
git bisect run ./try.sh  452.95s user 266.48s system 87% cpu 13:44.35 total
% git revert -n 7b67193a53209907f84a6253dcf3aceaf2eb8da1
% ./try.sh; echo $?
...
`foo.htm' -> `foo.html'
0
```

**Comment by glensc** [comment]
Indeed, lost some files because didn't expect rename command to be broken.

I recommend using `-i` option. Or even better adding it as alias:

```sh
alias rename="rename -i"
alias mv="mv -i"
```

also attaching reproducer on macOS:

```
❯ mkdir bug-3071
❯ cd bug-3071
❯ touch test_0{1,2,3,4,5}.htm
❯ rename -v .htm .html *.htm
`test_01.htm' -> `.html'
`test_02.htm' -> `.html'
`test_03.htm' -> `.html'
`test_04.htm' -> `.html'
`test_05.htm' -> `.html'
❯ ls -la
total 0
drwxr-xr-x  3 glen staff  96 Jun 27 14:09 ./
drwxr-xr-x 21 glen staff 672 Jun 27 14:09 ../
-rw-r--r--  1 glen staff   0 Jun 27 14:09 .html
❯ rename --version
rename from util-linux 2.40.1
```

could it somehow be filesystem related, as same did not happen when ran via docker alpine image:

```
❯ docker run --rm -it -w /app -v `pwd`:/app alpine sh -xc "apk add util-linux >/dev/null; rename -v .htm .html *.htm; rename --version"
+ apk add util-linux
+ rename -v .htm .html test_01.htm test_02.htm test_03.htm test_04.htm test_05.htm
`test_01.htm' -> `test_01.html'
`test_02.htm' -> `test_02.html'
`test_03.htm' -> `test_03.html'
`test_04.htm' -> `test_04.html'
`test_05.htm' -> `test_05.html'
+ rename --version
rename from util-linux 2.40.1
```

**Comment by glensc** [comment]
I'm guessing `basename(2)` from macOS  behaves differently for dot files.

I'm misreading the effect of 7b67193a53209907f84a6253dcf3aceaf2eb8da1 or toolchain is different than compiled on brew

- [bug-3071.c](https://github.com/user-attachments/files/16012706/bug-3071.c.txt)

```
❯ gcc bug-3071.c -o bug-3071.$(uname -o).$(uname -m)
❯ ./bug-3071.Darwin.arm64 .html
[.html]
```

```
❯ docker run --rm -it -w /app -v `pwd`:/app alpine sh -xc 'apk add alpine-sdk >/dev/null; gcc bug-3071.c -o bug-3071.$(uname -o).$(uname -m); ./bug-3071.Linux.aarch64 .html'
+ apk add alpine-sdk
+ uname -o
+ uname -m
+ gcc bug-3071.c -o bug-3071.Linux.aarch64
+ ./bug-3071.Linux.aarch64 .html
[.html]
```

**Comment by Bo98** [comment]
`basename()` is documented as follows:

> The basename() function may modify the string pointed to by `path`, and may return a pointer to static storage that may then be overwritten by a subsequent call to basename().

https://pubs.opengroup.org/onlinepubs/000095399/functions/basename.html

While I don't know which platforms will modify the input string, BSDs like macOS do definitely return static storage. As a result the usage of `basename` here is totally unsafe. The current code assumes that the input and output point to the same string:

https://github.com/util-linux/util-linux/blob/7b67193a53209907f84a6253dcf3aceaf2eb8da1/misc-utils/rename.c#L86-L90.

`orig` and `where` on BSD platforms (including macOS) will actually be completely separate buffers.

**Comment by karelzak** [comment]
I agree that basename() is problematic; maybe the best solution is to add a local ul_basename() implementation that is independent of libc (or ifndef __GLIBC__). Please, try this patch:

```diff
diff --git a/misc-utils/rename.c b/misc-utils/rename.c
index 9ab38695f..7b5dfbc8d 100644
--- a/misc-utils/rename.c
+++ b/misc-utils/rename.c
@@ -49,6 +49,37 @@ static int tty_cbreak = 0;
 static int all = 0;
 static int last = 0;
 
+/* This is a libc-independent version of basename(), which is necessary to maintain
+ * functionality across different libc implementations. It was inspired by the behavior
+ * and implementation of glibc.
+ */
+static char *ul_basename(char *path)
+{
+       char *p;
+
+       if (!path || !*path)
+               return (char *) ".";    /* ugly, static string */
+
+       p = strrchr(path, '/');
+       if (!p)
+               return path;            /* no '/', return entire string */
+
+       if (*(p + 1) != '\0')
+               return p + 1;           /* begin of the name */
+
+       while (p > path && *(p - 1) == '/')
+               --p;                    /* remove tailing '/' */
+
+       if (p > path) {
+               *p-- = '\0';
+               while (p > path && *(p - 1) != '/')
+                       --p;
+       } else while (*(p + 1) != '\0')
+               ++p;
+
+       return p;
+}
+
 /* Find the first place in `orig` where we'll perform a replacement. NULL if
    there are no replacements to do. */
 static char *find_initial_replace(char *from, char *to, char *orig)
@@ -59,7 +90,7 @@ static char *find_initial_replace(char *from, char *to, char *orig)
                /* We only want to search in the final path component. Don't
                   include the final '/' in that component; if `from` is empty,
                   we want it to first match after the '/', not before. */
-               search_start = basename(orig);
+               search_start = ul_basename(orig);
        }
 
        return strstr(search_start, from);
```

@t-8ch, any objection or suggestion?

**Comment by FaradayLight** [comment]
Hi, there appears to be an issue arising from this fix as observed in the latest release of the MacPorts package of the code.

Re-running the test detailed in :https://github.com/util-linux/util-linux/issues/3071#issuecomment-2144504701

Results in the following error message:
`
rename: test_01.htm: not a symbolic link
rename: test_02.htm: not a symbolic link
rename: test_03.htm: not a symbolic link
rename: test_04.htm: not a symbolic link
rename: test_05.htm: not a symbolic link
`

Environment details as in OP except for MacPorts package version:
`Ports package version:
util-linux @2.40.1 (devel)`
