### ISSUE TITLE
wdctl cannot read information about /dev/watchdog

### ISSUE THREAD

**Issue by Damenly** [util-linux/util-linux#3073]
https://github.com/safai-labs/util-linux/commit/247745344f4fb13fc92bc1303cee2c580a4e2980 broke the output of  `wdctl /dev/watchdog `. 

Take softdog as example,
Before:
```
wdctl /dev/watchdog
Device:        /dev/watchdog
Identity:      Software Watchdog [version 0]
Timeout:       60 seconds
Pre-timeout:    0 seconds
FLAG           DESCRIPTION               STATUS BOOT-STATUS
KEEPALIVEPING  Keep alive ping reply          1           0
MAGICCLOSE     Supports magic close char      0           0
PRETIMEOUT     Pretimeout (in seconds)        1           0
SETTIMEOUT     Set timeout (in seconds)       0           0
```
After:
```
wdctl /dev/watchdog
wdctl: cannot read information about /dev/watchdog: No such file or directory
```

After the commit, wdctl tries to read from sysfs directory first. However, for old misc device /dev/watchdog, there is no  such a directory so wdctl just breaks.
Although /dev/watchdog could be a compatible device of /dev/watchdog0, many software may still call wdctl on /dev/watchdog to query watchdog status directly.

**Comment by t-8ch** [comment]
@Damenly Could you try #3082 please?

**Comment by Damenly** [comment]
It works for me. Thanks.
