### ISSUE TITLE
lsblk HOTPLUG does not match /sys/class/block/*/removable

### ISSUE THREAD

**Issue by funny0facer** [util-linux/util-linux#3088]
`lsblk -d -o NAME,HOTPLUG` shows a different HOTPLUG value than `tail /sys/class/block/sda/removable` for my sda device (SATA SSD) with kernel >= 6.9

```
$ LC_ALL=C sudo pacman -Qi util-linux linux
Name            : util-linux
Version         : 2.40.1-1
Description     : Miscellaneous system utilities for Linux
Architecture    : x86_64
URL             : https://github.com/util-linux/util-linux
Licenses        : BSD-2-Clause  BSD-3-Clause  BSD-4-Clause-UC  GPL-2.0-only  GPL-2.0-or-later  GPL-3.0-or-later  ISC  LGPL-2.1-or-later  LicenseRef-PublicDomain
Groups          : None
Provides        : rfkill  hardlink
Depends On      : util-linux-libs=2.40.1  coreutils  file  libmagic.so=1-64  glibc  libcap-ng  libxcrypt  libcrypt.so=2-64  ncurses  libncursesw.so=6-64  pam  readline
                  shadow  systemd-libs  libsystemd.so=0-64  libudev.so=1-64  zlib
Optional Deps   : words: default dictionary for look
Required By     : base  btrfs-assistant  f2fs-tools  fakeroot  mkinitcpio  ntfs-3g  ostree  systemd  zeromq
Optional For    : corectrl  e2fsprogs  gzip
Conflicts With  : rfkill  hardlink
Replaces        : rfkill  hardlink
Installed Size  : 14.47 MiB
Packager        : Christian Hesse <eworm@archlinux.org>
Build Date      : Mon May 6 21:22:23 2024
Install Date    : Wed May 8 00:26:49 2024
Install Reason  : Installed as a dependency for another package
Install Script  : No
Validated By    : Signature

Name            : linux
Version         : 6.9.3.arch1-1
Description     : The Linux kernel and modules
Architecture    : x86_64
URL             : https://github.com/archlinux/linux
Licenses        : GPL-2.0-only
Groups          : None
Provides        : KSMBD-MODULE  VIRTUALBOX-GUEST-MODULES  WIREGUARD-MODULE
Depends On      : coreutils  initramfs  kmod
Optional Deps   : wireless-regdb: to set the correct wireless channels of your country
                  linux-firmware: firmware images needed for some devices [installed]
Required By     : None
Optional For    : base
Conflicts With  : None
Replaces        : virtualbox-guest-modules-arch  wireguard-arch
Installed Size  : 134.12 MiB
Packager        : Jan Alexander Steffens (heftig) <heftig@archlinux.org>
Build Date      : Fri May 31 17:14:45 2024
Install Date    : Sun Jun 2 15:32:06 2024
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

```
 I had some discussion on this over on the Arch Linux forum. See here: https://bbs.archlinux.org/viewtopic.php?pid=2175987#p2175987

it seems like lsblk is checking in a wrong directory "sdaable"
I can't post the complete output of strace here as this exceeds 65536 characters.

**Comment by t-8ch** [comment]
That `removable` attribute represents `GENHD_FL_REMOVABLE` which is for block devices where the media can be removed but the block device stays, like a CDROM drive.

That is exposed by `lsblk -o +RM`.

(You can attach longer logfiles as attachment to the issue)

**Comment by funny0facer** [comment]
hm. this value does indeed match. thanks for clarifying.

still, the "sdaable" looks strange to me in the strace output `LC_ALL=C strace lsblk -o NAME,HOTPLUG &> strace.txt`
[strace.txt](https://github.com/user-attachments/files/15810940/strace.txt)

**Comment by t-8ch** [comment]
A bit of background:

There are two different kinds of "removable" sysfs attributes in the kernel.

One is on "block" devices (/sys/class/block/sda/). It contains 0 or 1. It actually means "it is changable media, like CDROM". The media can change but the device will stay.
(Backed by `struct gendisk::flags & GENHD_FL_REMOVABLE`)

Then there is hotpluggable. It is also stored in a "removable" attribute. But it contains "fixed"/"removable"/"unknown".
(Backed by `struct device::removable`)

The two removable attributes are never in the same directory as they are created in different parts of the sysfs hierarchy.
To detect if a device is hotpluggable the ancestors of the device are inspected.

So in torvalds/linux@45b96d65ec68f625ad26ee16d2f556e29f715005 the flag `PORT_CMD_HPCP` is now translated into `ap->pflags |= ATA_PFLAG_EXTERNAL;`.
That in turn sets a flag in `ata_scsiop_inq_std()` which gets read back in `scsi_add_lun()` into `struct scsi_dev::removable`.
That in turn gets evaluated in `sd_probe()` and translated into `GENHD_FL_REMOVABLE`.

Leading it to be treated like a media-changable device.

I would argue that a scsi disk should not use `GENHD_FL_REMOVABLE`. But that code is also used for actual cdrom drives.

It's a mess.

But as that is a userspace regression it should be reported and the commit will be reverted in the kernel.
This gives everybody time to figure out how to proceed.

**Comment by t-8ch** [comment]
> still, the "sdaable" looks strange to me

I see. In my trace some other incorrect path is read. But that should not make a difference here, but be an unrelated bug.

**Comment by t-8ch** [comment]
> still, the "sdaable" looks strange to me

That should be fixed by #3089

**Comment by funny0facer** [comment]
no open point here anymore. thanks for having a look!

**Comment by t-8ch** [comment]
Well, somebody needs to report this to the kernel.
If you do, please post a link here.

**Comment by t-8ch** [comment]
See also https://github.com/storaged-project/udisks/issues/1282

**Comment by funny0facer** [comment]
unfortunately, I do not have to knowledge and time at the moment to fullfill the guideline at https://docs.kernel.org/admin-guide/reporting-issues.html

**Comment by t-8ch** [comment]
I'll write something tomorrow then.

**Comment by t-8ch** [comment]
https://lore.kernel.org/regressions/c0de8262-dc4b-4c22-9fac-33432e5bddd3@t-8ch.de/
