### ISSUE TITLE
lsmem: displays all node information

### ISSUE THREAD

**Issue by biubiuzy** [util-linux/util-linux#3110]
Currently, if there is no node for the first memory block,the subsequent nodes are not printed..
https://github.com/util-linux/util-linux/blob/master/sys-utils/lsmem.c#L498
Can we print all the node information?
![image](https://github.com/util-linux/util-linux/assets/24835721/1bc85a4d-5b98-49fb-aee5-b7cdf53f02c2)

**Comment by biubiuzy** [comment]
Is this customary for only the first memory node is judged? @karelzak

**Comment by karelzak** [comment]
I have commented on your PR.
