### ISSUE TITLE
Bug: libmount does not release file descriptors properly on corrupt ISO file mounting

### ISSUE THREAD

**Issue by siyia2** [util-linux/util-linux#3123]
I am trying to integrate libmount into my program that mounts .iso files but i always hit an issue, here is my implementation:

```
struct libmnt_context *ctx = mnt_new_context();
if (!ctx) {
    std::stringstream errorMessage;
    errorMessage << "\033[1;91mFailed to create mount context for: \033[1;93m'" << isoFile << "'\033[0m";
    {
        std::lock_guard<std::mutex> lowLock(Mutex4Low);
        mountedFails.insert(errorMessage.str());
    }
    return;
}

mnt_context_set_source(ctx, isoFile.c_str());
mnt_context_set_target(ctx, mountPoint.c_str());
mnt_context_set_options(ctx, "loop,ro");

bool mountSuccess = false;
std::string successfulFsType;

for (const auto& fsType : fsTypes) {
    if (fsType != "auto") {
        mnt_context_set_fstype(ctx, fsType.c_str());
    } else {
        mnt_context_set_fstype(ctx, NULL);
    }

    int ret = mnt_context_mount(ctx);
    if (ret == 0) {
        mountSuccess = true;
        successfulFsType = fsType;
        break;
    }

    mnt_reset_context(ctx);
    mnt_context_set_source(ctx, isoFile.c_str());
    mnt_context_set_target(ctx, mountPoint.c_str());
    mnt_context_set_options(ctx, "loop,ro");
}

mnt_free_context(ctx);
```

`mnt_free_context(ctx);`` does not release resources but only upon failed mount attempts due to corrupt ISOs. So attempting to mount them over and over again causes resource exhaustion with error: too many files open.

Workarounds on my end:

1)List and skip corrupt .iso files from mounting process (works).
2)Increase ulimit -n.
3)Use shell command mount - o loop (works but is slower).

However these do not address the main issue with libmount.

**Comment by siyia2** [comment]
Problem was on my end, instead of resetting context each time i had to clear and create a new to avoid resource leak.

**Comment by karelzak** [comment]
It would be nice to have debug output from libmount. Please add `mnt_init_debug(0);` to your code (before mny_new_context() or so) and call your program with the "LIBMOUNT_DEBUG=all" env variable.

**Comment by karelzak** [comment]
Note that it should be possible to use the list of filesystem types, something like:
```C
struct libmnt_context *ctx = mnt_new_context();
mnt_context_set_source(ctx, isoFile.c_str());
mnt_context_set_target(ctx, mountPoint.c_str());
mnt_context_set_options(ctx, "loop,ro");

mnt_context_set_fstype(ctx, "vfat,ext4,btrfs");
mnt_context_mount(ctx);
````

And libmount will try all the types. Alternatively, you can use NULL as fstype and use `mnt_context_set_fstype_pattern()`.

**Comment by siyia2** [comment]
Tried debugging nothing useful was reported, but i followed your advice and implemented like this:

```
// Create a libmount context
	struct libmnt_context *ctx = mnt_new_context();
	if (!ctx) {
		std::stringstream errorMessage;
		errorMessage << "\033[1;91mFailed to create mount context for: \033[1;93m'" << isoFile << "'\033[0m";
		mountedFails.insert(errorMessage.str());
		return;
	}

	// Set common mount options
	mnt_context_set_source(ctx, isoFile.c_str());
	mnt_context_set_target(ctx, mountPoint.c_str());
	mnt_context_set_options(ctx, "loop,ro");

	// Set filesystem types to try
	std::string fsTypeList = "iso9660,udf,hfsplus,rockridge,joliet,isofs";
	mnt_context_set_fstype(ctx, fsTypeList.c_str());

	// Attempt to mount
	int ret = mnt_context_mount(ctx);

	bool mountSuccess = (ret == 0);
	std::string successfulFsType;

	if (mountSuccess) {
		// If successful, we can get the used filesystem type
		const char* usedFsType = mnt_context_get_fstype(ctx);
		if (usedFsType) {
			successfulFsType = usedFsType;
		}
	}

	// Clean up the context
	mnt_free_context(ctx);
```

and problem seems to be gone, but i ll check further.

**Comment by siyia2** [comment]
After some rigorous testing i cannot detect the issue, either resource leak became much smaller and is undetectable or it does not exist any more. OMG speed increase is insane, compared to mounting with `mount - o loop` shell command, it is 100% faster!!!

**Comment by siyia2** [comment]
issue never came back problem was with my implementation, closing...
