### ISSUE TITLE
Autotools: uuid.pc does not contain -lpthread for static libuuid.a

### ISSUE THREAD

**Issue by neheb** [util-linux/util-linux#3210]
Causes problems for old glibc that does not have libpthread in libc. Undefined references to pthread functions.

Meson is not impacted as it deals with this.

**Comment by neheb** [comment]
Related: https://github.com/openwrt/openwrt/pull/16449

**Comment by karelzak** [comment]
Thanks! It should be fixed now.

**Comment by neheb** [comment]
@karelzak almost

If --disable-shared is passed, Libs.private are supposed to be promoted to Libs. This is how meson does it when passing -Ddefault_library=static.

**Comment by neheb** [comment]
Effectively it means we have to carry this patch: https://github.com/openwrt/openwrt/pull/16480/commits/3669dfa829d8714926e273fe9951bb893f44536e

Or just wait for next stable release to switch to meson.

**Comment by karelzak** [comment]
I'm not sure if I understand. The current (in git tree) uuid.pc returns the right options for `pkg-config --libs` and `pkg-config --libs --static`. I do not see why we need to change anything here.

**Comment by bkuhls** [comment]
This patch breaks the build of erofs-utils with non-threaded toolchains:
https://autobuild.buildroot.net/results/582/5827995db2a805e0c8a04fde8498eff6f28aa6d8//build-end.log
```
checking for uuid... yes
checking libuuid usability... no
configure: error: libuuid doesn't work properly
```
https://autobuild.buildroot.net/results/582/5827995db2a805e0c8a04fde8498eff6f28aa6d8//erofs-utils-1.8.10/config.log
```
/home/autobuild/autobuild/instance-1/output-1/host/lib/gcc/xtensa-buildroot-linux-uclibc/14.3.0/../../../../xtensa-buildroot-linux-uclibc/bin/ld: cannot find -lpthread: No such file or directory
```
Removing -lpthread from libuuid/uuid.pc.in fixes the problem, both packages do not depend on threads.

**Comment by neheb** [comment]
interesting. Seems to be guarded by HAVE_LIBPTHREAD

edit: meson build seems unconditionally enable it.

edit2: https://github.com/util-linux/util-linux/pull/3833  maybe...

**Comment by bkuhls** [comment]
> edit2: [#3833](https://github.com/util-linux/util-linux/pull/3833) maybe...

The autotools-based build system, where I am seeing this error, is not fixed by your patch.
Is autotools still maintainted or do you advise to switch to meson?

**Comment by neheb** [comment]
I personally advice meson usage yes.

Autotools is still maintained, yes. No idea if an autotools equivalent to the meson PR will be made.

**Comment by bkuhls** [comment]
> No idea if an autotools equivalent to the meson PR will be made.

sent PR: https://github.com/util-linux/util-linux/pull/3973
