### ISSUE TITLE
Ubuntu 18.04 CI broken

### ISSUE THREAD

**Issue by hramrach** [util-linux/util-linux#3215]
/usr/bin/docker exec  90a3de3652fb2e69b0cf70fc8567dba6b1a25bf1a6645236d19bb6f1486c6158 sh -c "cat /etc/*release | grep ^ID"
19
/__e/node20/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)

**Comment by t-8ch** [comment]
This is due to 75f3568

**Comment by karelzak** [comment]
I think that downgrading is a temporary solution only. It would probably be better to say goodbye to the old Ubuntu. @t-8ch, what do you think?

**Comment by hramrach** [comment]
Unlike with the other depends I don't see a notice about checkout@v1 being deprecated so it can probably be used for a while.

**Comment by karelzak** [comment]
OK, I'll merge the downgrade patch.
