### ISSUE TITLE
BlueStore now replicates its signatures

### ISSUE THREAD

**Issue by guits** [util-linux/util-linux#3219]
```console
[ceph: root@osd0 /]# wipefs -a /dev/vdp 
/dev/vdp: 22 bytes were erased at offset 0x00000000 (ceph_bluestore): 62 6c 75 65 73 74 6f 72 65 20 62 6c 6f 63 6b 20 64 65 76 69 63 65
[ceph: root@osd0 /]# ceph-bluestore-tool show-label --dev /dev/vdp
{
    "/dev/vdp": {
        "osd_uuid": "cce4701f-1739-4421-8193-d316bc870914",
        "size": 53687091200,
        "btime": "2024-09-24T19:51:27.676110+0000",
        "description": "main",
        "bfm_blocks": "13107200",
        "bfm_blocks_per_key": "128",
        "bfm_bytes_per_block": "4096",
        "bfm_size": "53687091200",
        "bluefs": "1",
        "ceph_fsid": "1b1e5892-74e9-11ef-801f-525400ea98c9",
        "ceph_version_when_created": "ceph version 19.3.0-4917-g8293d73f (8293d73f8690540e843a81caec373f9cc29cf705) squid (dev)",
        "created_at": "2024-09-24T19:51:30.386821Z",
        "elastic_shared_blobs": "1",
        "epoch": "16",
        "kv_backend": "rocksdb",
        "magic": "ceph osd volume v026",
        "multi": "yes",
        "osd_key": "AQA+GPNmB3WRKBAA6SBzvcCK0xs85gaBs+iADA==",
        "ready": "ready",
        "type": "bluestore",
        "whoami": "0"
    }
}
``` 
Depending on the size of the device, BlueStore now replicates its metadata to multiple places : 1GB / 10GB / 100GB / 1000GB
See corresponding Ceph PR : https://github.com/ceph/ceph/pull/55374

**Comment by karelzak** [comment]
The goal of the wipefs is to make the signatures invisible for system tools (libblkid). The goal is not to erase everything related to the signature from the device. It's not unusual that signature-specific tools can recover from wipefs.

It would be possible to improve libblkid/wipefs to check more places on the device, but this is rarely a good idea as it will detect devices where on-device stuff is incomplete or broken. It's usually better to make such devices invisible to the system and assume manual intervention from the user.

**Comment by karelzak** [comment]
Or we can introduce something like "wipe" mode for libblkid, and in this case, libblkid will probe for all possible locations.

**Comment by rabin-io** [comment]
Thanks for the update, indeed we also encountered this problem and had to create a workaround for exactly this situation. It would have been nice if `wipefs` could handle it as well.

**Comment by guits** [comment]
@rabin-io we ended up implementing a `ceph-bluestore-tool zap-device` command that takes care of wiping all bluestore metadata on a given device.

**Comment by rabin-io** [comment]
Can you share it?

**Comment by guits** [comment]
@rabin-io i'm not sure what you are asking exactly here.
All I'm saying is that the `ceph-bluestore-tool` binary, provided by the ceph-osd package, now includes a new subcommand, `zap-device`, to completely wipe BlueStore metadata altogether on a given disk. I'm unsure what your exact scenario is, but in any case, based on @karelzak's clarifications, I don't think this is the right place to discuss it further. I suggest opening a ticket in the Ceph tracker [here](https://tracker.ceph.com/).
