### ISSUE TITLE
Feature request: Please add an fsck target for oss-fuzz

### ISSUE THREAD

**Issue by ramosian-glider** [util-linux/util-linux#3222]
Kernel developers working on file systems rely on fsck to decide whether or not a filesystem image is valid. For example, it is a popular recommendation to run fsck on an image before letting the kernel mount it.

But given the complexity of file system parsing, fsck itself may contain bugs that may result in it incorrectly handling corrupt FS images.

Would it be possible to add an oss-fuzz target for fsck, so that it is extensively tested on invalid images?

**Comment by t-8ch** [comment]
The fsck in util-linux does not look at the filesystems itself.
Instead it only calls the correct filesystem-specific fsck implementation.

https://github.com/util-linux/util-linux/blob/master/disk-utils/fsck.c

**Comment by ramosian-glider** [comment]
Oh, my bad. I will direct the question about fuzzing to Ted then.
