### ISSUE TITLE
mount: mount the same block device twice

### ISSUE THREAD

**Issue by biubiuzy** [util-linux/util-linux#3251]
Now, we can mount the same block device to the same mount point twice continuously, it's OK?
```
[root@localhost tmp]# mount /dev/loop0 mnt/
[root@localhost tmp]# mount /dev/loop0 mnt/
[root@localhost tmp]# mount| grep loop0
/dev/loop0 on /tmp/mnt type ext4 (rw,relatime)
/dev/loop0 on /tmp/mnt type ext4 (rw,relatime)
[root@localhost tmp]#

```
This will report an error before.
```
[root@localhost tmp]# mount /dev/loop0 /tmp/mnt
[root@localhost tmp]# mount /dev/loop0 /tmp/mnt
mount: /tmp/mnt: /dev/loop0 already mounted on /tmp/mnt.
[root@localhost tmp]#
```

**Comment by karelzak** [comment]
From a userspace point of view, it's fine as it has never been controlled by mount(8)/libmount (well, with the exception of unprivileged user mounts).  This behavior depends on the kernel filesystem driver and its filesystem-specific. For example, it was always possible to do that with NFS, tmpfs, ...). 

Anyway, it was impossible with ext4, which means a new mount API introduced this regression. The old mount(2) syscall works as expected:
```
# mount /dev/loop0 /mnt/test
# LIBMOUNT_FORCE_MOUNT2=always mount /dev/loop0 /mnt/test
mount: /mnt/test: /dev/loop0 already mounted on /mnt/test.
       dmesg(1) may have more information after failed mount system call.
```

Please report this to the kernel (fs or ext4) developers (linux-fsdevel@vger.kernel.org).
