### ISSUE TITLE
`nsenter` `--env` switch hangs

### ISSUE THREAD

**Issue by raesene** [util-linux/util-linux#3270]
Adding the `--env` switch to an `nsenter` command causes it to hang and not return to the user.

Tested on 

 - Ubuntu 24.04 with `nsenter from util-linux 2.39.3`
 - Ubuntu 24.10 with `nsenter from util-linux 2.40.2`
 - Fedora Workstation with `nsenter from util-linux 2.40.2`

## Reproduction

The use case is getting the environment from a process running in Docker.

Docker version `27.3.1` installed from the Docker repositories.

1. `docker run -d nginx`
2. `ps -fC nginx` - Taking note of the PID from the main nginx process
3. First run `sudo nsenter -t $PID -a env` and the command runs successfully but shows the current environment
4. Then try `sudo nsenter -t $PID -a --env env` and the command hangs apparently indefinitely, instead of showing the environment from the contained process.

If there's more information that would be useful in troubleshooting this, let me know!

**Comment by karelzak** [comment]
Thanks for a nice reproducer. 

I can reproduce it with v2.39.x, but it works as expected with the current git-tree, where we have re-implemented how `/proc/#/environ` is read and parsed.

**Comment by karelzak** [comment]
> nsenter: failed to get environment variables: Success

It seems incorrect. The environ[] could be without NAME=value items. I'll fix it.
