### ISSUE TITLE
agetty: rethink the usage of multiple issue files 

### ISSUE THREAD

**Issue by karelzak** [util-linux/util-linux#3279]
https://github.com/systemd/systemd/issues/35071

> Oh, this won't work because agetty implements a logic where it won't even look at /run/issue.d if /etc/issue exists. I expected this to work like systemd dropins, i.e. I create /run/issue.d/sshd.issue and put some text there and it is printed after the default text from /etc/issue. But this does not happen unless I remove /etc/issue. This makes the scheme essentially useless… @karelzak can we change the logic to allow dropins from /run to be read even if /etc/issue is present?

**Comment by karelzak** [comment]
The new implementation does not support drop-ins 
https://uapi-group.org/specifications/specs/configuration_files_specification/

It would be nice to improve it to take into account the precedence of the files.

**Comment by keszybz** [comment]
Yeah, I think we had a miscommunication here. "I expected this to work like systemd dropins" — systemd looks for the main file and each drop-in with a unique name through the whole hierarchy, so it is possible to (separately) provide and override both the main file and each of the drop-ins.

**Comment by karelzak** [comment]
Yes, I missed the note about the drop-in in the original report (sorry). I thought you just didn't like the original unusual /etc/issue semantics, where the file acted as a trigger to read or not read other files.
                                                        
There is also a hermetic-usr request for /etc/login.defs https://github.com/util-linux/util-linux/issues/3444. Would this also be the place where we can use drop-in logic?               
                                                        
I'll probably create a simple library (for util-linux only, a shared and distributed library is probably overkill) to implement this multiple path ordering logic.

**Comment by keszybz** [comment]
> There is also a hermetic-usr request for /etc/login.defs [#3444](https://github.com/util-linux/util-linux/issues/3444). Would this also be the place where we can use drop-in logic?

Yes, certainly.



> I'll probably create a simple library (for util-linux only

That's reasonable. Linking to a separate library to just enumerate a bunch of files is a bit overkill. And with shared code it'll be easy to maintain consistent behaviour in multiple tools.

**Comment by karelzak** [comment]
Should be already implemented by https://github.com/util-linux/util-linux/blob/master/lib/configs.c
