### ISSUE TITLE
bluetooth device blocked by rfkill becomes unblocked after usb device found

### ISSUE THREAD

**Issue by bgx90** [util-linux/util-linux#3324]
### Linux
Kernel: Linux 6.11.10-amd64
Architecture: x86-64

### Issue
This issue is occurring on a Thinkpad W520 laptop. I block all bluetooth devices with `sudo rfkill block bluetooth`. After a reboot, `systemd-rfkill.service` restores this setting and blocks the laptop's builtin bluetooth. If after rebooting I use any of the special fn function keys on the keyboard (for example, fn+f8 to toggle the touchpad), bluetooth becomes unblocked. If I then block the bluetooth again with `sudo rfkill block bluetooth`, the bluetooth is once again blocked and using the special fn function keys no longer causes bluetooth to become unblocked. Watching the dmesg log as I press a fn function key after rebooting, it seems that the first use of any fn function key after a reboot causes the discovery of the laptop's builtin bluetooth device (a usb device), and this is causing the unblocking issue.

dmesg log:

```
[Dec11 14:45] usb 2-1.4: new full-speed USB device number 6 using ehci-pci
[  +0.117668] usb 2-1.4: New USB device found, idVendor=0a5c, idProduct=217f, bcdDevice= 7.48
[  +0.000022] usb 2-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0.000007] usb 2-1.4: Product: Broadcom Bluetooth Device
[  +0.000005] usb 2-1.4: Manufacturer: Broadcom Corp
[  +0.000004] usb 2-1.4: SerialNumber: 60D819B6B7C8
[  +0.225685] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[  +0.000006] Bluetooth: BNEP filters: protocol multicast
[  +0.000006] Bluetooth: BNEP socket layer initialized
[  +0.017168] Bluetooth: MGMT ver 1.23
[  +0.015628] Bluetooth: RFCOMM TTY layer initialized
[  +0.000010] Bluetooth: RFCOMM socket layer initialized
[  +0.000004] Bluetooth: RFCOMM ver 1.11

```

### Expected Behavior
According to the Userspace support section of the [docs](https://docs.kernel.org/driver-api/rfkill.html), "it is possible to switch all rfkill drivers (or all drivers of a specified type) into a state which also updates the default state for hotplugged devices." So, I would expect that all bluetooth devices blocked by rfkill should stay blocked even if  one is (re)discovered.

**Comment by karelzak** [comment]
I doubt this is a rfkill issue. This tool is just a simple wrapper for /dev/rfkill device, and this tool does not implement any policy. I think the right area where to ask for help is systemd (systemd-rfkil or udevdl) or kernel.

**Comment by bgx90** [comment]
I'll close this issue, then. Thanks.
