### ISSUE TITLE
lsblk listing feature (by-id, multipath)

### ISSUE THREAD

**Issue by johnr14** [util-linux/util-linux#616]
Hi, I was creating raid arrays with multiple disks and using multipath, that means lots of information.
I found out that lsblk is the best tool for the job ! 

However, I could not use the /dev/disk/by-id in the device listing. 
So I would like to ask for a feature **_-I_** (capital i) for **listing by-id** and **_-M_** for **multipath removal of duplicates**.

Serial could be used to remove duplicates. Here is an example : lsblk -o name,model,size,label,serial 

```
sdam             ST8000DM004-2CX1   7.3T                         5000c500ac884xxx
├─sdam1                             7.3T                         
├─sdam9                               8M                         
└─mpathq                            7.3T                         
  ├─mpathq-part1                    7.3T Apool                   
  └─mpathq-part9                      8M                         
sdan             ST8000DM004-2CX1   7.3T                         5000c500ac884xxx
├─sdan1                             128M                         
├─sdan2                             7.3T Seagate Expansion Drive 
└─mpathq                            7.3T                         
  ├─mpathq-part1                    7.3T Apool                   
  └─mpathq-part9                      8M       
```  

And expected output of : lsblk -I -M -o name,model,size,label,serial 
```
scsi-SATA_ST8000DM004-2CX1_WCT0BGGX  ST8000DM004-2CX1   7.3T   5000c500ac884xxx                    
└─mpathq                            7.3T                         
  ├─mpathq-part1                    7.3T Apool      
     ├─sdam1                             7.3T          
     └─sdan1                             128M                
  └─mpathq-part9                      8M    
     ├─sdam9 
     └─sdan2    

```
If placing sdam and sdan is too complicated, just the mpathq would do the work. And if multipath is disabled, just the first found name, in this case sdam.
```
scsi-SATA_ST8000DM004-2CX1_WCT0BGGX  ST8000DM004-2CX1   7.3T   5000c500ac884xxx                    
└─mpathq                            7.3T                         
  ├─mpathq-part1                    7.3T Apool         
  └─mpathq-part9                      8M    
```
My workaround was : 
`lsblk -S -o name,model,size,label,serial |grep 7.3T | rev | sort -u -k1,1 | rev`

Thanks
Note that there is a mis-match of partition names, that's because I haven't rebooted since change of partition tables.

**Comment by karelzak** [comment]
I'll think about it :-)

The problem is that lsblk code is currently not ready for some sophisticated evaluation of the tree as it does not save all the tree in memory -- it prints device and dependences without any care about another stuff in the tree. But I don't like it, it's already in my TODO to make it more extendible.

BTW, try --inverse, it maye be more readable in some cases.
