### ISSUE TITLE
feature request: FAT file system support for fstrim

### ISSUE THREAD

**Issue by Vdragon** [util-linux/util-linux#92]
I researched for this issue for a bit, please comment if there's anything wrong :-)
- Currently fs/fat supports 'discard' mount option to enable TRIM in realtime at the expense of I/O performance
- fstrim seemed to be using FITRIM ioctl for trimming, however [the FAT filesystem patch to support this](https://lwn.net/Articles/429692/) still not been merged into the [mainline](http://lxr.free-electrons.com/source/fs/fat/file.c)
- fstrim should be able to trim FAT file system once the FAT filesystem driver supports FITRIM ioctl

**Comment by chrisblizz** [comment]
@Vdragon Why did you close this? I would have found this pretty useful.
